project:
  type: website
  output-dir: docs

execute:
  cache: true
  warning: false
  message: false
  error: false

knitr:
  opts_chunk:
    cache.path: "_cache/"

website:
  title: "Andrés Gutiérrez"
  site-url: https://psirusteam.github.io
  description: "Blog of Andrés Gutiérrez"
  search: true
  navbar:
    left:
      - text: "Books"
        href: books.qmd
      - text: "Software"
        href: software.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Blog"
        href: blog.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    lang: en
