---
title: "Felicitaciones parce!!!"
author: "Andrés Gutiérrez"
date: "2008-09-17"
categories:
  - "Estadística"
---

Continuando con nuestra sección farandulera… Let me indroduce you to Jairo… Es para mí una grato placer saber que un estadístico de la Universidad Nacional de Colombia, discípulo de Leonardo Bautista y ex-funcionario del DANE, ha ganado un [prestigioso premio](http://www.amstat.org/sections/SBSS/) de ASA (Asociación Americana de Estadística).

Se trata de la competición de artículos estudiantiles 2008 de la sección de ciencia estadística Bayesiana de ASA. Las siguientes son las palabras de Jairo (reproducidas de [NotiCampus](http://noticampus.uprrp.edu/texto08008130h.html), página informativa de la Universidad de Puerto Rico).

"Este año participé en el concurso 'Student Paper Competition' que realiza la American Statistical Association y quedé entre los ocho mejores artículos a nivel mundial en el área de Estadística Bayesiana. El impacto de este concurso es tal, que es realizado por la organización más importante de Estadística. El mérito también está en que los demás ganadores obtuvieron el premio con sus tesis doctorales (de universidades como Duke y Rice), otros ya son profesores, y yo era el único realizando estudios de maestría".

"Gané el Premio en Section on Bayesian Statistical Science (SBSS) Student Paper Award en competencia con otros estudiantes de universidades de gran prestigio como: University of Connecticut, Duke University, University of North Carolina, Texas A&M University, University of Michigan Biostatistics y Rice University, entre otras. Finalmente, acabo de someter un artículo (resumen de mi tesis) a una revista que ha tenido en los últimos años un impacto importante: 'Biostatistics' con un profesor titular de la Universidad de Texas y mi director de Tesis (Raúl Pericchi)".

'Sin lugar a dudas estudiar en la Iupi te abre muchas puertas y la considero mi Alma Máter"..

Congratulaciones a Jairo por su importante labor investigativa, pero sobre todas las cosas, porque está demostrando en el exterior de qué estamos hechos los Colombianos.
