---
title: "Historia de la probabilidad (Era moderna)"
author: "Andrés Gutiérrez"
date: "2008-10-25"
categories:
  - "Probability"
  - "Modeling"
---

**Siglo XX**

El siglo XX se ha caracterizado por los avances de la [tecnología](http://es.wikipedia.org/wiki/Tecnolog%C3%ADa); [medicina](http://es.wikipedia.org/wiki/Medicina) y [ciencia](http://es.wikipedia.org/wiki/Ciencia) en general; fin de la esclavitud (al menos nominalmente); liberación de la mujer en la mayor parte de los países; pero también por crisis y despotismos humanos, que causaron efectos tales como las [Guerras Mundiales](http://es.wikipedia.org/wiki/Guerra_mundial); el [genocidio](http://es.wikipedia.org/wiki/Genocidio) y el [etnocidio](http://es.wikipedia.org/wiki/Etnocidio), las políticas de [exclusión](http://es.wikipedia.org/wiki/Exclusi%C3%B3n) social y la generalización del [desempleo](http://es.wikipedia.org/wiki/Desempleo) y de la [pobreza](http://es.wikipedia.org/wiki/Pobreza). Como consecuencia, se profundizaron las inequidades en cuanto al desarrollo social, económico y tecnológico y en cuanto a la distribución de la riqueza entre los países, y las grandes diferencias en la calidad de vida de los habitantes de las distintas regiones del mundo. En los últimos años del siglo, especialmente a partir de [1989](http://es.wikipedia.org/wiki/1989)-[1991](http://es.wikipedia.org/wiki/1991) con el derrumbe de los regímenes colectivistas de [Europa](http://es.wikipedia.org/wiki/Europa), comenzó el fenómeno llamado [globalización](http://es.wikipedia.org/wiki/Globalizaci%C3%B3n) o mundialización.

# 1920-1930

En los años de la gran Guerra (primera guerra mundial entre 1914 y 1918) la probabilidad y la estadística se esparcieron por todos lados. Durante la guerra, la investigación en probabilidad casi se detiene por causa de que la gente se enlistaba en los servicios armados. [Pearson](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm), [Lévy](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) y [Wiener](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) trabajaron en balística, [Jeffreys](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) en meteorología e [Yule](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) en administración.

- En 1900 [David Hilbert](https://mathshistory.st-andrews.ac.uk/Biographies/Hilbert/) propuso un conjunto de [problemas](http://aleph0.clarku.edu/~djoyce/hilbert/problems.html) para el siglo 20. El sexto problema fue, "tratar… por medio de axiomas, aquellas ciencias físicas en las cuales las matemáticas juegan un papel importante; en primer lugar están la teoría de la probabilidad y la mecánica." [La teoría de la medida](https://web.archive.org/web/20260317083125/https://jeff560.tripod.com/m.html), que jugaría un papel muy importante en la axiomatización de la probabilidad, fue creada por [Borel](https://mathshistory.st-andrews.ac.uk/Biographies/Borel/), [Lebesgue](https://mathshistory.st-andrews.ac.uk/Biographies/Lebesgue/) entre otros.

- Desde diferentes campos surgieron contribuciones que eventualmente encontraron lugar en la teoría de los procesos estocásticos. En física, [Einstein](https://mathshistory.st-andrews.ac.uk/Biographies/Einstein/) y [Smoluchovski](https://mathshistory.st-andrews.ac.uk/Biographies/Smoluchowski/) trabajaron en el movimiento [Browniano](https://web.archive.org/web/20260220124513/https://jeff560.tripod.com/b.html). [Bachelier](https://mathshistory.st-andrews.ac.uk/Biographies/Bachelier/) desarrolló un modelo similar aplicado a la especulación financiera; alternamente, el actuario [Lundberg](http://en.wikipedia.org/wiki/Ernest_Filip_Oskar_Lundberg) desarrolló una teoría de riesgo colectivo. –la enfermedad de la malaria y la migración de los mosquitos fueron el foco principal de la investigación de [Pearson](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) originado en el problema de la [caminata aleatoria](https://web.archive.org/web/20260310145716/https://jeff560.tripod.com/r.html). [Ronald Ross](http://en.wikipedia.org/wiki/Ronald_Ross) y [A. G. McKendrick](http://en.wikipedia.org/wiki/Anderson_Gray_McKendrick), sin la referencia del anterior trabajo de [Daniel Bernoulli](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm), crearon modelos matemáticos de epidemias.

- Aunque [Mendel](http://en.wikipedia.org/wiki/Gregor_Mendel) no usó la probabilidad en su trabajo sobre genética (publicado en 1866), sus ideas fueron probabilizadas cuando [Pearson](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm), [Yule](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) y [Fisher](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) investigaron si los principios de la genética podrían racionalizar los hallazgos de los biometristas.

- [Charles Spearman](http://en.wikipedia.org/wiki/Charles_Spearman) (1863-1945) impulsó la correlación y esta empezó a ser parte importante de la sicología. Entre las contribuciones a la estadística estuvieron la [correlación de rangos](https://web.archive.org/web/20260310145716/https://jeff560.tripod.com/r.html) y el [análisis factorial](https://web.archive.org/web/20260408144245/https://jeff560.tripod.com/f.html). [Godfrey Thomson](http://en.wikipedia.org/wiki/Godfrey_Thomson) fue un crítico severo del análisis factorial de la inteligencia basado en el trabajo de Spearman. En la década de 1930 [Louis L. Thurstone](http://www.indiana.edu/~intell/lthurstone.shtml) desarrolló el análisis factorial múltiple.

- En economía, especialmente en los Estados unidos, los métodos cuantitativos empezaron a ser más prominentes. Las figuras más importantes fueron Warren Persons, [Irving Fisher](http://en.wikipedia.org/wiki/Irving_Fisher), [Wesley Mitchell](http://en.wikipedia.org/wiki/Wesley_Clair_Mitchell) and [H. L. Moore](http://en.wikipedia.org/wiki/Henry_Ludwell_Moore). La mayoría de su trabajo se clasificaría en el análisis de series de tiempo.

- Las aplicaciones industriales en probabilidad empezaron con el trabajo de [Erlang](https://mathshistory.st-andrews.ac.uk/Biographies/Erlang/) sobre congestión de sistemas telefónicos, el ancestro de la [teoría de colas](https://web.archive.org/web/20251116012233/https://jeff560.tripod.com/q.html).

- Los desarrollos institucionales incluyen, en 1911 la creación del departamento de estadísticas aplicadas en UCL encabezado por [Pearson](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm). [Yule](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm), podría ser llamado "el primer estadístico moderno".

**1920-1930**

La mayoría de las personas que dominaron la probabilidad y la estadística tuvieron un impacto temprano. De ellos, el individuo que tuvo un mayor impacto fue [Fisher](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) en estadística. El alemán era el idioma tradicional en la literatura científica de la época. Sin embargo, Fisher escribía en inglés pues creía que la época de escritura alema había terminado con Gauss.

- Los avances en probabilidad incluyeron refinamientos del [teorema central del límite](https://web.archive.org/web/20251226073238/https://jeff560.tripod.com/c.html) ([Lindeberg](http://en.wikipedia.org/wiki/Jarl_Waldemar_Lindeberg) hizo una muy importante contribución) y de la [ley fuerte de los grandes números](https://web.archive.org/web/20260305095113/https://jeff560.tripod.com/l.html) y nuevos resultados incluían la [ley del algoritmo dominado](https://web.archive.org/web/20260305095113/https://jeff560.tripod.com/l.html). Hubo contribuciones de la mayoría de los países del continente europeo; por ejemplo, [Mazurkiewicz](https://mathshistory.st-andrews.ac.uk/Biographies/Mazurkiewicz/) de Polonia y en 1935 [Turing](https://mathshistory.st-andrews.ac.uk/Biographies/Turing/) repitió el trabajo de Lindeberg sin saber de su publicación.

- Los fundamentos de la probabilidad recibieron mucha atención y ciertas posiciones encontraron expresiones clásicas: la interpretación lógica de la probabilidad (grado de creencia razonable) fue propuesta por los filósofos de Cambridge, [W. E. Johnson](https://mathshistory.st-andrews.ac.uk/Biographies/Johnson/), [J. M. Keynes](https://mathshistory.st-andrews.ac.uk/Biographies/Keynes/) y [C. D. Broad](http://www.ditext.com/broad/cdbroad.html), y presentada a una audiencia científica por [Jeffreys](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm); el punto de vista [frecuentista](https://web.archive.org/web/20260408144245/https://jeff560.tripod.com/f.html) fue desarrollado por [von Mises](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm).

- En estadística, [R. A. Fisher](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) generó nuevas ideas sobre [estimación](https://web.archive.org/web/20260201120621/https://jeff560.tripod.com/e.html) y juzgamiento de [hipótesis](https://web.archive.org/web/20260422132814/https://jeff560.tripod.com/h.html) y su trabajo de diseño experimental movió este tópico desde los linderos hasta el centro de la estadística. Sus [Métodos estadísticos para investigadores](http://psychclassics.yorku.ca/Fisher/Methods/) (1925) fue el libro más influyente del siglo 20.

- [W. A. Shewhart](http://en.wikipedia.org/wiki/Walter_A._Shewhart) ([ASQ](http://www.asq.org/join/about/history/shewhart.html)) fue el pionero del [control de calidad](https://web.archive.org/web/20251116012233/https://jeff560.tripod.com/q.html), el cual se convirtió en una aplicación muy importante de la estadística en la industria.

**1930-1940**

En contra de una economía en recession y de una política desastrosa, hubo importantes desarrollos en probabilidad, teoría estadística y sus aplicaciones. En la Unión Soviética, a los matemáticos les iba mayor que a los economistas o a los genetistas y pudieron salir de su país y publicar en revistas internacionales; así [Kolmogorov](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) y [Khinchin](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) publicaron en Alemania, donde precisamente los judíos fueron expulsados de la academia desde 1934.

- En probabilidad, los principales desarrollos fueron la axiomatización de la [probabilidad](https://web.archive.org/web/20251113013258/https://jeff560.tripod.com/p.html) por [Kolmogorov](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) y el desarrollo de la teoría de los [procesos estocásticos](https://web.archive.org/web/20260217110036/https://jeff560.tripod.com/s.html) por él y por [Khinchin](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm). Su trabajo es usualmente visto como el comienzo de la probabilidad moderna.

- En los fundamentos de la probabilidad, [Bruno de Finetti](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) y Frank Ramsey (1903-1930) ([St. Andrews](https://mathshistory.st-andrews.ac.uk/Biographies/Ramsey/), [N.-E. Sahlin](http://www.fil.lu.se/sahlin/ramsey/)) trabajaron en la probabilidad subjetiva. Ramsey empezó con el criticismo de la escuela de lógica de Cambridge, en particular Keynes. Una superestructura estadística no se dio sino años [después](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm). [Jeffreys](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) dio un tratamiento complete a la estadística fundamentado en su noción lógica de la probabilidad, aunque la forma prevaleciente era la [clásica](https://web.archive.org/web/20251226073238/https://jeff560.tripod.com/c.html).

- Biometrika detuvo la publicación de la investigación biológica y se enfocó en la estadística teórica. El [Instituto de estadística matemática](http://www.imstat.org/history.htm) fue fundado en 1930 y su revista, [The Annals of Mathematical Statistics](http://www.imstat.org/history.htm) apareció en 1933. El primer laboratorio de estadística en los Estados Unidos fue creado en Iowa por [Snedecor](http://en.wikipedia.org/wiki/George_W._Snedecor) en 1933. Snedecor fue fuertemente influenciado por [Fisher](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm).

- En el campo de la inferencia estadística, el mayor desarrollo fue la teoría del juzgamiento de [hipótesis](https://web.archive.org/web/20260422132814/https://jeff560.tripod.com/h.html) de [Neyman](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm)-Pearson. El [análisis multivariado](https://web.archive.org/web/20260317083125/https://jeff560.tripod.com/m.html) se convirtió en una material identificable, formada por contribuciones como la [distribución Wishart](https://web.archive.org/web/20241204173847/https://jeff560.tripod.com/w.html) (1928), [los componentes principales de Haro](http://www.amstat.org/about/statisticians/index.cfm?fuseaction=biosinfo&BioID=7) ld Hotelling (1933) y la [correlación canónica](https://web.archive.org/web/20251226073238/https://jeff560.tripod.com/c.html) (1936) y el [análisis](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm)[discriminante de Fisher](https://web.archive.org/web/20260217120428/https://jeff560.tripod.com/d.html) (1936).

- Las aplicaciones de las matemáticas y estadísticas a la economía se juntaron en el movimiento [econométrico](https://web.archive.org/web/20260201120621/https://jeff560.tripod.com/e.html). Entre los líderes de la década de 1930 estuvieron [Jan Tinbergen](https://mathshistory.st-andrews.ac.uk/Biographies/Tinbergen/) y [Ragnar Frisch](http://nobelprize.org/economics/laureates/1969/frisch-autobio.html). Los econometristas que ganaron el premio Nobel en economía son Engle, Granger, Haavelmo, Heckman, Klein, McFadden.

**1940-1950**

Entre los millones de muertos de la segunda Guerra mundial se contaron algunos matemáticos y estadísticos. [Doeblin](https://mathshistory.st-andrews.ac.uk/Biographies/Doeblin/) es el más famoso de los finados; uno de los libros de [Neyman](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) está dedicado a la memoria de diez colegas y amigos. Esta guerra incentivó el estudio de la probabilidad y la estadística. Al final de la Guerra, muchas personas se encontraron trabajando como estadísticos, hubo nuevas aplicaciones y la importancia de esta material fue más ampliamente reconocida.

- Las persecuciones Nazis y la segunda guerra mundial empujaron la migración de muchos estadísticos a los Estados Unidos. Algunas de las más importantes figures de la probabilidad en la postguerra en Estados Unidos son: [Feller](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm), [M. Kac](https://mathshistory.st-andrews.ac.uk/Biographies/Kac/) ([MGP](http://www.genealogy.math.ndsu.nodak.edu/html/id.phtml?id=17851)), [Wald](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm), [G. E. P. Box](http://www.asq.org/about-asq/who-we-are/bio_box.html) ([MGP](http://www.genealogy.ams.org/html/id.phtml?id=42226)), [W. G. Cochran](https://mathshistory.st-andrews.ac.uk/Biographies/Cochran/) ([ASA](http://www.amstat.org/about/statisticians/index.cfm?fuseaction=biosinfo&BioID=21)) ([MGP](http://www.genealogy.ams.org/html/id.phtml?id=25897)), [W. Hoeffding](http://www.nap.edu/readingroom/books/biomems/whoeffding.pdf) ([MGP](http://www.genealogy.math.ndsu.nodak.edu/html/id.phtml?id=20681)), [H. O. Hartley](http://www.amstat.org/about/statisticians/bios/hartleyho.pdf) ([MGP](http://www.genealogy.math.ndsu.nodak.edu/html/id.phtml?id=20670)), F. J. Anscombe ([Obit. p. 17](http://www.imstat.org/bulletin/Bulletin31_1.pdf)) ([MGP](http://www.genealogy.math.ndsu.nodak.edu/html/id.phtml?id=62936)), [Z. W. Birnbaum](http://www.math.washington.edu/~sheetz/Obituaries/zwbirnbaum.html) ([MGP](http://www.genealogy.math.ndsu.nodak.edu/html/id.phtml?id=28292)) y [O. Kempthorne](http://www.amstat.org/about/statisticians/index.cfm?fuseaction=biosinfo&BioID=8) ([MGP](http://www.genealogy.ams.org/html/id.phtml?id=43260)).

- Los [métodos no-paramétricos](https://web.archive.org/web/20251108132247/https://jeff560.tripod.com/n.html) empezaron a ser sistemáticamente estudiados, usando técnicas de la teoría de la inferencia estadística; [E. J. G. Pitman](http://www.asap.unimelb.edu.au/bsparcs/aasmemoirs/pitman.htm) fue un pionero importante. Las pruebas estadísticas para el juzgamiento de hipótesis vinieron de no-estadísticos como [Spearman](http://en.wikipedia.org/wiki/Charles_Spearman) ([rangos](https://web.archive.org/web/20260310145716/https://jeff560.tripod.com/r.html)) o [Wilcoxon](http://www.umass.edu/wsp/statistics/tales/wilcoxon.html) ([prueba de Wilcoxon)](https://web.archive.org/web/20241204173847/https://jeff560.tripod.com/w.html). El repertorio conocido de las [pruebas del signo](https://web.archive.org/web/20260217110036/https://jeff560.tripod.com/s.html), [pruebas de permutación](https://web.archive.org/web/20251113013258/https://jeff560.tripod.com/p.html) y [la prueba de Kolmogorov-Smirnov](https://web.archive.org/web/20251129102941/https://jeff560.tripod.com/k.html) se expandieron rápidamente en el medio.

- El análisis moderno de [series de tiempos](https://web.archive.org/web/20251215071646/https://jeff560.tripod.com/t.html) vino de la unión de la teoría de los procesos estocásticos, la teoría de la predicción y la teoría de la inferencia estadística. Uno de los principales pioneros de esta década fue [M. S. Bartlett](http://en.wikipedia.org/wiki/M._S._Bartlett). En la década de 1950 [Tukey](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) fue una figura importante. En la década de 1960, [Kalman](http://en.wikipedia.org/wiki/Rudolf_Kalman) ([filtro de Kalman](https://web.archive.org/web/20251129102941/https://jeff560.tripod.com/k.html)) y los sistemas de ingeniería hicieron importantes contribuciones y en la década de 1970, los métodos de [G. E. P. Box](http://en.wikipedia.org/wiki/George_EP_Box) y [G. M. Jenkins](http://en.wikipedia.org/wiki/Gwilym_Jenkins) ([Box-Jenkins](https://web.archive.org/web/20260220124513/https://jeff560.tripod.com/b.html)) fueron adoptados en la economía y los negocios.

**1950-1980**

Este es un periodo de expansión, más países, más gente, más departamentos, más libros, más revistas. Los computadores empiezan a tener un gran impacto.

- Los departamentos existents de estadística se expanden. Nuevas instituciones son creadas, entre ellas el Laboratorio estadístico en [Cambridge](http://www.statslab.cam.ac.uk/History/2history.html) en 1947 y el [departamento de estadística](http://www.stat.harvard.edu/anniversary/) en Harvard en 1958.

- El alcance de la teoría de la probabilidad se incrementa con el nacimiento de nuevos subcampos como [la teoría de colas](https://web.archive.org/web/20251116012233/https://jeff560.tripod.com/q.html) y la [teoría de la renovación](https://web.archive.org/web/20260310145716/https://jeff560.tripod.com/r.html). El libro de [Feller](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) Introduction to Probability Theory hizo un impacto muy grande en el mundo de habla inglesa pues promovió el estudio de tópicos más avanzados como las [cadenas de Markov](https://web.archive.org/web/20260317083125/https://jeff560.tripod.com/m.html).

- En material estadística hubo un renacimiento Bayesiano. En Estados Unidos, [la teoría de decisión Bayesiana](https://web.archive.org/web/20260220124513/https://jeff560.tripod.com/b.html) reflejó la influencia de la [teoría de la decisión](https://web.archive.org/web/20260217120428/https://jeff560.tripod.com/d.html) de [Wald](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm).

- [W. Edwards Deming](http://www.amstat.org/about/statisticians/index.cfm?fuseaction=biosinfo&BioID=4) continúo el trabajo de [Shewhart](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) en control de calidad y fue muy efectivo a la hora de adoptar estos métodos en la industria.

- [Laplace](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) y [Quetelet](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) vieron el trabajo de los censos como posibles aplicaciones de la probabilidad pero el uso de la teoría estadística para recopilación de información oficial llegó sólo después de las actividades de [Morris Hansen](http://newton.nap.edu/books/0309055415/html/117.html) ([ver entrevista](http://www.census.gov/prod/2003pubs/oh-hanse.pdf)) en la oficina de censos de Estados Unidos.

**1980 + (Los efectos del computador)**

Este periodo describe el efecto impactante de los ordenadores en el desarrollo de métodos estadísticos desde su advenimiento, en la década de 1950 y el dramático cambio en la historia de la probabilidad y la estadística en las recientes décadas. Al final del siglo 19, las [máquinas mecánicas calculadoras](http://www.xnumber.com/xnumber/mechanical2.htm) proveyeron el material para la investigación de [Pearson](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) y [Fisher](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) y la construcción de sus [tablas estadísticas](https://web.archive.org/web/20260217110036/https://jeff560.tripod.com/s.html). Con la disponibilidad de los computadores, las viejas actividades tomaron menos tiempo y nuevas actividades fueron posibles.

- Las tablas estadísticas de números aleatorios fueron mucho más fáciles de producir y luego desaparecieron pues su función fue sometida a los paquetes estadísticos.

- Una gran masa de datos, más grande que en épocas pasadas, puede ser analizada.

- El [Data mining](https://web.archive.org/web/20260217120428/https://jeff560.tripod.com/d.html) exhaustivo es posible.

- Modelos y métodos más complejos pueden ser usados. Los nuevos métodos se han diseñado con idea de la implementación computacional. Por ejemplo, la familia de los [modelos lineales generalizados](https://web.archive.org/web/20260414152920/https://jeff560.tripod.com/g.html) vinculada al programa GLIM (ver [John Nelder](http://stats.ma.ic.ac.uk/jan01/public_html/) [FRS](http://www.royalsoc.ac.uk/DServe/dserve.exe?dsqIni=Dserve.ini&dsqApp=Archive&dsqCmd=Show.tcl&dsqSearch=RefNo=='EC/1981/28'&dsqDb=Catalog)).

- En el siglo 20 cuando [Student](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) (1908) escribió sobre la media normal y [Yule](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) (1926) escribió sobre las correlaciones sin sentido, ellos usaron experimentos basados en muestras y en la década de 1920 valió la pena producir tablas de [números aleatorios](https://web.archive.org/web/20260310145716/https://jeff560.tripod.com/r.html). Esto cambió con la introducción de los métodos asistidos por el computador para la generación de números pseudo-aleatorios, más aún los métodos de [Monte-Carlo](https://web.archive.org/web/20260317083125/https://jeff560.tripod.com/m.html) (introducidos por [von Neumann](https://mathshistory.st-andrews.ac.uk/Biographies/Von_Neumann/) y [Ulam](https://mathshistory.st-andrews.ac.uk/Biographies/Ulam/)) fueron posibles.

- Desde 1980 los métodos de Monte Carlo han sido estudiados y usados directamente en el análisis de datos. En la inferencia clásica, el [bootstrap](https://web.archive.org/web/20260220124513/https://jeff560.tripod.com/b.html) ha sido prominente.
