---
title: "Historia de la probabilidad (Era Primaria)"
author: "Andrés Gutiérrez"
date: "2008-10-04"
categories:
  - "Probability"
  - "Bayesian Statistics"
---

**1650-1700**

En este periodo se encuentran los orígenes de la probabilidad y de la estadística mediante el tratamiento matemático del juego y del estudio sistemático de las cifras de mortalidad. Esta época es conocida como la era de la [revolución científica](http://web.clas.ufl.edu/users/rhatch/pages/03-Sci-Rev/SCI-REV-Home/05-RSW-Sci-Rev.htm) en donde grandes nombres como, [Galileo](https://mathshistory.st-andrews.ac.uk/Biographies/Galileo/) (ver [Materiales](http://www.york.ac.uk/depts/maths/histstat/galileo.pdf) y [Todhunter](http://visualiseur.bnf.fr/Visualiseur? Destination=Gallica&O=NUMM-62103)) y [Newton](https://mathshistory.st-andrews.ac.uk/Biographies/Newton/) dieron algunas ideas de la probabilidad sin influenciar su desarrollo teórico.

- Antes de este periodo, hubo algunas contribuciones a la probabilidad y es así como [Cardano](https://mathshistory.st-andrews.ac.uk/Biographies/Cardan/) (1501-76) dio algunas probabilidades asociadas al lanzamiento de los dados. Sin embargo, una masa crítica de investigadores y resultados fue alcanzada solamente después de las discusiones entre Pascal y [Fermat](https://mathshistory.st-andrews.ac.uk/Biographies/Fermat/).

- Las estadísticas poblacionales surgen mediante el trabajo de [Graunt](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm). [William Petty](http://en.wikipedia.org/wiki/William_Petty) (amigo de Graunt) creó el término **Política Aritmética** refiriéndose al estudio cuantitativo de la demografía y de la economía. [Gregory King](http://en.wikipedia.org/wiki/Gregory_King) fue una importante figura de la siguiente generación. Sin embargo la línea econométrica no surgió de la manera adecuada. De hecho, el economista más influyente del siglo 18, Adam Smith, escribió, "Yo no tengo ninguna esperanza en la política aritmética".

- Una nueva forma de matemáticas de seguros de vida es creada a partir del trabajo de [Graunt](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) por los matemáticos [Halley](https://mathshistory.st-andrews.ac.uk/Biographies/Halley/), [Hudde](https://mathshistory.st-andrews.ac.uk/Biographies/Hudde/) y [deWitt](https://mathshistory.st-andrews.ac.uk/Biographies/De_Witt/). Mucho después algunos probabilistas escribirían acerca de temas actuariales, entre ellos [deMoivre](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm), [Simpson](https://mathshistory.st-andrews.ac.uk/Biographies/Simpson/), [Price](https://mathshistory.st-andrews.ac.uk/Biographies/Price/), [DeMorgan, ](https://mathshistory.st-andrews.ac.uk/Biographies/De_Morgan/)[Gram](https://mathshistory.st-andrews.ac.uk/Biographies/Gram/), [Thiele](https://mathshistory.st-andrews.ac.uk/Biographies/Thiele/), [Cantelli](https://mathshistory.st-andrews.ac.uk/Biographies/Cantelli/), [Cramér](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) y deFinneti. En el siglo 20 algunos temas de actuaria más la motivación de [G. J. Lidstone](https://mathshistory.st-andrews.ac.uk/Biographies/Lidstone/) estimularon a [E. T. Whittaker](https://mathshistory.st-andrews.ac.uk/Biographies/Whittaker/) y [A. C. Aitken](https://mathshistory.st-andrews.ac.uk/Biographies/Aitken/), en la contribución del desarrollo estadístico y el análisis numérico.

- En nuevas instituciones, además de las universidades tradicionales, apuntalan estos desarrollos. En Paris y Londres se crean grupos privados de discusión, entre ellos el de [Mersenne](https://mathshistory.st-andrews.ac.uk/Biographies/Mersenne/), desde donde se crean la [Academia de ciencias](https://mathshistory.st-andrews.ac.uk/Societies/Paris/) y la [Sociedad real de Londres](https://mathshistory.st-andrews.ac.uk/Societies/RS/) ([archivos](http://www.royalsoc.ac.uk/DServeA/)). En [Philosophical Transactions](http://gallica.bnf.fr/Catalogue/noticesInd/FRBNF37571969.htm) se publican muchas contribuciones a la probabilidad y a la estadística, incluyendo artículos escritos por [Halley](https://mathshistory.st-andrews.ac.uk/Biographies/Halley/), [deMoivre](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm), [Bayes](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm), [Pearson](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm), [Fisher](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm), [Jeffreys](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) y [Neyman](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm). Las academias de [Berlin](https://mathshistory.st-andrews.ac.uk/Societies/Berlin/) y [St. Petersburg](https://mathshistory.st-andrews.ac.uk/Societies/Russian/) se formaron poco después.

**Siglo XVIII**

Hald (1990) llamó a la primera parte de esta época **el gran salto** (1708-1718): Hubo contribuciones muy importantes en distintos temas de la probabilidad. Aunque las raíces de la probabilidad y de la estadística son muy distintas, en los comienzos del siglo 18 se entendía que los dos temas estaban cercanamente relacionados.

- [Jakob Bernoulli](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) (Ars Conjectandi) y [Arnauld](https://mathshistory.st-andrews.ac.uk/Biographies/Arnauld/) (Logique) sugieren una concepción de la probabilidad un poco más amplia que la asociada a los juegos, chances y oportunidades. La [ley de los grandes números](http://members.aol.com/jeff570/l.html) de [Bernoulli](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) establece una teoría que vincula la probabilidad con los datos.

- [Montmort](https://mathshistory.st-andrews.ac.uk/Biographies/Montmort/) ([Essay d'analyse sur les jeux de hazard](https://web.archive.org/web/20241203140745/https://math.dartmouth.edu/~doyle/docs/hazard/scan/hazard.pdf) (1708)) y [deMoivre](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) (Doctrine of Chances (1718)) son autores que producen nuevos resultados de la teoría de los juegos extendiendo el trabajo de [Pascal](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) y de [Huygens](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm).

- El artículo de [Arbuthnot](https://mathshistory.st-andrews.ac.uk/Biographies/Arbuthnot/) en 1710 ([An Argument for Divine Providence, taken from the constant Regularity observed in the Births of both Sexes](http://www.york.ac.uk/depts/maths/histstat/arbuthnot.pdf)) usa una prueba de [significación](http://members.aol.com/jeff570/s.html) ([la prueba del signo](http://members.aol.com/jeff570/s.html)) para establecer que la probabilidad de nacimiento de un varón no es de un medio. Estos cálculos fueron refinados por [Gravesande](https://mathshistory.st-andrews.ac.uk/Biographies/SGravesande/) y por [Nicolás Bernoulli](https://mathshistory.st-andrews.ac.uk/Biographies/Bernoulli_Nicolaus%28I%29/). Aparte de haber sido una de las primeras aplicaciones de la probabilidad a las estadísticas sociales, el artículo de Arbuthnot ilustra una conexión cercana entre la teología y la probabilidad en la literatura de la época. El trabajo de [John Craig](https://mathshistory.st-andrews.ac.uk/Biographies/Craig/) establece otro ejemplo de esta situación.

- La consideración de la evaluación de riesgos, dramatizada por la [Paradoja de San Petersburgo](http://members.aol.com/jeff570/s.html) (formulada por [Nicolás Bernoulli](https://mathshistory.st-andrews.ac.uk/Biographies/Bernoulli_Nicolaus%28I%29/) en 1713 y discutida por [Gabriel Cramer](https://mathshistory.st-andrews.ac.uk/Biographies/Cramer/)) guió la teoría de la [esperanza moral](http://members.aol.com/jeff570/m.html) (o [utilidad esperada](http://members.aol.com/jeff570/u.html)) formulada por [Daniel Bernoulli](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) (1737).

La probabilidad se establece en la ciencia de la Física, en la astronomía muestra una influencia. La aplicación más duradera en la astronomía trata acerca de la combinación de observaciones. La teoría resultante de los [errores](ECwwwStaffaldrichThis%20was%20the%20pri) es el ancestro más importante de la inferencia estadística moderna, particularmente en el campo de la teoría de [estimación](http://members.aol.com/jeff570/e.html).

- Los más importantes astrónomos y matemáticos, incluidos [Daniel Bernoulli](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm), [Boscovich](https://mathshistory.st-andrews.ac.uk/Biographies/Boscovich/), [Euler](https://mathshistory.st-andrews.ac.uk/Biographies/Euler/), [Lambert](https://mathshistory.st-andrews.ac.uk/Biographies/Lambert/), [Mayer](https://mathshistory.st-andrews.ac.uk/Biographies/Mayer_Tobias/) y [Lagrange](https://mathshistory.st-andrews.ac.uk/Biographies/Lagrange/), trataron el problema de la combinación de observaciones astronómicas, "para minimizar los errores surgidos de las imperfecciones de los instrumentos y de los órganos de los sentidos" en palabras de [Thomas Simpson](https://mathshistory.st-andrews.ac.uk/Biographies/Simpson/). Simpson introdujo la idea de postular una distribución para los [errores](http://members.aol.com/jeff570/e.html).

- Se desarrollaron algunas pruebas de [significación](http://members.aol.com/jeff570/s.html), la mayoría de ellas aplicadas en astronomía. [Daniel Bernoulli](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm), [John Michell](http://www.seds.org/messier/xtra/Bios/michell.html) (1767) y [Crossley](http://www.yorksphilsoc.org.uk/files/michell.pdf) calcularon las chances ([odds](http://members.aol.com/jeff570/o.html)) de que el sistema de Pléyades (siete cabrillas) fuera un sistema de estrellas y no un conglomerado aleatorio.

- Se realizan afirmaciones en forma de intervalo para el parámetro de la distribución Binomial (ancestros de los [intervalos de confianza](http://members.aol.com/jeff570/c.html) modernos). Estos fueron propuestos por [Lagrange](https://mathshistory.st-andrews.ac.uk/Biographies/Lagrange/) y por [Laplace](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) en la década de 1780.

- En 1770 [Condorcet](https://mathshistory.st-andrews.ac.uk/Biographies/Condorcet/) empieza una publicación acerca de matemáticas sociales, para la aplicación de la teoría de probabilidad en las decisiones de jurados y otras asambleas. Su trabajo tuvo una fuerte influencia en [Laplace](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) y [Poisson](https://mathshistory.st-andrews.ac.uk/Biographies/Poisson/). Otros autores franceses de este periodo son [D'Alembert](https://mathshistory.st-andrews.ac.uk/Biographies/D'Alembert/) y [Buffon](https://mathshistory.st-andrews.ac.uk/Biographies/Buffon/); el primero es recordado por sus comentarios críticos en la teoría de probabilidad y el último el experimento de la aguja.

- Un desarrollo importante en la teoría de la probabilidad fue el trabajo de [probabilidad condicional](http://members.aol.com/jeff570/c.html) con aplicaciones a la [probabilidad inversa](http://members.aol.com/jeff570/i.html) o [Inferencia Bayesiana](http://members.aol.com/jeff570/b.html) propuesto por Bayes y Laplace.
