---
title: "El verdadero Papá Noel"
author: "Andrés Gutiérrez"
date: "2008-12-23"
categories:
  - "Estadística"
---

Estaba escribiendo un *post* y al momento de darlo de alta me pregunté si a los fieles lectores de este blog les interesaría, en esta precisa época, leer un *post* sobre métodos de pseudo-máxima verosimilitud. Me respondí que no - aunque puedo estar equivocado. Fue así, como recordé que, hace unos años, un conferencista internacional abrió su disertación con un par de estadísticas acerca de un personaje muy famoso, con el que crecí y disfrute, de manera latente, en las navidades. Este post trata acerca de este personaje… el querido Papá Noel, Santa Claus, Viejito Pascuero, Colacho o San Nicolás… En fin, el personaje legendario que según la cultura occidental trae regalos a los niños en navidad.

Un estudio de la compañía europea SWECO revela las verdades detrás del telón… Con las conclusiones del estudio sigo creyendo fervientemente en Papá Noel.

- Papá Noel tiene que visitar la noche del próximo 24 de diciembre la nada despreciable cifra de 2.500 millones de hogares alrededor del mundo… Claro está, teniendo en cuenta que todos los niños del planeta se hayan portado bien y merezcan un regalo de este allanador de moradas navideño.

- Las estadísticas informan que hay unas 48 personas por kilómetro cuadrado en la Tierra, y 20 metros entre casa y casa. De este modo, si Papá Noel sale de su casa y viaja en contra del sentido de rotación del planeta tendría 48 horas para entregar todos los presentes.

- En materia logística, la entrega de los regales debe hacerse en 34 microsegundos (millonésimas de segundo) por cada hogar... Resulta sorprendente que en este minúsculo espacio de tiempo, Papá Noel pueda descender del trineo, coger los regalos, subir al tejado, entrar por la chimenea, dejarlos al pie del árbol de Navidad, mordisquear las galletitas, beber la leche y volver a su trineo liderado por Rodolfo. Aunque repetitivo, es un proceso laborioso, que requiere su tiempo.

- En la aventura de recorrer la tierra para entregar los regalos a los niños buenos, Papá Noel debería viajar a la modesta velocidad de 5.800 kilómetros por segundo.

- Sin embargo, a esa velocidad, la resistencia del aire contra Papá Noel cargado con todos los regalos, harían que el trineo, los renos y hasta el propio Papá Noel ardieran en menos que canta un gallo. A su vez, de acuerdo a otro estudio que recorre los blogs que leo, si Papá Noel llegara a viajar a la velocidad supersónica que requiere el cumplimiento de sus tareas navideñas, sería consumido por las llamas y se desintegraría en 4,26 milésimas de segundo. Obviamente, Papá Noel no es consumido por las llamas pues lleva puesto su traje rojo que lo protege y bastante.

- Si Papá Noel viviera en Korvatunturi (Laponia finlandesa), un lugar que según la tradición ha estado habitado por Papá Noel hace ya varias centurias, el precio de los regalos aumentaría significativamente.

- Por tanto, basándose en la topografía de la tierra y la distribución de la población, el lugar desde el que Papá Noel tendría un mejor acceso a todos los niños buenos del planeta sería Kyrgyzstan en Asia central

**¡FELIZ NAVIDAD QUERIDO LECTOR!... no olvides que tú eres el regalo más grande para este blog. Bendiciones.**
