---
title: "Historia de la probabilidad (Era Contemporánea)"
author: "Andrés Gutiérrez"
date: "2008-10-11"
categories:
  - "Probability"
  - "Bayesian Statistics"
---

**Siglo XIX**

La característica fundamental son sus fuertes cambios. Cambios anunciados y gestados en el pasado pero que se efectuarían, de hecho, en el siglo. Cambios en todos los ámbitos de la vida y el conocimiento. [Revoluciones](http://es.wikipedia.org/wiki/Revoluci%C3%B3n) de todas las índoles tendrían su lugar. La ciencia y la economía se retroalimentarían, el término "científico", acuñado en 1833 por [William Whewell](http://es.wikipedia.org/wiki/William_Whewell), [1](http://es.wikipedia.org/wiki/Decimon%C3%B3nico) [2](http://es.wikipedia.org/wiki/Decimon%C3%B3nico) sería parte fundamental del lenguaje de la época

**1800-1830**

Este periodo se encuentra dominado por las figuras de [Laplace](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) y [Gauss](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm). Laplace cubrió todo el rondó de la probabilidad y la estadística; Gauss se enfocó solamente en la teoría de los errores.

- El trabajo en la teoría de los errores alcanzó un clímax con la introducción del [método de los mínimos cuadrados](https://web.archive.org/web/20260317083125/https://jeff560.tripod.com/m.html) que fue publicado [Legendre](https://mathshistory.st-andrews.ac.uk/Biographies/Legendre/) en 1805. Durante veinte años hubo tres razonamientos basados en la teoría de la probabilidad: El argumento bayesiano de [Gauss](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) (con una distribución a priori [uniforme](https://web.archive.org/web/20241213234751/https://jeff560.tripod.com/u.html)), el argumento de [Laplace](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) basado en el [teorema central del límite](https://web.archive.org/web/20251226073238/https://jeff560.tripod.com/c.html) y el argumento de [Gauss](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) que se basó en el teorema de [Gauss-Markov](https://web.archive.org/web/20260414152920/https://jeff560.tripod.com/g.html). El trabajo de investigación continuo a través del siglo 19 con la ayuda y contribución de numerosos astrónomos y matemáticos; entre ellos, [Cauchy](https://mathshistory.st-andrews.ac.uk/Biographies/Cauchy/), [Poisson](https://mathshistory.st-andrews.ac.uk/Biographies/Poisson/), [Fourier](https://mathshistory.st-andrews.ac.uk/Biographies/Fourier/), [Bessel](https://mathshistory.st-andrews.ac.uk/Biographies/Bessel/), [Encke](http://en.wikipedia.org/wiki/Johann_Franz_Encke), [Chauvenet](https://mathshistory.st-andrews.ac.uk/Biographies/Chauvenet/) y [Newcomb](https://mathshistory.st-andrews.ac.uk/Biographies/Newcomb/). (Aparece la [distribución de Cauchy](https://web.archive.org/web/20251226073238/https://jeff560.tripod.com/c.html) como un caso poco elegante de la teoría de los errores.) [Pearson](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm), [Fisher](OLDpcearliestworking%22%20l%20) y [Jeffreys](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) aprenden la teoría de los errores desde la perspectiva de los astrónomos.

- [Gauss](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) encontró una segunda aplicación de los mínimos cuadrados en la geodesia. Los geodesistas hicieron importantes contribuciones a los mínimos cuadrados, particularmente desde la perspectiva computacional. Los epónimos, [Gauss-Jordan](https://web.archive.org/web/20260414152920/https://jeff560.tripod.com/g.html) y [Cholesky](https://web.archive.org/web/20251226073238/https://jeff560.tripod.com/c.html), son puestos en honor a posteriores geodesistas. [Helmert](http://en.wikipedia.org/wiki/Friedrich_Robert_Helmert) (la transformada de [Helmert](https://web.archive.org/web/20260422132814/https://jeff560.tripod.com/h.html)) fue un geodesista que contribuyó a la teoría de los errores. Nótese que el topógrafo [Frank Yates](https://mathshistory.st-andrews.ac.uk/Biographies/Yates/) contribuyó enormemente a la estadística siendo colega y sucesor de [Fisher](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) en Rothamsted.

- En Gran Bretaña se llevó a cabo el primer censo poblacional en 1801. Éste terminó la controversia acerca del tamaño de la población que empezó con [Price](https://mathshistory.st-andrews.ac.uk/Biographies/Price/), amigo de Bayes, quien argumentaba que la población había decrecido en el siglo 18. Numerosos escritores lanzaron estimaciones, incluyendo a [Eden](http://en.wikipedia.org/wiki/Sir_Frederick_Morton_Eden).

- [William Playfair](http://en.wikipedia.org/wiki/William_Playfair) encontró nuevas formas de representación gráfica de los datos. Sin embargo, nadie le prestó atención. La teoría estadística que ganó terreno en los siguientes 150 años no tuvo en cuenta la idea de la graficación de los datos. Esta idea es reciente y se asocia con [Tukey](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm).

- Concluye la era de las academias y los mayores avances se dan en las universidades. El sistema de educación francesa fue transformado gracias a la revolución y el siglo 19 vio el surgimiento de la universidad alemana.

**1830-1860**

Este periodo vio el surgimiento de de la sociedad estadística, la cual ha estado active en la escena científica desde entonces. Aunque el significado de la palabra "Estadística" ha cambiado desde el principio de la literatura filosófica de la probabilidad. En este periodo, también se dio la más glamorosa rama del análisis empírico de las series temporales, el llamado "ciclo de las manchas solares".

- Desde 1830 han habido varias sociedades estadísticas, incluyendo la [London (Royal) Statistical Society](http://www.rss.org.uk/main.asp?page=1085) y la [American Statistical Association](http://www.amstat.org/about/index.cfm?fuseaction=history) (ahora la más grande del mundo). El [International Statistical Institute](https://web.archive.org/web/20131030031035/http://isi.cbs.nl/nutshell.htm) fue fundado en 1885 aunque ha organizado congresos internacionales desde 1853. Las estadísticas estuvieron basadas en las poblaciones humanas y en Francia [André-Michel Guerry](http://en.wikipedia.org/wiki/Andr%C3%A9-Michel_Guerry) mapeó una clase de estadísticas morales. [Quetelet](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) fue un catalizador en la formación de la London Society.

- Desde 1840, existe la literatura filosófica de [probabilidad](https://web.archive.org/web/20251113013258/https://jeff560.tripod.com/p.html). La literatura inglesa empieza con la discusión de probabilidad de John Stuart Mill (1843). Este fue seguido por [John Venn](https://mathshistory.st-andrews.ac.uk/Biographies/Venn/), [W. Stanley Jevons](http://en.wikipedia.org/wiki/William_Stanley_Jevons) y [Karl Pearson](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm). Hubo un traslape en la literatura de lógica y de probabilidad. [De Morgan](https://mathshistory.st-andrews.ac.uk/Biographies/De_Morgan/) y [Boole](https://mathshistory.st-andrews.ac.uk/Biographies/Boole/) también aportaron exhaustivas y largas discusiones acerca de la probabilidad.

- En 1843 [Schwabe](http://en.wikipedia.org/wiki/Heinrich_Schwabe) observe que la actividad de las manchas solares ([sunspot](http://en.wikipedia.org/wiki/Sunspot)) era periódica. Seguido de décadas de investigación, no solo en la física solar sino en el magnetismo terrestre, meteorología e incluso economía, donde se examinaban las series para ver si su periodicidad coincidía con la de las manchas solares. Incluso antes de la manía o moda de las manchas solares hubo un interés intense en la periodicidad en la meteorología, en el estudio de las mareas y otras ramas de la física observacional. Juntos, [Laplace](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) y [Quetelet](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm), habían analizado datos meteorológicos y [Herschel](https://mathshistory.st-andrews.ac.uk/Biographies/Herschel/) había escrito un libro al respecto. Las técnicas en uso variaban desde las más simples, como la tabla de [Buys Ballot](http://en.wikipedia.org/wiki/C. H. D._Buys_Ballot), a formas más sofisticadas como el [análisis armónico](https://web.archive.org/web/20260422132814/https://jeff560.tripod.com/h.html). Al final del siglo, el físico [Arthur Schuster](http://en.wikipedia.org/wiki/Arthur_Schuster) introdujo el [periodogram](https://web.archive.org/web/20251113013258/https://jeff560.tripod.com/p.html) a. Sin embargo, por ese entonces, una forma rival del análisis de series temporales, basada en la correlación y promovida por [Pearson](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm), [Yule](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm), [Hooker](http://en.wikipedia.org/wiki/Reginald_Hawthorn_Hooker) y otros, fue tomando forma.

**1860-1880**

Dos importantes campos de aplicación se abrieron en este periodo. La probabilidad encontró una aplicación más profunda en la física, particularmente en la teoría de gases, naciendo así la mecánica estadística. Los problemas de la mecánica estadística estaban detrás del alcance de los avances de la probabilidad a comienzos del siglo 20. El estudio estadístico de la herencia, desarrollado dentro de la [biometría](https://web.archive.org/web/20260220124513/https://jeff560.tripod.com/b.html), tuvo lugar. Al mismo tiempo el mundo sufrió importantes cambios geográficos. Un trabajo importante en la teoría de la probabilidad venía desarrollándose en Rusia mientras que el trabajo estadístico venía de Inglaterra.

- En 1860 [James Clerk Maxwell](https://mathshistory.st-andrews.ac.uk/Biographies/Maxwell/) usó la curva del error (distribución normal) en la teoría de los gases; parece que él estaba influenciado por Quetelet. Boltzmann y Gibbs desarrollaron la teoría de gases dentro de la mecánica estadística.

- [Galton](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) inaugural el estudio estadístico de la herencia, trabajo continuado en el siglo 20 por [Pearson](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) and [Fisher](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm). La correlación fue una de las más distintivas contribuciones de la escuela inglesa.

- En contraste, la llamada "dirección continental" investigaba que tan apropiado era el uso de los modelos para el tratamiento de las tasas de nacimientos y defunciones por considerar la estabilidad de las series sobre el tiempo.

- Hubo una mayor penetración de la estadística en la psicología y en la economía. Se tuvo en cuenta el trabajo de los políticos aritméticos de 1650. El trabajo de Jevons sobre [números índice](https://web.archive.org/web/20251215085114/https://jeff560.tripod.com/i.html) fue inspirado por la teoría de los errores. La investigación en series temporales económicas fue inspirada por el trabajo de lo meteorólogos acerca de la variación estacional de los ciclos solares y sus correlaciones en la tierra.

**1880-1900**

En este periodo la escuela inglesa estadística tomó forma. [Pearson](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) fue el personaje dominante hasta que [Fisher](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) lo desplazó en la década de 1920s.

- [Galton](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) introdujo la [correlación](https://web.archive.org/web/20251226073238/https://jeff560.tripod.com/c.html) y una teoría basada en el anterior concepto fue rápidamente desarrollada por [Pearson](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm), [Edgeworth](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm), [Sheppard](http://en.wikipedia.org/wiki/William_Fleetwood_Sheppard) y [Yule](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm). La correlación fue la mayor salida desde el trabajo estadístico de Laplace y Gauss. Empezó a ser ampliamente aplicada en biología, psicología y ciencias sociales.

- En economía [Edgeworth](http://www.economics.soton.ac.uk/staff/aldrich/Figures.htm) siguió algunas ideas de Jevons, sobre números índice. Sin embargo, en Inglaterra la economía estadística era más cercana al trabajo en estadísticas oficiales o periodismo financiero. En Italia [Vilfredo Pareto](http://cepa.newschool.edu/het/profiles/pareto.htm) descubrió una regularidad estadística en la distribución del ingreso ([distribución de Pareto)](https://web.archive.org/web/20251113013258/https://jeff560.tripod.com/p.html).
