---
title: "La probabilidad de un madrazo…"
author: "Andrés Gutiérrez"
date: "2009-11-06"
categories:
  - "Probability"
  - "Inference"
---

Pasando a temas un poco más jocosos, imagine que usted recibe una carta de un amigo suyo. Usted lee la carta y con escepticismo se da cuenta que es un escrito estructurado, que se han tomado harto tiempo para escribirlo y que, a pesar de su gran sorpresa, usted cree que es un sutil insulto. Pues bien, a simple vista la carta contiene poca información pero detalladamente, usted se da cuenta que es un acróstico y que su amigo lo está mandando al carajo. Eso suena muy real después de que el gobernador de California, el carismático Arnoldo Suarez enviara una misiva respondiendo negativamente a una petición. Al mirar detalladamente el mensaje, es fácil darse cuenta que se trata de una composición casi poética que contiene un mensaje claro y directo: FUCK YOU.

Por supuesto, el gobernador de California niega estar detrás de este desagradable incidente y toda la culpa se la atribuye a una desafortunada coincidencia perpetrada por el desatino del destino. Sin embargo, [Philip B. Stark](http://statistics.berkeley.edu/~stark/Preprints/acrosticVeto09.htm), a través de numerosos escenarios, demuestra que la probabilidad de tal casualidad es casi nula. Entre algunos de los escenarios están:

1. Si se digita un escrito de siete líneas y cada letra es elegida al azar, de forma independiente, a partir de las 26 letras del alfabeto inglés (ignorando mayúsculas y minúsculas, espacios, números y puntuación), la probabilidad de que la primera letra de las siete líneas forme este acróstico es (1/26)^7 = 1.245e-10.

2. No todas las letras del alfabeto tienen la misma frecuencia de uso. Así, la letra c tiene una frecuencia de 0.03511, la letra f de 0.03779, la letra k de 0.00690, la letra o de 0.06264, la letra u de 0.01487, la letra y de 0.01620. De esta manera, la probabilidad buscada es de 0.03779 × 0.01487 × 0.03511 × 0.00690 × 0.01620 × 0.06264 × 0.01487 = 2.054e-12.

Pues bien, fíjese usted qué fácil es insultar sutilmente. Desde ahora en adelante lea bien, muy bien.
