---
title: "Homenaje a Leonardo Bautista"
author: "Andrés Gutiérrez"
date: "2009-05-04"
categories:
  - "Teaching"
  - "Sampling"
---

En los últimos años, el maestro **Leonardo Bautista** fue uno de los personajes más importantes e influyentes en la escena estadística colombiana. Como discípulos suyos, creemos que nuestro cometido con la ciencia requiere que como publicación se haga un homenaje al profesor Bautista, no con lamentos sobre su partida sino como a él más le hubiese gustado: divulgando las investigaciones que él realizó en conjunto con sus pupilos.

El segundo número de la **Revista Comunicaciones****en Estadística** será un homenaje al maestro Bautista. Varios colegas, algunos desde el extranjero, participarán con sus valiosos artículos y aportes generados en conjunto con el maestro Bautista. En particular, quisiera resaltar la participación editorial del estadístico **José Fernando Zea Castro** quien escribió el siguiente ensayo desde su perspectiva como estudiante.

### Leonardo Bautista: Perspectiva del estudiante

El profesor Leonardo Bautista falleció el 20 de Enero del 2009. Este hecho es muy doloroso para la comunidad estadística y el país pierde una figura controvertida que no tenía miedo de decir la verdad y de ser honesto en sus planteamientos. Sin embargo, su legado y sus enseñanzas permanecerán por mucho tiempo. Él Creó un estilo y una manera única de ejercer su profesión, fue una persona de odios y de amores, con una personalidad radical, fuerte y apasionada, fue un luchador incansable, un poeta, un maestro que hizo con su profesión los mejores versos, excelente representante de lo que debe ser un estadístico: responsable, disciplinado, creativo, ilustrado, ordenado, comunicador, diáfano en sus planteamientos, locuaz y divertido.

Tuve el honor de conocer al profesor y de tomar con él tres cursos en el pregrado: Muestreo I, Muestreo II, y Diseño y Desarrollo de Encuestas. Son muchas las enseñanzas que dejó para mi vida profesional y laboral. A comienzos de Febrero del año 2005, tuve mi primera clase de Muestreo I, el profesor llegó puntualmente y el salón se encontraba en silencio, expectante y se respiraba una atmósfera de tensión; ya teníamos cierta información proporcionada por algunos de sus estudiantes anteriores que nos hacía pensar que aprobar y sobresalir en este curso no iba a ser nada fácil. Sin embargo, también sabíamos de la excelente calidad de éste docente.

Hasta ese día, la mayoría de mis compañeros y yo, nos habíamos desplazado por el mundo abstracto de las matemáticas, nuestros conocimientos estadísticos y la aplicación de éstos en la vida real, eran vagos, confusos o inexistentes. Comenzó la clase y el maestro indagó por nuestros nombres y por las asignaturas que íbamos a cursar ese semestre, no transcurrió mucho tiempo y él abordó a uno de mis compañeros preguntándole: "¿vas a ver cinco materias y muestreo?", mi compañero intimidado asintió afirmativamente con la cabeza, a lo cual el profesor respondió –"muestreo requiere dedicación de tiempo completo incluso hasta en los sueños", esta fue la primera pista de lo exigente que iba a ser. Desde el primer día de clases el profesor tuvo la capacidad de inferir la personalidad y el carácter de muchos de sus estudiantes, su mirada intimidaba pero a la vez motivaba e invitaba a poner atención a cada una de sus palabras y gestos.

En esa primera clase, nos presentó el programa del curso y mencionó nombres incomprensibles e indescifrables para mí en ese momento: probabilidad de inclusión, estimador de Horvitz-Thompson, diseño de muestreo multietápico, conglomerados, unidad primaria de muestreo, etc. Aunque me sentía confundido, me quedó muy claro la seriedad y profesionalismo que iban a tener sus clases, efectivamente no me equivoqué. Desde este día, Leonardo Bautista puso las reglas muy claras, no valía enfermarse, ni la ocurrencia de ningún evento extraordinario (ni siquiera la ocurrencia de otro 5-0 de Colombia sobre Argentina) para aplazar parciales o eludir nuestras responsabilidades.

Transcurrían los días y sus clases cada vez se iban tornando más interesantes, enriquecedoras y divertidas, éstas eran de una alta exigencia, ricas de anécdotas y por supuesto no faltaba el humor negro hacia algunos de sus estudiantes más desorientados. Leonardo Bautista era un psicólogo, sí que lo era, en unas pocas clases ya tenía identificado a sus pupilos más complicados, confiados, de peor carácter y más desorientados, así mismo tenía una broma y una observación jocosa para sus estudiantes más particulares.

Leonardo Bautista tenía el ejemplo adecuado, la anécdota interesante y el comentario acertado para cada una de las preguntas que nos iban surgiendo, eran frecuentes los ejemplos que nos trasmitía de sus experiencias. Siempre nos exigió que planteáramos bien las preguntas que nos surgían y nos enseñó la metodología y el orden en que se plantea y se resuelve un problema estadístico.

Muchos de nosotros tuvimos el primer contacto con un paquete estadístico en este curso, nos enseñó SAS de la manera más sencilla posible o como a él le gustaba decir de "manera picapedrera", implementamos en este paquete desde los diseños de muestreo más sencillos: Bernoulli, muestreo aleatorio simple, hasta diseños más complejos como los diseños multietápicos. Nunca fue reacio a que exploráramos otras herramientas y motivó el uso de otras alternativas como R, paquete estadístico que empezaba a ser popular en el departamento de estadística gracias a varios profesores, entre ellos los de computación estadística: Álvaro Montenegro y Jorge Ortiz, este último quien tomó como asistente en esa ocasión el curso de muestreo.

Aún están en mi mente las tareas extensas que él nos dejaba cada martes para la siguiente semana; éstas eran bien planteadas, interesantes, ricas en conceptos, prácticas y muy laboriosas, muchos entendimos al realizarlas conceptos tan importantes como probabilidad de inclusión, probabilidad de cobertura, insesgamiento, varianza de un estimador, boostrap, jacknife y otras nociones de estadística multivariada, modelos lineales e inferencia estadística.

La biblia del profesor Leonardo Bautista era el libro de muestreo de Särndal, Wretman y Swensson: "Model Assisted Survey Sampling", en sus palabras descubrir este libro fue encontrar la luz, el camino y la senda correcta de la enseñanza del muestreo, según él, otros autores clásicos no abordaban de manera tan clara el muestreo como lo hacía este libro. Nos exigía una lectura detallada de cada uno de los párrafos del libro y para muchos de sus estudiantes ésta fue la primera inmersión en la lectura de un libro en lengua extranjera.

La diversión se acababa cuando ya se acercaba el parcial, las perspectivas de responder un examen en el cual todo estaba dado para perderlo no nos entusiasmaba mucho. En primer lugar, el examen era un sábado, la primera parte de éste era un control de lectura de la biblia del profesor Bautista a través de varias preguntas de tipo opción múltiple con penalización de dos puntos negativos para aquellas de éstas que estuvieran mal contestadas.

La segunda parte del examen se hacía en unas sala de cómputo, muchos de nosotros llegábamos con una sonrisa victoriosa, con la satisfacción de haber realizado un programa con un ingenioso código en SAS o R, con el cual implementábamos los diseños de muestreo enseñados hasta ese momento por el profesor; sin embargo por alguna razón desconocida, en muchas ocasiones nuestros programas no funcionaban al aplicarlo al conjunto de datos entregados por él, o bien, funcionaban sólo después de haber terminado el examen. Por lo tanto era posible que algún estudiante, habiéndose dejado llevar por los nervios y sumado a esto el no haber estudiado ni preparado de manera adecuada su programa, tuviera una nota inferior a cero, es decir, se podía quedar debiendo nota Este asunto lo resolvía el profesor plasmando en la hoja de dicho estudiante un cero con todo el cuidado.

Se perdía siempre con 2.5, así que si alguien sacaba un doloroso 2.9 no había posibilidad alguna de redondeo, la nota era contundente: 2.5.

Su fuerte exigencia nos forjó y nos hizo más fuertes, si algo nos transmitió el profesor Bautista fue el sentirnos orgullosos de nuestra profesión, pero nunca despreciando o subestimando las demás profesiones u oficios. El profesor nos hizo concientes de la importancia de nuestra labor en la toma de decisiones en el quehacer económico, social, político y científico.

Fue inolvidable la experiencia que tuvimos con él en el curso de Diseño y Desarrollo de Encuestas que impartió en Julio del año 2005, en esa ocasión se quería realizar una investigación en Soacha acerca del riesgo de cáncer de cuello uterino en las mujeres mayores de 25 años. Cada uno de los detalles, desde el planteamiento con un médico de cada una de las preguntas del cuestionario hasta la creación de los cuadros de salida de la encuesta, entre otras muchas minucias, fueron explicadas de manera clara y precisa por él. Fue una experiencia totalmente enriquecedora e inolvidable, llena de anécdotas e historias.

De ese curso recordamos un dolor en su espalda aparentemente insignificante, el cual empezó a manifestársele cuando había transcurrido unos días del inicio del curso; ese dolor día a día lo afectaba más y se hizo evidente que algo grave lo aquejaba, pues bien, fue por esos días que se le diagnóstico cáncer en la medula. Pese a sus dolores y dificultades para movilizarse él nunca se rindió ni eludió sus responsabilidades académicas. por el contrario siempre estuvo dispuesto a colaborarnos y nos transmitió conocimientos invaluables, finalmente y pese a las dificultades que hubo a raíz de sus problemas de salud se logró culminar con éxito el curso.

Pasaron seis meses en los cuales supimos de la lucha incesante del profesor contra el cáncer. Luego de éstos regresó a las aulas, en esa ocasión el iba a impartir el curso de Muestreo II. Por sus dolores ya no podía escribir en un tablero, así que empezó a preparar diapositivas para cada clase. Pese a los constantes dolores del profesor el curso logró terminarse con éxito y con la exigencia a la que él nos tenía acostumbrado.

El legado que deja Leonardo Bautista es invaluable, muchos estadísticos aprendimos muestreo y estadística con él, nos enamoramos de nuestra profesión, nos dejó un libro de muestreo en el cual sintetizó de manera muy clara sus enseñanzas y en donde plasmó algunos de sus pensamientos. Dirigió varios trabajos de grado e influenció varios artículos e investigaciones y muchas personas siguen ahora sus pasos y transitan por los senderos que él dejó despejados.

Sus aportes tuvieron un alcance mucho más allá de la academia, fueron muy reconocidos sus cursos de censos y encuestas para funcionarios del DANE. En esta institución e indirectamente en muchas otras él también dejó su huella. Su laboriosidad y dedicación marcó también a muchos estadísticos que actualmente laboran en el sector público y privado. Leonardo Bautista nos dejó varias lecciones para nuestra vida: la pasión por servir a la sociedad, el amor por la profesión y nunca rendirnos ni siquiera ante las adversidades más grandes; nos enseñó la fuerza de la argumentación y nos mostró como hay que defender nuestras ideas con estilo y respeto hacia los demás.

Gracias maestro.

José Fernando Zea Castro

"Yo no se lo que es el destino, caminando fui lo que fui" Leonardo Bautista citando a Silvio Rodríguez…

(El anterior texto fue tomado de la editorial del segundo número de la Revista Comunicaciones en Estadística y se reproduce con autorización del comité editorial)
