---
title: "¿Análisis de correspondencias en Marketing?"
author: "Andrés Gutiérrez"
date: "2009-02-27"
categories:
  - "Estadística"
---

Para un mejor entendimiento de la teoría aquí planteada [haga clic en este vínculo](http://predictive.files.wordpress.com/2009/02/biplot1.pdf) y encontrará el documento que sustenta las ideas expuestas a continuación.

Hablo desde mi propia perspectiva… los métodos estadísticos deben tener validez teórica desde el punto de vista del usuario. Es decir, en epidemiología, economía, contaduría, sociología o en marketing, los métodos estadísticos tienen validez siempre y cuando sirvan para apoyar la teoría desarrollada en estas áreas del conocimiento. No le digan a un gerente de mercadeo que la variable satisfacción del consumidor no entra en el modelo re regresión porque el beta no resultó significativo. En estos aspectos, la ciencia estadística debe ser vista como una herramienta. Ahora, como sucede con toda herramienta, es necesario adecuarla al terreno y afinarla de tal manera que se convierta en una herramienta indispensable en manos del experto y no en una más de las herramientas a las cuales se puede acceder. En esta ocasión, le tocó el turno al análisis de correspondencias. Específicamente al muy conocido y bien ponderado mapa perceptual, resultado de éste análisis.

Una de mis primeras experiencias en marketing fue en un lugar en donde el informe que se presentaba al gerente de marca estaba constituido por más de doscientas diapositivas, muy bonitas y coloridas, que correspondían a gráficos de frecuencias de todas y cada una de las preguntas que estaban en el instrumento. Lo anterior me pareció muy curioso; sin embargo estoy seguro que este montón de datos sigue siendo una muy buena herramienta en las manos de los CEO's. Una de las soluciones que yo propuse fue reemplazar ese montón de datos por verdadera información… Al fin de cuentas, ese es el fin de la mayoría de procesos estadísticos… La respuesta que obtuve fue negativa. Es muy difícil cambiar la percepción del gerente y mucho más de quienes reciben dinero del gerente. Así que sí al gerente le agradan las tablas… pues a hacer tablas en el SPSS.

Tiempo después se interesaron en la solución. Sin embargo era una solución que no se defendía por sí misma… la interpretación del análisis de correspondencias depende de las tablas de contingencia utilizadas para generar el mapa perceptual. Por ejemplo, la siguiente figura puede guiar a conclusiones muy erróneas.

Es decir, para un gerente de marca es indispensable que las herramientas con las cuales toma sus importantes decisiones sean compatibles con la realidad del mercado. En el anterior gráfico es posible concluir que la marca con la mejor percepción de mercado es la **Brand C**. Bien, esto es falso si vemos las tablas de frecuencias originales (no las muestro a propósito). Sin embargo, una solución a este problema está dada por la incorporación de información auxiliar con respecto a los atributos de la categoría de mercado. De otro lado, si vemos el siguiente gráfico, resultado de un análisis de correspondencias modificado, entonces resulta que la interpretación se vuelve mucho más diáfana.

Pues aunque la **Brand C**está asociada a tres atributos se concluye que no es la marca más importante dentro de la categoría de mercado. Ahora, la marca más impactante resulta ser la **Brand B** y esto significa que está mucho mejor puntuada que cualquier otra marca en el mercado. Nótese que la incorporación de la importancia relativa, tanto en marcas como en atributos, es un gran salto en la interpretación de la percepción de la categoría y toma estratégica de decisiones. Con este tipo de gráfico no se necesita conocer la tabla de contingencia que lo generó. Si usted fuera el gerente de la **Brand A**y tuviera que tomar una decisión acerca de el atributo de enfoque en la próxima pauta publicitaria, ¿en cuál atributo enfocaría la propaganda?... conociendo que el atributo principal en el mercado es el **V1**seguramente le apuntaría a este.

Sin embargo, en términos de estrategia, es posible llegar a mejorar el anterior gráfico. Sin embargo, este paso se debe realizar de la mano del experto. Lo que se propuso fue segmentar la tabla de contingencias. De esta manera, el gerente se acerca mucho más a la percepción real del consumidor. Piense por un instante en la compra de un producto cualquiera y en lo complejo que resulta este proceso inconsciente. El siguiente gráfico **PLASMA**la mente del consumidor promedio en la categoría y permite conocer el proceso inconsciente que él realiza en su mente a la hora de comprar un producto o adquirir un servicio.

Este gráfico no pretende ser la solución a los problemas del investigador, ni mucho menos pretende reemplazar los arrumes de diapositivas, por lo cuales se pagan un precio. Simplemente pretende dar información veraz... Ymás aun, en estos tiempo de competitividad **la información es poder**.
