---
title: "La verdad de las estadísticas"
author: "Andrés Gutiérrez"
date: "2009-08-11"
categories:
  - "Estadística"
---

Esta es una historia y una invitación. Una historia y

balance de proyectos. El cotejo entre lo vislumbrado

como posible y lo finalmente cumplido como hecho

verificable.

Las discusiones que hemos sostenido, en el intento

siempre renovado de perfeccionar la identidad de nuestra

profesión, que serviría para hacer más sólida nuestra

propia posición en la sociedad.

La alta tensión entre quienes tienen mayor afinidad

por las matemáticas y quienes están cerca de la producci

ón de los datos, de la administración de diversos

“fondos” de información. Académicos y aplicados.

Falsas antinomias que tal vez sólo sirvieron para alejar

la discusión de los verdaderos problemas, que con

tanta claridad estampara en el número 1 de Estadística,

la revista del IASI, el fundador del IBGE, Mario Augusto

Teixeira de Freitas, a quien Dieulefait llamaba

“el Santo de la Estadística”:

Haga la América la Estadística que debe hacer

y la  Estadística hará grande a la América.

> Esta es una historia y una invitación. Una historia y balance de proyectos. El cotejo entre lo vislumbrado como posible y lo finalmente cumplido como hecho verificable. Las discusiones que hemos sostenido, en el intento siempre renovado de perfeccionar la identidad de nuestra profesión, que serviría para hacer más sólida nuestra propia posición en la sociedad.
>
>
> La alta tensión entre quienes tienen mayor afinidad por las matemáticas y quienes están cerca de la producción de los datos, de la administración de diversos “fondos” de información. Académicos y aplicados. Falsas antinomias que tal vez sólo sirvieron para alejar la discusión de los verdaderos problemas, que con tanta claridad estampara en el número 1 de Estadística, la revista del IASI, el fundador del IBGE, Mario Augusto Teixeira de Freitas, a quien Dieulefait llamaba “el Santo de la Estadística”: Haga la América la Estadística que debe hacer y la Estadística hará grande a la América.

El anterior fragmento es tomado del epílogo del libro [La verdad de las estadísticas](http://verdaddelasestadisticas.blogspot.com/), escrito por el doctor Hugo Ambrosí y quien muy gentilmente lo ha publicado en [su blog personal](http://verdaddelasestadisticas.blogspot.com/). El libro merece ser leído y releído pues, aparte de que fue escrito por un estadístico influyente en el desarrollo de la estadística en Argentina, está matizado con cierto tinte filosófico que conlleva a que el lector piense y piense acerca de preguntas a las cuales es difícil dar respuestas.

Es un honor para mì recomendar este texto y, desde este modesto espacio, darle todo mi apoyo.
