---
title: "¿Se acerca el fin de los departamentos de estadística?"
author: "Andrés Gutiérrez"
date: "2009-10-16"
categories:
  - "Publications"
  - "Community and Events"
---

En agosto de este año recibí, como de costumbre, el magazín *AMSTAT-News* (publicación de ASA: American Statistical Association). Después de ojearla por encima y hojearla rápidamente, me di cuenta que el magazín, además de contener valiosas ofertas laborales y oportunidades de estudio para los gringos, contenía bastante publicidad de software y, más bien, poca información. Así que la remití a mi compañero de oficina para que le echara un vistazo. Algunos días después, mi avezado colega me recomendó la lectura de un artículo de Keith Crank, director de la sección de investigaciones y posgrados de la ASA, titulado *Why We Need Data on Our Profession?* (¿Por qué necesitamos de los datos en nuestra profesión?). A simple vista, el título del artículo se me antojaba aburrido, soso y hasta redundante. Pues un estadístico de profesión necesita datos, de la misma manera que un médico necesita enfermos o un carpintero necesita madera.

Sin embargo, hice caso a esta recomendación y me aventuré en la tarea de entender esta lectura, que en su primer párrafo advertía que la crisis económica en Estados Unidos había impactado directamente en la educación estadística y había impulsado el cierre de varios departamentos de estadística pues definitivamente no son un buen negocio. Con tremenda introducción me dispuse a leer el artículo completo ([ver acá](http://predictive.files.wordpress.com/2009/10/asanews.pdf)) y, al finalizar la lección, tuve una incómoda sensación de preocupación. Las cosas son claras, en una sociedad como la de Estados Unidos, que tiene la asociación de estadísticos más fuerte e influyente del mundo moderno (los integrantes de ASA incluyen miembros del senado, cámara y directores de entidades gubernamentales) se están cerrando las puertas a la educación estadística con la excusa (¿pretexto?) de la coyuntura económica.

Unos días después me enteré que los rectores de las universidades públicas colombianas estaban dando de qué hablar y no propiamente en el ámbito académico. Resulta que la coyuntura económica llegó con fuerza a Colombia y ahora [no hay recursos para el fomento de la educación pública](http://www.eltiempo.com/vidadehoy/educacion/presidente-uribe-tercia-en-polemica-con-la-contraloria-por-recursos-para-la-educacion_6364827-1) (aunque paradójicamente sí hay recursos para el fomento de la guerra, el odio entre compatriotas y la protección económica de terratenientes ricos que el estado subsidia con recursos del pueblo). El gobierno pide a las universidades auto-sostenibilidad y las universidades han implementado planes en esta dirección, pero el ejecutivo no incrementa el rubro presupuestal para alivianar las cargas de la educación colombiana. Sin embargo, el tema que realmente me preocupa es que los rectores de las universidades empiecen a tomar medidas parecidas a las que tomó, por ejemplo, la Universidad Central de Florida al eliminar su departamento de estadística.

Pensemos un poco en las implicaciones que tendría esta medida. Voy a referirme a la perla de la corona en materia de educación estadística en Colombia: El [Departamento de Estadística de la Universidad Nacional de Colombia](http://www.ciencias.unal.edu.co/departamentos/index.php?id=3) (del cual soy orgullosamente egresado y al cual orgullosamente pertenezco como estudiante de posgrado). En sus más de 50 años de historia, este departamento ha logrado tener una gran visibilidad a nivel internacional y, sin temor a equivocarme, sus docentes han conseguido alcanzar un nivel muy alto en la calidad de la educación que imparten. Además de ser el semillero para que otras instituciones (públicas y privadas) inicien la difícil tarea de la educación e investigación estadística, el departamento ha logrado posicionarse con su [Simposio de Estadística](http://www.ciencias.unal.edu.co/estadistica/simposio/index.html) (el encuentro más importante de estadísticos a nivel Colombia y uno de los más reconocidos en Latino-América), con la [Revista Colombiana de Estadística](http://www.estadistica.unal.edu.co/publicaciones/estadistica/rce/index.html) (publicación indexada en las más prestigiosas bases de datos bibliográficas) y con sus programas de posgrado (a nivel de especialización, maestría y doctorado). Pues bien, si las cosas siguen así, es posible que estos entes desaparezcan. Y si desaparece el departamento, seguro desaparecerán otras carreras públicas y, siendo así, no le queda mucha esperanza a las emergentes facultades de estadística en el sector privado.

Como diría mi primer jefe… "no se preocupe, más bien ocúpese". Y es que la responsabilidad de hacerle frente a un problema tan grave como este no está sólo en manos del director del departamento o del decano de la facultad. Seguramente, esta responsabilidad debe ser compartida por todos nosotros. Estoy seguro que algunos lectores, porque seguramente los hay, dirán que esta entrada raya en lo amarillista. A esos lectores les digo, sobre todo si son comentarios en la academia, que es mejor la seguridad que la policía, la prevención que las lamentaciones. Si pasó en Estados unidos, puede pasar en Colombia. La solución no está en quedarse callado o en tomar las vías de hecho. La solución tampoco está en los argumentos que expone Crank en su artículo. La solución está en usted y en lo que, desde su sitio de confort, sea capaz de hacer.
