---
title: "Publicaciones Colombianas Online"
author: "Andrés Gutiérrez"
date: "2009-02-10"
categories:
  - "Publications"
  - "Community and Events"
---

En Colombia existen dos publicaciones cuyo tema central es la estadística. Cada una de ellas tiene diferentes características y por lo tanto llenan distintos faltantes en la escena estadística Hispanoamericana. Sin embargo, una característica común es la cultura de la divulgación de sus artículos de manera gratuita.

Esta cultura es importante e indispensable en el desarrollo de la investigación de contenidos estadísticos puesto que para acceder a un artículo simplemente se debe ingresar a la página de la publicación y desde allí es posible descargar cada uno de los archivos que conforman el volumen de cada revista.

Con todo respeto, hoy quiero hacer un reconocimiento público a la **Revista Colombiana de Estadística**, a su editora actual Piedad Urdinola y a sus editores pasados Jorge Ortiz Pinilla y Campo Elías Pardo. Desde que Jorge Ortiz recibió esta publicación empezó un proceso de transformación y posicionamiento en el escenario nacional e internacional. Su sucesor, Campo Elías Pardo, siguió esta política ubicando a la Revista Colombiana de Estadística en una mayor cantidad de índices internacionales. La editora actual está haciendo una tarea maravillosa consolidando a la revista como una de las mejores publicaciones de Hispanoamérica, a nivel internacional y, en la categoría **A** de Colciencias, a nivel nacional.

Por otro lado está la revista **Comunicaciones en Estadística** que está empezando a seguir ese difícil camino de posicionamiento nacional. Esta revista tiene un lugar diferente en la escena estadística puesto que sus objetivos a mediano plazo están enfocados en el fortalecimiento teórico y práctico de los nuevos investigadores estadísticos. Sin embargo, este camino está acompañado por un antiguo editor de la Revista Colombiana de Estadística y esto augura un camino lleno de perspectivas exitosas.

Detrás de estas dos publicaciones está el trabajo de diseño impecable de Camilo Cubides, experto en el lenguaje $LaTeX$ quien también ha prestado asesoría a otras publicaciones seriadas en Colombia.

Estimado lector, no deje de visitar los vínculos de cada una de estas publicaciones y por favor, únase a la cultura de descargar de manera gratuita los artículos de su interés. Recuerde que esto es posible gracias al esfuerzo mancomunado de personas apasionadas por la estadística que intentan poner un valioso recurso a su disposición. A continuación los vínculos a las páginas de cada publicación.

- [**Revista Colombiana de Estadística**](http://www.ciencias.unal.edu.co/publicaciones/estadistica/rce/v31-2.html)

- **[Comunicaciones en Estadística](http://www.usta.edu.co/otras_pag/revistas/comunicaciones_en_estadistica/contenido/contenido.html)**
