---
title: "La corriente Bayesiana empírica"
author: "Andrés Gutiérrez"
date: "2009-05-24"
categories:
  - "Bayesian Statistics"
  - "Modeling"
---

Lo anterior ha permitido que el investigador pueda proponer modelos que siguen comportamientos estructurales distintos y en algunos casos que se encuentran anidados en modelos más complejos. En el caso bayesiano, es claro que el momento de coyuntura en el cual el investigador no contempla un punto de retorno está dado en la formulación de la distribución a priori para el vector de parámetros de interés $btheta$. Más aún, la influencia de la distribución a priori en la resultante distribución a posteriori está dada por la asignación del vector de hiperparámetros $bEta$ que parametriza la distribución a priori. Cuando los valores exactos de los hiperparámetros se desconocen o cuando no se tiene plena certeza del comportamiento estructural de la distribución a priori, entonces es necesario estimarlos pues de estos dependen los resultados en cualquier investigación de tipo causal. En otras palabras, una mala asignación de los valores de los hiperparámetros conduce a una distribución a priori que no es acorde con la realidad y esto puede conllevar a su vez a que la distribución a posteriori no concuerde con la realidad, produciendo así resultados engañosos.

Siguiendo los fundamentos filosóficos de la estadística bayesiana, tener que estimar el vector de hiperparámetros envuelve al investigador en una paradoja cuya solución no siempre está dada por métodos bayesianos. En primer lugar, nótese la forma de la distribución a priori del vector de parámetros de interés: $p(btheta|bEta)$. A simple vista se puede concluir que $bEta$ hace parte de la distribución a priori la cual, según la lógica de la filosofía bayesiana, involucra el conocimiento del investigador antes de la recolección de los datos. Por tanto la pregunta directa que surge es ¿Por qué estimar algo que se debería suponer conocido?. En segundo lugar y si se concibe tal estimación, la otra pregunta natural es ¿Se deben utilizar los datos para estimar tales hiperparámetros?. Las posibles respuestas a las anteriores preguntas han creado toda una nueva corriente alterna a la bayesiana pura llamada la cual utiliza los métodos de estimación puntual frecuentista para estimar estos hiperparámetros y por consiguiente definir la distribución a priori del vector de parámetros de interés.

En las últimas décadas la formulación de modelos estadísticos ha evolucionado demasiado. En un principio, los modelos establecidos obedecían a reglas estándar que se suponían ciertas para toda la población. Sin embargo, el estado de la naturaleza de la mayoría de los problemas práctico no sigue una regla común para todos y cada uno de los elementos de una población aleatoria. De hecho el sentido común establece que para una misma población, pueden existir tendencias comunes entre diferentes miembros de la misma y la estructura de dispersión de los elementos puede obedecer comportamientos disímiles a través de éstos.

Lo anterior ha permitido que el investigador pueda proponer modelos que siguen comportamientos estructurales distintos y en algunos casos que se encuentran anidados en modelos más complejos. En el caso bayesiano, es claro que el momento de coyuntura en el cual el investigador no contempla un punto de retorno está dado en la formulación de la distribución a priori para el vector de parámetros de interés $\theta$. Más aún, la influencia de la distribución a priori en la resultante distribución a posteriori está dada por la asignación del vector de hiperparámetros $eta$ que parametriza la distribución a priori. Cuando los valores exactos de los hiperparámetros se desconocen o cuando no se tiene plena certeza del comportamiento estructural de la distribución a priori, entonces es necesario estimarlos pues de estos dependen los resultados en cualquier investigación de tipo causal. En otras palabras, una mala asignación de los valores de los hiperparámetros conduce a una distribución a priori que no es acorde con la realidad y esto puede conllevar a su vez a que la distribución a posteriori no concuerde con la realidad, produciendo así resultados engañosos.

Siguiendo los fundamentos filosóficos de la estadística bayesiana, tener que estimar el vector de hiperparámetros envuelve al investigador en una paradoja cuya solución no siempre está dada por métodos bayesianos. En primer lugar, nótese la forma de la distribución a priori del vector de parámetros de interés: $p(\theta|eta)$. A simple vista se puede concluir que $eta$ hace parte de la distribución a priori la cual, según la lógica de la filosofía bayesiana, involucra el conocimiento del investigador antes de la recolección de los datos. Por tanto la pregunta directa que surge es ¿Por qué estimar algo que se debería suponer conocido?. En segundo lugar y si se concibe tal estimación, la otra pregunta natural es ¿Se deben utilizar los datos para estimar tales hiperparámetros?. Las posibles respuestas a las anteriores preguntas han creado toda una nueva corriente alterna a la bayesiana pura llamada la cual utiliza los métodos de estimación puntual frecuentista para estimar estos hiperparámetros y por consiguiente definir la distribución a priori del vector de parámetros de interés... Aunque, por supuesto, no se trata de la única solución al problema de modelos jerárquicos, ésta pone en tela de juicio el andamiaje epistemológico de la teoría adjudicada al reverendo Bayes. Aunque, como suele suceder con lo bayeasiano, la puesta en marcha de los métodos bayesianos empíricos suelen arrojar resultados y mejor aún, resultados.
