---
title: "First International Workshop on Applied Statistics (Bogotá - Colombia)"
author: "Andrés Gutiérrez"
date: "2009-10-09"
categories:
  - "Community and Events"
  - "Teaching"
---

Hace mucho tiempo que Bogotá no era la sede de un evento que reuniera a varios de los más prestigiosos estadísticos de Colombia y el mundo. En esta ocasión la novel Facultad de Estadística de la Universidad Santo Tomás coadyuvada por su Centro de Investigaciones y Estudios Estadísticos (CIEES) serán los organizadores del **First International Workshop on Applied Statistics** ([clic acá para mayor información](http://predictive.files.wordpress.com/2009/10/programa_evento.docx)) que se realizará en las instalaciones de la Universidad Santo Tomás (sede Bogotá) del 9 al 12 de Noviembre del presente año.

Lo más interesante del evento es su mecánica. En esta oportunidad todos los invitados internacionales, además de conferencias darán cursillos intensivos de 18 horas sobre temas de punta en la investigación de la estadística aplicada. Lo anterior es muy interesante puesto que el participante no será bombardeado con un arsenal de conferencias que le será difícil asimilar, sino por el contrario, ***el participante será educado personalmente por los mejores estadísticos del mundo***. Siendo esa la filosofía del evento, me parece que es pertinente invitar a toda la comunidad nacional e internacional a hacerse partícipe de este taller. Entre los invitados internacionales y sus cursillos se presentan a continuación:

1. Pedro Silva (Universidad de Southampton, Inglaterra) - Cursillo: Análisis avanzado de datos muestrales ([clic acá para obtener una descripción](http://predictive.files.wordpress.com/2009/10/curso-analisis-datos-muestrales-resumo-1.doc)).

2. Víctor Guerrero (UNAM, México) – Cursillo: Estimación de tendencias de series de tiempo mediante mínimos cuadrados penalizados ([clic acá para obtener una descripción](http://predictive.files.wordpress.com/2009/10/descripcioncurso_jun09.pdf)).

3. Julio Singer (Brasil, Universidad de Sao Paulo) – Cursillo: Introducción a la teoría asintótica.

Además, el evento cuenta con la participación de varios estadísticos reconocidos a nivel nacional, no sólo de Bogotá, sino también de varias escuelas regionales en estadística. Otro tópico impresionante son las bajas tarifas del evento que se encuentran entre los cien y doscientos mil pesos.

Docente -Profesional \$200.000,00

Estudiantes Pregrado \$120.000,00

Estudiantes Posgrado \$180.000,00

> Docente -Profesional
>
> \$200.000,00
>
>
>
> Estudiantes Pregrado
>
> \$120.000,00
>
>
>
> Estudiantes Posgrado
>
> \$180.000,00

El lector interesado puede comunicarse al siguiente correo electrónico para obtener más información (sanderrangel@usantotomas.edu.co).

# **[Inscripciones aquí](http://www.usta.edu.co/index.php?option=com_content&view=article&id=429: first-international-workshop-on-applied-statistics&catid=1: latest-news)**
