---
title: "Estimadores de máxima cuasiverosimilitud en muestreo bifásico"
author: "Andrés Gutiérrez"
date: "2009-06-30"
categories:
  - "Inference"
  - "Sampling"
---

Los estimadores śoptimos de calibraciśon utilizan informaciśon auxiliar completa para

producir estimaciones mśas eŻcientes. Cuando no se dispone de este recurso, una

alternativa es realizar un muestreo en dos fases para recopilar la informaciśon auxi-

liar en una primera fase y despuśes utilizarla en el dise~no o estimaciśon de la segunda

fase. Se compara la eŻciencia de los estimadores śoptimos de calibraciśon, cuando

la relaciśon entre la variable de estudio y las variables de informaciśon auxiliar es

lineal y log-lineal. En este śúltimo caso se utilizan mśetodos de cuasi-verosimilitud

para la estimaciśon de los parśametros del modelo de super-poblaciśon.

Los estimadores óptimos de calibración (Wu & Sitter) utilizan información auxiliar completa para producir estimaciones más eficientes. Cuando no se dispone de este recurso, una alternativa es realizar un muestreo en dos fases para recopilar la información auxiliar en una primera fase y después utilizarla en el diseńo o estimación de la segunda fase. [Haciendo clic acá](http://predictive.files.wordpress.com/2009/06/2009-cuasiverosimilitud.pdf) encontrará un reciente artículo (a manera de revisión) en donde se compara la eficiencia de los estimadores óptimos de calibración, cuando la relación entre la variable de estudio y las variables de información auxiliar es lineal y log-lineal. En este último caso se utilizan métodos de cuasi-verosimilitud para la estimación de los parámetros del modelo de super-población.
