---
title: "Seleccionando muestras de café"
author: "Andrés Gutiérrez"
date: "2009-06-16"
categories:
  - "Sampling"
  - "Community and Events"
---

Acabo de salir de una reunión corta pero sustanciosa...

Érase una vez, una gentil mujer, de unos cuarenta años de edad, que me contactó a mi teléfono personal acudiendo a la necesidad de que le "ayudara" en la selección de una muestra para un estudio de investigación de mercados... Por supuesto, yo mostré toda mi disposición y acepté atenderla en mi oficina. La mujer me respondió que era mejor encontrarnos en un café en el centro de la ciudad. ¿Un café? - me pregunté - mejor sería en su oficina... La gentil y necesitada dama accedió a que la reunión se efectuara en sus instalaciones.

Hoy llegué puntual a la cita, pero para mi sorpresa el celador que atendía me recibió con una desafortunada noticia... - ¿Qué qué? - La señora se llama fulanita de tal - le respondí con afán... ¿Si? ¿y el segundo apellido? - me respondió el ingrato celador... Desde allí las cosas comenzaron al revés... Llamé a la gentil dama a su celular, le informe que acerca del insuceso en portería y así me dejó acceder a las instalaciones.

El guarda de seguridad, me guió a lo que parecía ser un salón comunal... una mesa de plástico y dos sillas VaniplaX... ¿En dónde estoy? - me pregunté y reflexioné en que hubiese sido mejor haber accedido a tener la entrevista en el café. Después de un treinta minutos, la señora se apareció con el cabello... cabello mojado y cara lavada... Hola, se me hizo tarde, siéntate... (Yeah right!!!)

Empezó contándome acerca de lo "exitosa" que era su empresa, en donde la costumbre era contratar para que hicieran el trabajo (¿sucio?). En ese justo instante me sentí desafortunado y quería concretar el diseño de muestreo rápidamente. La gentil dama escuchaba atentamente cuando le hablé de mi experiencia y del proceso científico que había detrás de la selección de cualquier muestra. Cuánto llegamos a la parte contractual, yo le hice mi propuesta económica y fijé las condiciones de pago.

Fin de la reunión.

¿Cómo? ¿Por qué? ¡¡¡Ni que la muestra tuviera oro!!!... los argumentos de la gentil dama - psicóloga de profesión - rayaban en lo ridículo. Aclaro que la muestra necesitaba de información auxiliar y que la propuesta económica era bastante asequible. ¿Cuánto tiempo se demora seleccionando la muestra?, yo tengo un estadístico que me hace eso gratis - argumentaba la señora.

Mi reflexión: 1) Yo no soy un, soy un profesiona.l 2) Quisiera conocer al estadístico que hace muestras gratis, me suena a psicólogo. 3) ¿Cuánto cuesta hacer un? Mínimo unos treinta millones de pesos ¿Habrá que estudiar siete años para hacer que unas personas conversen en el focus group?. 4) Estas gerentes de empresitas de barrio se ufanan de que están haciendo patria y empresa... No lo creo, no están haciendo patria, están lucrándose y aprovechándose de tanto administrador desempleado. Si quisieran hacer patria y empresa, entonces ni siquiera mencionarían la palabra y la cambiarían por. 5) Necesitamos una ley de verdad que cobije nuestra profesión. No más ingenieros, ni administradores, ni psicólogos seleccionando muestras gratis, muestras de café, muestras de café con mala leche... Zapatero a tus zapatos ¿Qué diría el gremio de los médicos si un administrador quisiese realizar una cirugia de miocardio?
