---
title: "La ley 379"
author: "Andrés Gutiérrez"
date: "2009-01-08"
categories:
  - "Sampling"
  - "Surveys"
---

En el [blog de Alex Zambrano](https://web.archive.org/web/20141011173557/http://alexjzc.wordpress.com/) encontré un post que contenía el [documento PDF](http://predictive.files.wordpress.com/2009/01/ley-del-estadistico.pdf) de la tan misteriosa ley del estadístico. Ley que, entre otras cosas, encuentra grandes desviaciones de la realidad en algunos de sus parágrafos. Basta con leerla para darse cuenta que, en principio, la ley está descontextualizada de la realidad que atañe a esta década.

Estimado colega, estimado lector… ¿sabías que el ejercicio profesional de la ciencia estadística está reglamentado por el congreso de la república de Colombia? Si bien es cierto que la famosa y misteriosa ley ha estado en boca de la mayoría, también es cierto que esa mayoría, entre la cual me cuento, no conoce a ciencia cierta los beneficios, derechos y deberes que la ley trae consigo. Más aún, el ejercicio del profesional en estadística se ve enmarcado bajo una especie de clandestinidad profesional que le resta un poco de seriedad al proceso científico del estadístico. Un simple ejemplo: ¿Alguien sabe cuál es el diseño de muestreo de la encuesta nacional de hogares? Me refiero al verdadero diseño muestreo… yo creo muy pocos estadísticos saben esa respuesta… Es más, una simple búsqueda en la WEB me lleva a un documento oficial que responde a la anterior pregunta de la siguiente manera:

> [El diseño de la muestra es] Polietápico, dado que para llegar a la selección de los hogares y personas objeto de investigación, se seleccionan secuencialmente las unidades de muestreo de cada tipo, con base en probabilidades de selección calculadas en función del número de unidades últimas de observación (hogares o personas).

¡Oh! Quien escribió eso debe ser un verdadero maese del muestreo. A ese tipo de clandestinidad es al que me refiero en el anterior párrafo. La misteriosa Ley olvida obligar a las entidades oficiales a revelar detalles del diseño muestreo, práctica común y corriente en países desarrollados. La ley es confusa en su lectura, razón por la cual he decidido que es una ley inútil; tan inútil como el **consejo profesional de estadística**o como la **asociación colombiana de estadísticos**, máximas entidades por las cuales, según la misteriosa ley, se regirían algunas prácticas profesionales. Tal vez sea ignorancia mía, pero… ¿alguien me puede informar acerca de la existencia de las anteriores entidades? Lo más cercano que conozco en materia de asociaciones o conglomerados de estadísticos es la **comunidad colombiana de estadística (CCE)**, que es un excelente intento por formar una cultura de cohesión en el contexto del profesional de la estadística. Sin embargo, la CCE no es una entidad oficial. Es más, la CCE existe gracias al esfuerzo de unos pocos puesto que, para pesar nuestro, si la CCE no ofreciera oportunidades laborales, serían pocos los integrantes de tal comunidad.

Siguiendo con la desinformada ley, en no pocos artículos se habla, sin diferenciación alguna, de estadísticos, tecnólogos en estadística y técnicos en estadística. Una vez más, mi restringido conocimiento me lleva a creer que en Colombia sólo existen carreras universitarias en estadística, y no tecnologías o carreras técnicas. Además, si la apertura de un programa universitario en estadística en una universidad privada (tradicional y respetada) ha causado un revuelo de magnitudes catastróficas, no me imagino si algún politécnico, fundación o instituto intentara abrir un programa de 4 o 6 semestres en estadística.

Estimado colega… ¿qué pasaría si lo anterior ocurriera? Tal vez, no estamos preparados para esta verdadera hecatombe de transición. Sin embargo, estoy seguro, que muy pronto nos encontraremos con esta clase de programas y con más competencia… y con competencia de calidad. De una cosa estoy seguro, el estadístico debe estar preparado para competir en el mercado del talento humano y ser capaz de surgir a niveles superiores sin importar su alma mater.

Tal vez, ya sea hora de salir de nuestro*sitio de confort*… tal vez ya sea hora de que nos unamos como un solo hombre y que este país nos reconozca como forjadores de un nuevo rumbo. Por mi parte, estoy cansado de que algunas personas, buenas personas y con la mejor de las intenciones, me llamen *ESTADISTA*. ¿De quién es la culpa? De nosotros. Esta famosa ley revela que nosotros no sabemos lo que ellos sí… no sabemos unirnos y no sabemos trabajar para nosotros mismos… a diferencia de ellos… ellos lo saben y están preparados… mientras tanto nosotros… en el mismo sitio de confort.

¿Tarjeta profesional? ¿ECAES? ¿Asociaciones? Tal vez sí… En la universidad Nacional de Colombia se ha venido debatiendo este tipo de temas, aunque en círculos muy pequeños, sin mayor trascendencia. Por ejemplo, hace un año, cuando este blog contaba sus primeros relatos, estaba en mente de los colombianos la reputación del DANE, por cuenta de varios escándalos externos e internos, y por ende la veracidad de las estadísticas oficiales, con las que se pretenden tomar las grandes decisiones de estado. Los maestros Leonardo Bautista y Jorge Martínez intentaron proponer nuevas vías de cohesión; sin embargo, la comunidad estadística escuhó pero no apoyó...! Error!, puesto que ellos están ahora interesándose en diferentes opciones, entre ellas las universidades privadas y ellos están haciendo muchas preguntas... preguntas que se responderían si nosotros decidieramos salir de nuestro sitio de confort.
