---
title: "Malditas estadísticas"
author: "Andrés Gutiérrez"
date: "2009-08-29"
categories:
  - "Estadística"
---

Me permito reproducir en este medio la columna de Hector Rincón aparecida en el número 843 de la revista Cambio del 27 de Agosto de 2009 al 2 de Septiembre. En esta columna de opinión el señor Rincón hace un recuento de las estadísticas sociales que maneja nuestro país: malditas estadísticas sociales.

> ### Pobre país
>
>
> por Hector Rincón
>
>
> http://www.cambio.com.co/opinioncambio/blog.php?id_blog=3396046
>
>
> El país político y el país gubernamental y el país periodístico estaban muy ocupados al comienzo de la semana en sus habituales temas clientelistas, corrompidos y faranduleros como para ponerle atención a las cifras de pobreza que gritaban más pobreza, más indigencia, pobres más empobrecidos, pobre de los pobres.
>
>
> Qué pereza los pobres. El desdén con el que suele mirarse al llevado del putas quedó otra vez en claro cuando las nuevas cifras apenas recibieron breves espacios en los medios y no oí ninguna reflexión de los gobernantes y cero de los políticos, porque los unos y los otros y los otros estaban invadidos con los asuntos que les son remunerativos: lo que va a pasar con el poder político, lo que va a pasar con el poder económico, lo que está pasando con la vida de nueve de cada diez estrellas de Hollywood.
>
>
> Y las cifras desgarran. En números gruesos en Colombia hay 20'200.00 pobres. Llámese pobres, según los tecnócratas que hacen las investigaciones, a aquellos ciudadanos que pertenecen a familias de cuatro miembros promedio que no alcanzan a recibir entre todos 1'086.000 pesos de ingresos mensuales. Hagan cuentas: 1'086.000 dividido cuatro, igual 271.500 pesos por cabeza. Cada mes. De pobres así de pobres tenemos 20'200.000, que equivalen a toda la población de Bogotá, Medellín, Cali, Barranquilla, Bucaramanga y Pereira juntas.
>
>
> Y en indigencia, las cifras no desgarran sino que desgarran y subvierten y queman. De indigentes tenemos 7'900.000 colombianos. Llámese indigentes aquellos ciudadanos que pertenecen a familias de cuatro miembros en promedio y que no alcanzan a recibir entre todos 468.000 pesos mensuales. Hagan cuentas: 468.000 pesos dividido cuatro, igual 117.000 pesos por cabeza. Cada mes. De indigentes así tenemos 7'900.000, que equivalen a la población de Bogotá más la de Armenia más la de Popayán.
>
>
> Ante cifras como esas, que expresan de manera nítida lo que en el Gobierno de la seguridad democrática y de la confianza inversionista se llama "cohesión social", ante esas estadísticas que como proclamaba Belisario Betancur reflejan las condiciones objetivas de la violencia, ante esas cifras deprimentes, el Gobierno responde con trampas.
>
>
> En la presentación de ese último informe sobre la pobreza y la indigencia, el Gobierno optó por ponerle a ellas un maquillaje grotesco: las comparó con el año 2002 para decir que la pobreza había bajado un cinco por ciento. Porque si lo hubiera asistido la honradez habría echado mano de las cifras de 2006, las últimas que había por ahí, para admitir que la pobreza desde entonces ha aumentado un uno por ciento.
>
>
> En cualquier caso, en el caso de una disminución del cinco por ciento, o de un aumento del uno por ciento; con un consolidado del tanto y tanto y tanto por ciento, comparado con el tercer trimestre, con el segundo semestre, como quieras, como quieran, en Colombia hay 20'200.000 ciudadanos que viven, que sobreviven, con 271.500 pesos mensuales; y hay 7'900.000 que escarban la vida con 117.000 pesos mensuales.
>
>
> Ante esta realidad oprobiosa, que intentan tapar con comparaciones amañadas para vender triunfos inmorales, no es necesario mucho análisis sobre los porqué de la inseguridad urbana y de la criminalidad que se extiende como una marea roja. Ante estas cifras que, ¿no sé si lo dije?, son del propio Gobierno, de Planeación Nacional, no sirve la sugerencia del general Naranjo sobre que la oleada de homicidios y de delincuencia se debe al microtráfico de estupefacientes y a la disputa por las 'ollas' en donde los venden. Solo servirá la conciencia de que de esta manera el país es inviable y será invivible hasta para los ricos si sigue progresando, como sigue, la miseria y la iniquidad. Miseria e inequidad que son tan inmensas que Colombia es el país de América Latina con peores cifras de pobreza. Pobrecitos.
