---
title: "Examen de calificación doctoral"
author: "Andrés Gutiérrez"
date: "2009-03-18"
categories:
  - "Teaching"
  - "Publications"
---

> Me estiré desde donde estaba sentado y saqué un cuaderno del cajón. Era un cuaderno de hojas cuadriculadas para cuadros y tablas, lo había comprado para la clase de estadística unas semanas antes de encontrarme con el libro pero aun no lo había usado. Lo abrí por la primera página, aspiré el olor de la hoja limpia y en blanco, cogí el bolígrafo y comencé a escribir en él frase por frase lo que me dictaba el libro. Después de pasar al cuaderno una de las frases continuaba con la siguiente y la escribía detrás de la anterior. Cuando el libro inició un nuevo párrafo y luego otro, reviví una y otra vez lo que el libro me decía. Por fin levanté la cabeza y de las páginas que había escrito y miré por un la do al cuaderno y por el otro al libro. Yo había escrito el cuaderno, pero lo que había escrito era lo mismo que decía el libro. Aquello me gustó tanto que comencé a hacer lo mimo cada noche hasta el amanecer

Tomado de

**La vida Nueva**

del gran escritor turco

**Orhan Pamuk**

(foto)
