---
title: "Estrategias de muestreo: Diseño de encuestas y estimación de parámetros"
author: "Andrés Gutiérrez"
date: "2009-11-13"
categories:
  - "Estadística"
---

Es un honor poder compartir con ustedes mi primer libro... pueden estar seguros que este es el comienzo de una nueva cultura de la estadística aplicada en Colombia y en hispanoamericana... vendrán más, muchísimos más. Como [había anunciado antes](../books.qmd), este libro está divido en tres partes. La primera parte trata con rigurosidad los diseños de muestreo para elementos y conglomerados y es apta para el aprendizaje exhaustivo del muestreo. La segunda parte trata con la incorporación de información auxiliar en la etapa de estimación en donde surgen los estimadores de regresión, los estimadores de calibración, el método de raking y el IPFP. Además, esta parte adjunta un muy buen capítulo de estimación de parámetros finitos bajo modelos (model-based survey sampling). La tercera parte trata con temas más complejos como diseño de muestreo y estimación en encuestas multi-propósito, muestreo balanceado, muestreo indirecto y muestreo en dos fases.

Mi objetivo es que este libro se convierta en una guía no sólo académica sino práctica y que el profesional, estadístico o no, que se encuentre involucrado en el diseño, implementación y ejecución de encuestas encuentre en este texto un baluarte que le permita relizar su trabajo profesional con mejor eficiencia.

Gracias, muchas gracias, en primer lugar a Dios, y a ustedes... Todos ustedes son la razón de este blog, de las publicaciónes en revistas y de este libro y los otros que vendrán.

PD1: En la foto, al lado izquierdo este servidor, en el centro mi libro y al lado derecho Pedro Silva, profesor de la universidad de Southampton en Inglaterra y expresidente del InterAmerican Statistical institute (IASI), el personaje latinoamericano más influyente en el mundo del muestreo.

PD2: [La página oficial del libro es esta](../books.qmd). Allí encontraran las soluciones a los ejercicios, el paquete base en R ([TeachingSampling package](../software.qmd)), las erratas y las actualizaciones que haré.
