---
title: "The elements of statistical learning"
author: "Andrés Gutiérrez"
date: "2009-10-15"
categories:
  - "Estadística"
---

Con gran sorpresa me enteré que el libro The elements of statistical learning de Trevor Hastie, Robert Tibshirani y Jerome Friedman [se encuentra disponible de manera gratuita](http://www-stat.stanford.edu/~tibs/ElemStatLearn//). Este libro trata de minería de datos, inferencia y predicción estadística. en palabras de los autores:

> Los desafíos en el aprendizaje a partir de datos han conducido a una revolución en la ciencia estadística. Dado que la computación juega un papel clave, no es sorprendente que gran parte de este nuevo desarrollo haya sido realizado por investigadores de otros campos como las ciencias de la computación (computer sciences) y la ingeniería.
>
>
> Además, los retos en la áreas de almacenamiento de datos, la organización y la búsqueda han llevado al nuevo campo de la "minería de datos"; los problemas de estadística e informática en el campo de la biología y de la medicina han creado "bioinformática". Enormes cantidades de datos se están generado en muchos campos, y la tarea del estadístico es darle sentido a estos datos y extraer los patrones y tendencias, y entender lo que dicen los datos. A esto lo llamamos "aprendizaje a partir de los datos".
