---
title: "¡Que no es estadista, es estadístico!"
author: "Andrés Gutiérrez"
date: "2009-09-05"
categories:
  - "Community and Events"
  - "Publications"
---

La semana pasada llegó a mi correo electrónico una oferta laboral enviada por el programa de egresados de la Universidad Nacional de Colombia. Los términos de referencia eran los siguientes:

> De manera atenta nos permitimos informarles de la siguiente oferta laboral.
>
>
>
> CONVOCATORIA: 1009
>
>
> ENTIDAD SOLICITANTE: PROYECTO DE INTERVENTORIA DE LA ALIMENTACIÓN ESCOLAR- DPTO DE NUTRICION Y DIETETICA.- UN
>
>
> 1. FORMACIÓN ACADÉMICA SOLICITADA: ESTADISTICA
>
> 2. CARGO:
>
> **ESTADISTA**

La verdad que ya estoy cansado de que se confundan estos conceptos. Es cuestión de sentido común… una entidad de nutrición dietética no puede ir campante mandando correítos y anunciando que se ha abierto una convocatoria para el cargo de estadista.! Es simplemente absurdo¡Además el nombre de nuestra profesión lleva una tilde en la primera i, lo que no ocurre con el nombre del oficio de quien dirige un estado. Esta es una buena herramienta para empezar a difundir el verdadero nombre de nuestra profesión.

Y si la anterior alusión al sentido común no funciona, tomaré las vías de hecho de una vez por todas. Ahí está, cada vez que un abogado me diga estadista, yo le diré tinterillo. Si el error proviene de un médico, yo le diré tegua o matasanos y si es de especialidad ortopedista pues nada que hacer, le diré sobandero. Por supuesto, haré esa reflexión seguida de la nemotecnia de la tilde en nuestra profesión para que no se molesten.
