---
title: "Algunos cambios contra el Alzhéimer"
author: "Andrés Gutiérrez"
date: "2010-10-21"
categories:
  - "Community and Events"
  - "Publications"
---

Por si usted no lo sabe, cada uno de nosotros está en una competencia. Se trata de usted contra su primo alemán, el señor Alzheimer. Hace poco escuché que esta enfermedad está relacionada con los hábitos monótonos cultivados por décadas. Nada más fastidioso que un viejito lleno de mañas. Un conferencista famoso ha dicho que una de las tácticas para evitar caer en estos horribles hábitos monótonos está al alcance de la mano y se trata de: el cambio. Cambiar la forma de vestir, cambiar la ruta de camino a casa o al trabajo, cambiar de residencia, cambiar, cambiar y cambiar. De esta manera, el cerebro se ejercita.

Por tanto, para sacar una ventaja considerable en esta competencia he decidido cambiar algunas cosas de forma, no de fondo, en la apariencia de este blog y también en la red social que nos cobija, Facebook. He querido dar color al blog, por esto el tema ha cambiado y también el tipo de letra y los encabezados. Por otro lado, he decidido terminar con el grupo social en Facebook, en parte por las limitaciones que restringían la comunicación eficaz entre los integrantes. Esta comunidad en la red social ahora estará cobijada por una página WEB dentro de Facebook. Para hacer parte de esta nueva plataforma puede hacer clic en el botón ME GUSTA de la [página oficial del Apuntes en Estadística](http://www.facebook.com/pages/Apuntes-de-Estadistica/170838552930678) en Facebook.

¡Un abrazo desde Colombia!

Andrés Gutiérrez
