---
title: "Posts más leídos en este 2010"
author: "Andrés Gutiérrez"
date: "2010-12-31"
categories:
  - "Estadística"
---

Ha sido verdaderamente un año muy completo... gracias a todos por leer, comentar y compartir las entradas de este blog... Feliz y prospero 2011. A continuación los artículos más leídos:

1. [La curtosis, una medida ampliamente conocida pero malinterpretada….](2010-02-12-la-curtosis-una-medida-ampliamente-conocida-pero-malinterpretada.qmd)

2. [Modelos estadísticos](https://web.archive.org/web/20101101165821/http://predictive.wordpress.com/2008/06/22/modelos-estadisticos-2/)

3. [Seis simples técnicas para la presentación de datos](https://web.archive.org/web/20101101094609/http://predictive.wordpress.com/2008/05/03/seis-simples-tecnicas-para-la-presentacion-de-datos/)

4. [Diagrama de torta](2009-08-26-diagrama-de-torta.qmd)

5. [Historia de la probabilidad (Era Primaria)](2008-10-04-historia-de-la-probabilidad-era-primaria.qmd)

6. [Muestras representativas](https://web.archive.org/web/20101205055928/http://predictive.wordpress.com/2007/09/03/muestras-representativas/)

7. [Métodos multivariados en Excel](https://web.archive.org/web/20101101165513/http://predictive.wordpress.com/2008/03/31/metodos-multivariados-en-excel/)

8. [Acerca de la estadística Bayesiana](https://web.archive.org/web/20090329224654/http://predictive.wordpress.com/2008/04/08/no-rotundo-a-la-estadistica-bayesiana/)

9. [El gremio se pronuncia acerca de las recientes encuestas electorales de las elecciones en Colombia](2010-04-12-el-gremio-se-pronuncia-acerca-de-las-recientes-encuestas-electorales-de-las-elecciones-en-colombia.qmd)

10. [Breve historia del muestreo (Design-based & Model-based)](2009-04-15-breve-historia-del-muestreo-design-based-model-based.qmd)

Saludos a todos desde Colombia!!!!
