---
title: "Análisis de datos. Métodos y ejemplos (Lagrand & Pinzón)"
author: "Andrés Gutiérrez"
date: "2010-08-06"
categories:
  - "Estadística"
---

Escribir esta entrada representa para mi una gran alegría. Se trata del trabajo realizado por Claude Langrand y Luz Mary Pinzón, publicado por la editorial de la Escuela Colombiana de Ingeniería Julio Garavito. Este libro que fue publicado en el 2009, puede convertirse en una guía continua para el profesional cuyo trabajo está ligado al análisis de datos y aprovechamiento de la información, máxime cuando en sus implementaciones prácticas utiliza el software SPAD. A continuación reproduzco la presentación que los autores hacen de su libro:

> Este libro está dirigido en especial a estudiantes de ingeniería, de maestría en matemáticas aplicadas, informática, ciencias económicas y gestión, así como a investigadores, profesores e ingenieros, que cuentan con importantes bases de datos de donde deben extraer información sintética necesaria para la toma de decisiones.  De manera más amplia, lo pueden utilizar estadísticos, administradores y toda persona que posea conocimientos elementales en estadística, con habilidad para visualizar una representación geométrica en un espacio dado y con deseos de comprender los fundamentos de los métodos disponibles en los programas estadísticos a los que se tiene acceso actualmente.

Este obra puede ser adquirida [haciendo clic acá](http://www.lalibreriadelau.com/libros-de-estadistica-ca39_79/libro-analisis-de-datos-metodos-y-ejemplos-p25357).
