---
title: "Feliz día estadísticos"
author: "Andrés Gutiérrez"
date: "2010-10-20"
categories:
  - "Estadística"
---

Hoy, 20 de octubre de 2010, el mundo celebra el día mundial de la estadística. Esperemos que sea la primera de muchas celebraciones como reconocimiento al valor y aporte de los estadísticos en el mundo.

Esta es una iniciativa de las Naciones Unidas, y su objetivo es celebrar el papel y la importancia de la estadística y dar a conocer muchos de los logros de las estadísticas oficiales. Estas celebraciones están teniendo lugar en todo el mundo. Para conocer lo que esta sucediendo en tu parte del mundo puedes acceder a la [página oficial del WSD](http://unstats.un.org/unsd/wsd/) (World Statistics Day).

Por ejemplo, en Estados Unidos, las asociaciones de estadística y las agencias federales de estadística ofrecerán un desayuno en el Capitolio; en Hong Kong, el departamento de censos ha organizado varias actividades incluyendo cursos en medición y mejoramiento de encuestas y una mini-exhibición sobre las estadística oficiales; en Italia, el edificio ISTAT se cubrirá con una gran cortina y sobre esta se proyectará un video conmemorativo a la estadística; la agencia de estadísticas canadienses ha producido el [este video](http://www.youtube.com/watch?v=ntU3_x6PqpY&sns=em) para honrar este día; En Australia se ha inaugurado una nueva publicación que promueve el uso de la estadística en el diseño de las políticas publicas basadas en evidencia estadística.

Aprovecho entonces esta oportunidad para congratularme con los lectores de este blog y desear a todos un muy feliz día. Y en tu país, ¿qué está ocurriendo?
