---
title: "Muestreo y análisis de encuestas en R (Parte I)"
author: "Andrés Gutiérrez"
date: "2010-04-29"
categories:
  - "Estadística"
---

Hace algunos años cuando cursaba las materias de muestreo I y II en mi *alma máter*, la Universidad Nacional de Colombia, Sede Bogotá, me preguntaba si al igual que en los métodos estadísticos tradicionales - como la regresión, el análisis de correspondencias o las pruebas t - habría algún software que permitiera realizar estimación de totales o medias para distintos diseños de muestreo. Mi búsqueda comenzó en SPSS, Minitab, Statgraphics, entre otros. El resultado fue desalentador aunque motivador. En efecto, en ese entonces no existía, y dudo que ahora exista, un paquete computacional de clic-clic amigable con el cual realizar inferencias sobre los totales o medias. Ahora, gracias a las ventajas de R y SAS existen varios paquetes de muestreo que si bien no son de clic-clic, si permiten enfocarse en el diseño de las encuestas y dejan de lado la difícil tarea de la programación.

[Haciendo clic acá encontrará una presentación](http://www.box.net/shared/4gg5i2v58z) que incluye, en esta primera entrega, el diseño y análisis de una encuesta contemplando diseños de muestreo básicos que se implementan con la ayuda de un marco de muestreo de elementos. Esta puede ser una ayuda útil tanto para estudiantes y docentes del curso de muestreo, aunque también puede ser utilizado por los profesionales del diseño y análisis de encuestas.

El objetivo de la presentación es conocer las bondades y desventajas de las principales estrategias de muestreo cuando se tienen marcos de muestreo de elementos utilizando programación en R. Los temas tratados: R, Marco y Lucy, estrategias para muestreo Bernoulli, estrategias para muestreo aleatorio simple, estrategias para muestreo aleatorio simple con reemplazo, estrategias para muestreo sistemático.

Actualización 1: La presentación puede ser descargada también desde acá. ([TeachingSampling](http://predictive.files.wordpress.com/2010/04/teachingsampling.pdf))
