---
title: "El gremio se pronuncia acerca de las recientes encuestas electorales de las elecciones en Colombia"
author: "Andrés Gutiérrez"
date: "2010-04-12"
categories:
  - "Elections"
  - "Surveys"
---

Empiezo esta entrada con un [vínculo](http://www.semana.com/noticias-confidenciales/margen-error/137485.aspx) que el [Doctor Daniel Diaz](http://estocasticos.wordpress.com/) me hizo llegar… Se trata de un comentario con aíres de jocosidad acerca de una situación que se presentó la semana pasada con un estudio de opinión que realizó una empresa de investigación de mercados y que conmovió profundamente la situación electoral en Colombia. Al respecto la revista semana afirma que:

> Cuando se hizo la tabulación arrojó el desconcertante resultado de que Mockus estaba ligeramente por encima de Juan Manuel Santos. Los directivos de la firma se sorprendieron tanto que pensaron que se podía tratar de un error metodológico o de trabajo de campo y, ante la duda, decidieron volverla a hacer. El resultado es el conocido: Santos 29,5 por ciento y Mockus 24,8 por ciento. Lo curioso es que ambos resultados son compatibles y coherentes estadísticamente, pues en los dos casos hay un empate técnico si se tiene en cuenta el margen de error.

Acerca de lo anterior, tengo que compartir mi alegría porque según estas cifras es posible que el candidato de mi preferencia logre la primera magistratura en los comicios presidenciales que se acercan. Sin embargo, debo también compartir mi profunda tristeza y decepción por las grandes fallas técnicas que se presentan en esos estudios de opinión, tan familiares en nuestra sociedad, los cuales no pueden ser catalogados ni siguiera como una imitación de encuesta (mucho menos se puede decir que hay muestreo en la selección de los individuos).

Desde la perspectiva del ojo experto, la anécdota que comparte la revista semana debería ser suficiente para desacreditar cualquier informe técnico de estas empresas encuestadoras… "eh, repitamos la encuesta, ya que no hay nada mejor que hacer…" Para los lectores de este blog, debe ser [bien conocida la apatía que promulgo por estas prácticas](2010-02-03-tribulaciones-en-el-tiempo.qmd)… Desde mi punto de vista, el desconocimiento de las buenas prácticas estadísticas me parecen una oportunidad para jugar a voluntad con la opinión pública, ligada directamente con los destinos de nuestro país. Póngase una vez más en el lugar del gerente de marca de una empresa privada que ha contratado una investigación de mercados… Se realiza el estudio y el procesamiento arroja que su producto está por debajo de lo esperado… La solución con este tipo de prácticas es: "No digan nada y repitamos la encuesta hasta que cuadren los resultados." Por Dios, a cuánta gente habrán engañado estos tíos… Es obvio que al pueblo se le engaña fácilmente, pero estas personas son capaces de engañar a gerentes de mercadeo instruidos en las mejores universidades. ¡Eso debe acabar!

Aparte de los detalles éticos, los inconvenientes técnicos de estos mediocres estudios son inconmensurables… Al respecto, por medio de mi colega Laura Amaranta Carrillo León, he podido tener acceso a un pronunciamiento realizado por varios expertos en muestreo y análisis de encuestas en Colombia. [Haciendo clic acá podrá tener acceso a este valioso comunicado](http://predictive.files.wordpress.com/2010/04/pilas-con-las-encuestas-electorales-3.pdf) que muy honrosamente se me permitió difundir por este blog. Al respecto, basta decir que cada día nuestro gremio debe estar más unido y debe pronunciarse, así como en esta ocasión, seriamente en temas concernientes con el análisis de datos (no solo provenientes de encuestas). Mis comentarios son de solidaridad con esta misiva y no me queda más que agradecer a mis colegas por su sentido patriótico de pertenencia y por el excelente trabajo que hicieron al plasmar en palabras del día a día los detalles técnicos. Comedidamente invito a los lectores a estudiar detenida y cuidadosamente cada una de las diapositivas que conforman el informe y a difundirlo entre sus allegados.
