---
title: "¿Nuestro gremio sin profesión?!oportunidad de agremiación!"
author: "Andrés Gutiérrez"
date: "2010-02-26"
categories:
  - "Estadística"
---

Derly escribe lo siguiente desde Bogotá:

> Hola Andrés,
>
>
> Me parecería chévere que comentaras algo acerca de este intercambio de mails que tuve con una persona de [ELEMPLEO. COM](http://www.elempleo.com/) en tu blog. Están relacionados con una sugerencia que yo hice, acerca de que incluyeran la profesión de ESTADÍSTICA en el formulario de ingreso, pues [al parecer la confunden con ESTADISTA](2009-09-05-que-no-es-estadista-es-estadistico.qmd). Es una invitación a reflexionar, al grado de evolución que existe en el mercado laboral para los estadísticos. Mientras en países como EE. UU. o algunos países de Europa, existen páginas de empleo específicas para perfiles analíticos y estadísticos, aquí en Colombia ni siquiera sabemos que existen y qué hacen los estadísticos. Adicionalmente la señora habla como si la estadística fuera de menor importancia que una carrera del común como un Ingeniero, Economista, Administrador, etc…y peor aún habla de una HOMOLOGACIÓN...(????)
>
>
> Es más, me parecería ideal que los que quisieran nos uniéramos para que también escribiéramos a [ELEMPLEO. COM](http://www.elempleo.com/), indicando las importantes razones de incluir nuestra carrera, dentro de las posibles e importantes carreras de los profesionales del país.

La cadena de mensajes dice lo siguiente:

> Hola Buenas tardes
>
>
> Quería sugerir que en la lista de profesiones cuando se rellena el formulario de información personal, incluyan la profesión ESTADÍSTICO. Actualmente hay una que se llama ESTADISTA y no se si refieren a un profesional en ESTADÍSTICA, pues la profesión y título se llama ESTADÍSTICA. [Nótese que] ESTADISTA, es una persona experta en temas del estado, como el presidente de la república.
>
>
> Agradezco tomen en cuenta esta apreciación.

Los señores del portal de internet respondieron lo siguiente:

> Estimada usuaria:
>
>
> De acuerdo a su sugerencia. Es importante que usted sepa que las compañías realizan búsquedas por las profesiones genéricas y es muy importante que trate de homologar su titulo a alguna de las profesiones que existen. No es una cuestión de incluir o no una profesión en nuestro portal, el punto es que el filtro no será utilizado por las empresas y de esta manera no serán ubicados en la base de datos.
>
>
> Sin embargo se esta trabajando en un rediseño de la página donde se controlará esta variable. Es importante dejar claro su perfil profesional para que cuando sea leída por las empresas sepan su profesión real.

Deerly respondío así:

> Estimada.
>
>
> Es importante que también usted sepa, que dentro de las ofertas que publican SÍ EXISTEN ofertas especificas para profesionales en ESTADÍSTICA y también es importante que usted sepa que esta carrera NO TIENE homologación con una carrera del común, pues es una ciencia independiente. Creo que la cuestión SÍ es de incluir la profesión en e listado.

*My reply*:

Estoy de acuerdo con Derly, da tristeza... Ahora, la mayor parte de mi tristeza se genera con el gremio... Por una parte, la señora que responde los correos y por ende el portal ELEMPLEO. COM no están enterados enterados de que existe nuestra profesión, eso da tristeza. Ahora, frente al reclamo de Derly, no muestran señas de querer incluir a nuestra profesión en la base de datos, eso genera más tristeza. Pero, que el gremio se haya quedado en su [sitio de confort](2009-04-04-la-humildad-del-gremio.qmd) y no haga nada al respecto, o no se interese por difundir su profesión, genera mucha mucha tristeza.

La mayoría de colegas egresados en Colombia ejerce su profesión desde una oficina y dado que somos pocos, es muy importante generar voz a voz acerca de lo que hacemos y del nombre correcto de nuestra profesión. Si conseguimos ser reconocidos allá afuera, las puertas se abrirán aún más, mucho más.

Por otro lado, insisto en que es absurdo que una carrera con más de 50 años de existencia sea confundida... Pero eso de la confusión es lo de menos, ¿cómo puede ser que con 50 años no exista una asociación colombiana de estadística? - O mejor, existe pero en Facebook... Yo he escrito al administrador de esa comunidad en repetidas ocasiones y jamás me ha respondido. - Así que, si la que existe no funciona, creemos una que sí funcione... Una asociación gremial con personería jurídica adscrita al ministerio del interior... una asociación con junta directiva que apruebe los estatutos y que tramite este tipo de asuntos. Una asociación que ejerza inspección, registro, control y vigilancia de los profesionales.

Estoy seguro que si el presidente de tal asociación le escribiera a ELEMPLEO. COM, la respuesta del portal hubiese sido otra... Mientras tanto, no podemos seguir en el sitio de confort huyendo de la sabiduría y del sentido común: . Despertemos y hagamos algo, la solución no es incluir a nuestra profesión en un portal de internet, no se trata de eso... se trata de hacernos fuertes, de hacernos interesantes para el mercado laboral, se trata de asociarnos.

PD: Mientras tanto, escribiré al portal siguiendo el valiente ejemplo de Derly. Si alguno está interesado en escribir, el contacto es Monica Patricia del Valle y su correo es [mondel@elempleo.com](mailto:mondel@elempleo.com)
