---
title: "Tribulaciones en El Tiempo"
author: "Andrés Gutiérrez"
date: "2010-02-03"
categories:
  - "Surveys"
  - "Policy Evaluation"
---

Yo no sé cuál es el proceso de edición de un periódico colombiano tan importante como El Tiempo; de lo que sí estoy seguro es que alguien (¿algunos?) debe revisar las columnas que allí se escriben. Está bien, supongamos que el supervisor del redactor no lee todos los contenidos a fondo, pero estoy seguro que el titular sí lo lee… Y un titular llamativo invita a leer el contenido de la columna. Ahora, no hay nada más llamativo que la publicación de cifras, y no hay nada más entretenido para el pueblo ignorante que las cifras manipuladas. Así que, casi se puede afirmar con seguridad que los titulares amañados de tan respetable diario no fueron un error del reportero sino que, por el contrario, dan cuenta de alguna movida política o algo por el estilo.

Y es que concluir que, [mediante un sondeo de la empresa Datexco](http://www.eltiempo.com/archivo/documento/MAM-3816273), el 85.4% de personas votaría para que el actual presidente sea candidato, es equivalente a que el ciudadano de a pie, en la vida real, en las urnas reales, se vea en la obligación de votar a favor de la continuidad del actual mandatario. Que un periódico con tan alta circulación afirme que tal porcentaje de personas votará a favor, es equivalente a promulgar un decreto en el inconsciente colectivo de este pueblo ignorante, mi pueblo colombiano.

Cada vez que leo este tipo de noticias me sonrojo y miro al suelo con pena ajena… pena de patria… Si una institución privada como El Tiempo es susceptible de tal manipulación, cuánto más no lo serán entidades públicas, que manejan las valiosas estadísticas oficiales, como el DANE, y que tienen en sus altos mandos a comodines políticos que están allí no por su alto grado de competitividad, ni por su preparación académica, ni por su experiencia en el sector, sino porque son convenientes y maleables.

Por otro lado me pregunto ¿por qué no ha dado la cara el representante de la empresa Datexco? Él debería estar en la obligación de desmentir el titular de El Tiempo… El señor en cuestión, debería entender que esas cifras malintencionadas le hacen daño a su negocio… ¿Así de seria es la empresa Datexco cuando realiza investigaciones de mercado? Póngase a pensar que si usted fuera el gerente de marca de una multinacional de productos lácteos y, de repente, contrata a Datexco para la realización de una investigación de mercados para saber que tanto se vendería un nuevo producto en el mercado. Bien, pasan los días y llega el tiempo de la presentación del informe técnico y los analistas de Datexco concluyen que el 85.4% de la población compraría su producto… Súper, con esas cifras usted empieza a movilizar todo su arsenal porque está seguro que su producto va a arrollar a la competencia y, por consiguiente, va a generar millones de dólares en ganancias. En resumen, usted pagó 50 mil dólares por la investigación, 60 mil dólares en la producción de la pauta publicitaria, 200 mil dólares en la pauta televisiva y 2 millones de dólares en la producción y distribución de su nuevo producto… Tres meses después, usted se da cuenta que su producto es un fracaso… los accionistas están muy molestos por esas decisiones mal tomadas… usted revisa las conclusiones de Datexco y ¡oh sorpresa! los "analistas" de Datexco olvidaron decir que sólo un 3% de la población consume productos lácteos, y que dentro de ese 3% el 85.4% sí compraría su producto.

Si uno piensa con detenimiento en la situación anterior concluye que vale un pepino la plata de los comerciales, la plata de las pautas y la plata del yogur no consumido. Vale un pepino frente a la desestabilización de las instituciones, frente a la corrupción amangualada de quienes están en el poder, frente a más vidas perdidas y olvidadas por causa de los falsos positivos, frente a una realidad social que deja en la pobreza a más de veinte millones de compatriotas y en la miseria a más de ocho millones.

PD1: Cabe aclarar que no soy guerrillero, no soy amigo de las FARC y soy más bien conservador.

PD2: Gracias Daniel.

PD3: [Clic acá para ver el análisis real](http://www.lasillavacia.com/historia/6292?page=2) de la información de la encuesta.
