---
title: "El proyecto IPSUR"
author: "Andrés Gutiérrez"
date: "2010-07-31"
categories:
  - "Estadística"
  - "R"
---

En Julio de este año, salió al ciberespacio la obra maestra de G. Jay Kerns. Él ha escrito una obra de alto talante que personalmente siempre quise leer... Se trata de un compendio introductorio de probabilidad y estadística con R... pero cuando digo con R quiero decir que R hace parte fundamental en la lectura y comprensión del texto... Se puede decir que el libro tiene dos partes: la primera enfocada con temas de probabilidad y la segunda con técnicas estadísticas. sin descartar la segunda, me parece que este texto resalta por su excelencia en la escritura de la primera parte... En los cursos de servicios de Probabilidad y Estadística es difícil realizar aplicaciones prácticas de probabilidad con algún software estadístico como SPSS o MINITAB o SAS y la estrategia del docente se remonta a la diagramación en tablero de árboles de porbabilidad siguiendo fielmente la teoría del libro de texto. Sin embargo, esta obra de Kerns, le permite al profesor llevar de la mano la teoría junto con la enseñanza de un software estadístico. Si el lector nota bien, se dará cuenta de que lo anterior conlleva a no sólo enseñar una matería sino también inculcar en el subconciente colectivo de la calse la necesidad de la computación para realizar estadística y la cultura del aprendizaje de R, hoy por hoy el más importante e influyente software estadístico en las aulas de clase. Me gusta este enfoque y fue precisamente lo que tratamos de hacer en <<[Teoría Estadística: Aplicaciones y Métodos](2010-04-07-nuestro-libro-de-estadistica-teoria-estadistica-aplicaciones-y-metodos.qmd)>> con los temas de inferencia estadística... llevar conceptos importantes como suficiencia, completez, insesgamiento, cotas de varianza a un lenguaje computacional estándar que sirviera como baluarte fundamental en la enseñanza de tales temas.

La segunda sección del libro de Kerns comprende técnicas estadísticas como pruebas de hipótesis, regresión o series de tiempo. No voy a ahondar en esto pues hay ya muchos libros que unifican estos conceptos con el software R. Esta obra [hace parte de un proyecto](https://web.archive.org/web/20100730113926/http://ipsur.r-forge.r-project.org/book/index.php) adelantado por el mismo Kerns y por G. Andy Chang de la Youngstown State University. Como hace parte de un proyecto GNU... pues ¿adivinen qué?... sí, es grátis... [la descarga del libro es gratis](http://www.lulu.com/product/file-download/introduction-to-probability-and-statistics-using-r/12037733) y viene acompañada de la descarga del paquete de R. Ahora, que si lo quiere tener en formato de papel y así apoyar al autor, pues sólo [debe adquirir su copia impresa por no más de 30 dólares americanos](http://www.lulu.com/product/tapa-blanda/introduction-to-probability-and-statistics-using-r/12037732). Si usted ya es usuario de R siga las siguintes instrucciones para accede al paquete y al libro:

```
install.packages("IPSUR")
library(IPSUR)
read(IPSUR)
```

Pero esto apenas empieza, dado que es parte de un proyecto GNU, el autor de esta obra ha puesto a disposición de la comunidad [los códigos LaTeX](https://web.archive.org/web/20100730114349/http://ipsur.r-forge.r-project.org/book/downloads.php) para que usted los modifique y pueda construir su propio libro (debe tener en cuenta el manejo de Sweave, LaTeX y BibTeX). Se trata de una obra sin antecedentes, no sólo por su contenido (libro y paquete) sino por el alcance que estoy seguro va a tener en el mediano plazo dadas sus técnicas de comercialización.
