---
title: "Meta-Análisis estadístico de encuestas electorales en Colombia: El fenómeno de Familias en Acción"
author: "Andrés Gutiérrez"
date: "2010-06-08"
categories:
  - "Estadística"
---

Hace varios días quería escribir esta entrada que, aunque al día de hoy puede parecer un poco desactualizada, tiene una connotación estadística interesante. Si no la escribí en su tiempo pertinente fue por dos motivos: el primero emocional, causado por la decepción que me produjo los resultados electorales en Colombia y el segundo terrenal, pues estaba ausente de mi sitio regular de trabajo (aunque seguía trabajando, por supuesto). Ahora que en mi vida todo vuelve a la normalidad y la interesante rutina toma su lugar, es tiempo de reflexionar y comentar este interesante fenómeno, no sin antes agradecer a mi maestro LGDM por haberme transmitido desde la distancia su parecer, el cual motivo esta entrada. En primer lugar quiero introducir algunos conceptos que el lector desprevenido debe interiorizar para un mejor entendimiento del tema y luego de contextualizar la coyuntura electoral colombiana pasaré a exponer la idea principal y las conclusiones de este fugaz estudio.

Para entrar en materia es necesario exponer que mucho descubrimientos de la ciencia médica han tenido lugar debido a que la estadística ha incorporado entre su arsenal de herramientas una técnica basada en la recopilación de observaciones de diferentes estudios en diferentes tiempos e incluso en diferentes países y regiones. Se trata del [meta-análisis](http://es.wikipedia.org/wiki/Metaan%C3%A1lisis), que según información de la red, fue empleado por primera vez por Eugene V. Glass en 1976 y es usado con autoridad y como evidencia en muchas publicaciones científicas médicas de renombre internacional. Para los escépticos, hay que afirmar que esta técnica fue utilizada por primera vez por el señor por Karl Pearson a principios del siglo pasado para palear los problemas que se presentan cuando se trabaja con tamaños de muestra pequeños.

El lector se preguntará cuál es la relación entre estos estudios clínicos con el título de esta entrada. Pues bien, se trata de analizar rápida y empíricamente el comportamiento de la tendencia electoral en Colombia para luego contrastarla con los resultados reales de las votaciones… El análisis se hará teniendo en cuenta los resultados de las encuestas electorales de los últimos meses, tal y como lo haría un investigador médico con un conjunto de experimentos, tal y como lo sugiere el meta-análisis. Es claro que no se tienen experimentos controlados pero dado que el tamaño de muestra final es elevado, este supuesto se puede omitir, máxime cuando los resultados de las encuestadoras no fueron disimiles.

Yo siempre he afirmado que no soy dogmático de ninguna rama de la estadística; aunque como conocedor de los temas de muestreo presté poca importancia a la validez individual de cada resultado que las firmas encuestadoras colombianas presentaban en sus sondeos de opinión. Sin embargo, la tendencia de un empate técnico era clara, continua y contundente. Ahora, apelando a la [teoría estadística de la inferencia en poblaciones finitas basada en modelos poblacionales](2009-04-15-breve-historia-del-muestreo-design-based-model-based.qmd) y reuniendo las observaciones de las distintas encuestas - justo como en el meta-análisis - se llega no sólo a un tamaño de muestra alto, sino a conclusiones similares, pero esta vez respaldadas por las técnicas estadísticas. El lector estará de acuerdo conmigo en que, bajo este escenario, la reunión de tantas y tantas observaciones no es una cuestión de poca importancia.

Con base en lo anterior, se podría afirmar que existe evidencia estadística de que la votación de la primera vuelta de las elecciones presidenciales en Colombia no sería otra cosa que una reñida puja entre el candidato del oficialismo y el candidato independiente. Sin embargo, la realidad de las votaciones arrojó otro escenario muy distinto al que sugería la estadística. El candidato oficialista obtuvo una ventaja de tres millones de votos frente a su inmediato contendor independiente… ¿Qué paso?, esa fue la pregunta que, con seguridad, fue planteada por más de tres millones de votantes simpatizantes del candidato independiente. Si por un lado, y con poca validez estadística, las encuestas realizadas pronosticaban un empate y por el otro, y con harta validez estadística, el meta-análisis parece concluir de la misma manera, ¿qué diantres pasó?

Yo no sé con seguridad si lo que voy a afirmar a continuación sea la respuesta a la pregunta, pero si sé que explica muy bien el fenómeno. Dos argumentos, los siguientes:

Primero: en Colombia existe un programa gubernamental de ayuda a la población menos favorecida del país (que lamentablemente es la gran mayoría). [Cifras oficiales](http://www.businesscol.com/noticias/fullnews.php?id=10901) indican que unas tres millones de familias están activas en este programa que provee una ayuda de entre 10 a 15 dólares mensuales. Para recibir esta ayuda es necesario demostrar que la familia es pobre, muy pobre. Segundo: volviendo a los supuestos del meta-análisis, la mayoría de las encuestas fue realizada en los principales municipios y ciudades del país de forma telefónica y unas pocas se hicieron por interceptación en la calle. Lo anterior no garantiza la homogeneidad y control de un experimento de laboratorio. A todas las encuestadoras se les olvidó que la gran mayoría de Colombianos con teléfono no pertenece a ese cúmulo de familias que reciben ese beneficio del estado; si no tienen dinero para comer mucho menos para pagar las cuentas del teléfono… Grave error si se quieren realizar pronósticos en un país en donde la regla es la pobreza… A todas las firmas de sondeos de opinión se les olvidó que la política de este gobierno está basada en la mano dura y que es de todos conocida la injerencia indirecta del estado en la contienda electoral… Grave error porque ya era bien sabido que se había amenazado a los beneficiarios de Familias en Acción de que el candidato independiente anularía este programa y los perjudicaría directamente… Grave error si se tiene en cuenta que tres millones de votantes pobres y desesperados pueden hacer una gran diferencia en las elecciones.

Muy a pesar mío sé que esta entrada tendrá el mismo efecto que tiene un grito debajo del agua y que muy pocas personas oirán el clamor que las ocho millones de personas que en este mismo instante tienen hambre en mi país.

PD: como conclusión se puede afirmar que en estadística no todo vale, no todo vale, no todo vale y que las muestras son sagradas, las muestras son sagradas, las muestras son sagradas.
