---
title: "Cosas que debo hacer este semestre..."
author: "Andrés Gutiérrez"
date: "2010-02-14"
categories:
  - "Modeling"
  - "Bayesian Statistics"
---

Recibo ideas...

1. Publicar (alguien tiene un mejor nombre?, todavía no me convenzo de ese título... este libro es pura estadística matemática aplicada a las ciencias sociales... modelos univariados y multivariados, ejemplos en R y datos reales, 350 pags!!!!)

2. Empezar my thesis PhDs (Modelamiento Bayesiano para datos longitudinales en media y varianza, mi tutor me dice que debo entregar en año y medio... ojalá, Dios me ayude!!!)

3. Terminar el libro de Bayesiano (En principio se llama Introducción a los modelos Bayesianos... ¿un mejor nombre?... ya terminé toda la parte teórica, pero falta que los coautores me ayuden con los ejemplos en R... Modelos univariados, multivariados, regresión, modelos lineales generalizados, modelos jerárquicos, series de tiempo, muestreo y sobrevida.)

4. Darle forma a las notas de Análisis de Sobrevida (Esta será una linda aventura... todo empezó con el curso de doctorado y ahora ya tenemos unas notas que carecen de estructura, pero que muy seguramente saldrán a la vida en un libro introductorio de esta linda materia.)

5. Patinar con mis amigos!!! skating with my hommies.
