---
title: "¡Me tomo un tinto y tumbo el muestreo!"
author: "Andrés Gutiérrez"
date: "2011-04-16"
categories:
  - "Estadística"
---

El título de este *post* refleja literalmente las palabras de algunos obstinados colegas que, además de arribistas, muestran su ignorancia tratando de enmarcarlo todo dentro de modelos de probabilidad, despreciando la teoría de la aleatorización. Está bien que no les guste el muestreo, pero una cosa es la antipatía por una materia y otra es llegar a tal punto de negar la realidad.

Definitivamente se debe tener muy poco sentido común para afirmar que al tomarse un tinto, es posible invalidar una teoría con décadas de existencia, que ha sido formulada por las mentes más brillantes de la estadística. A lo que me refiero es que existe una actitud incorrecta de parte de un pequeño cúmulo de profesionales, que desestiman el muestreo.

Quiero traer a colación las palabras de uno de los estadísticos más importantes del mundo, Andrew Gelman. Este tipo adora los modelos, es un bayesiano de ultra-derecha, ha escrito muchos libros y atículos en temas de modelos y fíjense en lo que dice:

>... el muestreo es más que una metáfora, es crucial en muchos aspectos de la estadística. Esto es evidente en los estudios de opinión pública y salud, donde los análisis se basan en muestras aleatorias, y en las estadísticas del medio ambiente, donde variables continuas de naturaleza física se estudian a partir de muestras del espacio-tiempo. Pero, incluso en las zonas donde el muestreo es menos evidente, puede ser importante. Considere la posibilidad de experimentos médicos, donde el objetivo siempre es la inferencia de la población en general, no sólo para los pacientes en el estudio. Del mismo modo, el objetivo de los neurocientíficos es conocer los aspectos generales de los cerebros de humanos y animales, no sólo para estudiar las criaturas en particular de las que se dispone de datos. En última instancia, la muestra es sólo otra palabra para subconjunto, y en ambas inferencia bayesiana y clásica, la generalización adecuada de la muestra a la población depende de un modelo para la toma de muestras o el proceso de selección. No tengo ningún problema con el uso del muestreo como marco para la inferencia, y yo creo que esto funcionará aún mejor si se hace hincapié en la generalización a partir de muestras reales de las poblaciones reales - no sólo construcciones matemáticas - que son esenciales para gran parte de nuestras inferencias aplicadas.
