---
title: "Programación del Workshop en Estadística Bayesiana (Bogotá - Colombia)"
author: "Andrés Gutiérrez"
date: "2011-01-19"
categories:
  - "Community and Events"
  - "Bayesian Statistics"
---

La International Association of Survey Statisticians, junto con la Facultad de Estadística de la Universidad Santo Tomás presentan uno de los eventos más esperados por la comunidad estadística colombiana, el International Workshop on Applied Statistics en su segunda versión. Este evento bienal que tendrá lugar en la sede principal de la Universidad entre el 3 y el 5 de febrero de 2011, abordará como tema principal la **Estadística Bayesiana y sus Aplicaciones.**

El evento contará con la presencia de reconocidos profesionales de la estadística a nivel internacional, los cuales estarán acompañados de destacados estadísticos nacionales, todos ellos expertos en Estadística Bayesiana, a saber:

- Raquel Prado - University of California

- Mike Daniels - University of Florida

- Eduardo Gutiérrez - Universidad Nacional Autónoma de México

- Andrés Gutiérrez - Universidad Santo Tomás

- Fabio Humberto Nieto - Universidad Nacional de Colombia (Sede Bogotá)

- Jairo Fúquene - University of Puerto Rico

- Victor López - Universidad Nacional de Colombia (Sede Medellín)

El workshop se caracteriza porque todos los invitados internacionales, además de conferencias, desarrollarán cursillos intensivos (10 horas) sobre temas de punta en la investigación de la estadística aplicada, con lo cual los participantes serán instruidos personalmente por este reconocido equipo estadístico. Los cursos ofrecidos, son:

- Introducción a la Estadística Bayesiana

- Modelos e Inferencia Bayesiana en Series Temporales

- Bayesian Modeling of Missing Data in Longitudinal Studies

La información sobre el programa del seminario, el valor de la inversión, así como el procedimiento de inscripciones, puede encontrarse en la página web: http://www.usta.edu.co/

Los contactos para ampliar la información son:

- [estadística@usantotomas.edu.co](mailto:estadística@usantotomas.edu.co)

- [heivarrodriguez@usantotomas.edu.co](mailto:heivarrodriguez@usantotomas.edu.co)

- Teléfonos: 5878869, 5878797 ext: 1422 – 1450

**PROGRAMA**

CURSILLO N°1:

Raquel Prado (University of California): Modelos e Inferencia Bayesiana en Series Temporales

CURSILLO N°2:

Mike Daniels (University of Florida): Bayesian modeling of missing data in longitudinal studies

CURSILLO N°3:

Eduardo Gutiérrez (Universidad Nacional Autónoma de México): Introducción a la Estadística Bayesiana

**JUEVES 03 DE FEBRERO DE 2011**

- 8:00 – 11:00 am

Cursillos – Día 1 (Salas asignadas)

- 6:30 – 7:00 pm

Instalación del Evento (Aula Magna Fray Domingo de las Casas)

- 7:00 – 8:00 pm

Conferencia 1: Time Series Analysis using TAR Models – Fabio Humberto Nieto. Universidad Nacional de Colombia – Sede Bogotá.

- 8:00 – 8:30 pm Acto Social

**VIERNES 04 DE FEBRERO DE 2011**

- 8:00 – 11:00 am

Cursillos – Día 2 (Salas asignadas)

- 3:00 – 4:00 pm

Ciclo de Comunicaciones

- 4:00 – 5:00 pm

Conferencia 2: "A Case for Robust Bayesian Priors with Applications to Clinical Trials"- Jairo Fúquene (University of Puerto Rico)

- 5:00 – 6:00 pm

Conferencia 3: "Modelos doblemente generalizados utilizando técnicas bayesianas"- Andrés Gutiérrez (Universidad Santo Tomás)

- 6:00 – 6:30 pm

Coffee Break.

- 6:30 – 7:30 pm

Conferencia 4: "Construcción de distribuciones a partir de variables latentes" – Eduardo Gutiérrez. Universidad Nacional Autónoma de México (UNAM)

- 7:30 – 8:30 pm

Conferencia 5: "Modelos temporales para detectar fatiga a partir de señales de electroencefalografías" – Raquel Prado. University of California.

**SÁBADO 05 DE FEBRERO DE 2011**

- 8:00 – 11:00 am

Cursillos – Día 3 (Salas asignadas)

- 2:00 – 2:45 pm

Conferencia 6: "Teoría de diseños óptimos Bajo una perspectiva Bayesiana" – Víctor López. Universidad de Nacional de Colombia- Sede Medellín

- 2:45 – 3:30 pm

Conferencia 7: "A Bayesian Shrinkage Model for Incomplete Longitudinal Binary Data with Application to the Breast Cancer Prevention Trial" – Mike Daniels. University of Florida

- 3:30 – 4:30 pm

Panel de Clausura – ¿Llegó la era de la estadística bayesiana?

Raquel Prado (University of California), Mike Daniels (University of Florida) & Eduardo Gutiérrez (Universidad Nacional Autónoma de México).

Moderador: Andrés Gutiérrez – Universidad Santo Tomás

- 4:30 – 5:00 pm

Evento Social - Cierre
