---
title: "¿Cuál será mi próxima parada?"
author: "Andrés Gutiérrez"
date: "2011-10-18"
categories:
  - "Colombia"
  - "Estadística"
---

Acabo de hacer una lectura rápida del [último número de AMSTAT NEWS](https://web.archive.org/web/20231101232248/http://magazine.amstat.org/wp-content/uploads/2011an/September%202011.pdf) y hay un artículo muy interesante en donde varios estadísticos responden un chismografo (que en Colombia es una suerte de preguntas con el objetivo único de curiosear la vida de los demás). En este mismo instante estoy leyendo las respuestas de algunos personajes y lo que voy a hacer, aunque puede parecer impersonal, es constestar esas preguntas con el ánimo de hacer un balance de mi corta carrera profesional. Además, le insto a que se anime y responda también este chismografo.

¿Qué o quién lo inspiró a estudiar estadística?

Lamentablemente no fue un alguien que me inspiró a estudiar estadística. Esto fue un gran accidente, que de planeado no tuvo nada (me voy a permitir afirmar que fue una Diosalidad: una casualidad guiada por Dios). Como para muchas personas en Colombia, el único lugar dónde es posible tener una educación buena y no tan costosa es la universidad pública. Yo había presentado un examen de admisión a Ingeniería Industrial y afortunadamente no pasé. Luego, pensé: La respuesta era fácil, yo era bueno para los números. Así que, después de meditarlo un poco y teniendo en cuenta que alguien de mi colegio había sido admitido a la carrera de estadística en la Universidad Nacional, pues me aventuré, sin tener idea que esa decisión cambiaría mi vida por siempre.

Aunque, una mejor pregunta sería ¿quién lo inspiró a estudiar? La respuesta es muy sencilla, mi abuela Lola. Es como mi mamá, ella me crió porque mi mamá biológica falleció cuando yo tenía dos años. Ella todos los días ponía en mí el deseo de vivir y de no dejarme de las circunstancias.

¿Cuál es la parte más excitante de su trabajo?

Por un lado mi pasión siempre ha sido enseñar. Se me da y punto. Me gusta interactuar con las personas y qué mejor manera de hacerlo que siendo profesor. Ésta es una tarea muy difícil, más en una universidad privada en donde la educación es un servició más y en donde los evaluadores de la labor docente son los alumnos. Así que, en mi trabajo en la Universidad Santo Tomás, la parte más excitante es ser mejor docente de lo que fueron mis docentes. Y vaya docentes que he tenido. Algunos muy buenos, otros que podrían mejorar algunas cosas. La Universidad Nacional, al igual que cualquier otra universidad en el mundo, tiene una gama de excelentes maestros, no todos ellos excelentes personas. Así que cada clase es una única oportunidad de ser mejor profesor que mis mejores profesores y también es una oportunidad de no cometer los errores que mis profesores cometieron conmigo. ¿Por qué mis mejores profesores fueron mis mejores profesores? En realidad, no lo fueron por su gran conocimiento. Lo fueron porque me impregnaron algo de su particular forma de enfrentar la vida. ¿Por qué mis peores profesores fueron mis peores profesores? En realidad, no lo fueron por su escaso conocimiento. Lo fueron por su triste forma de enfrentar la vida. A diferencia de algunas otras profesiones, cuando uno es profesor, la materia prima son personas. Lamentablemente yo tuve algunos profesores y profesoras que no trabajaban (o trabajan) con personas sino con cerebros. Al igual que yo, mis estudiantes tienen dificultades no solamente con el muestreo, sino con la vida. Por eso me gusta la USTA, cuya impronta institucional es criar personas más allá de buenos profesionales. Si usted es profesor (tal vez si fue mi profesor) le doy un pedazo de consejo: Y es que yo pienso que los profesores malos son malos porque ven el triste reflejo de ellos en la cara de sus alumnos.

Por otro lado, trabajo como investigador en la USTA. Este oficio no se compara un ápice al de profesor. Así que no lo voy a comentar. Por otro lado soy consultor y lo excitante es que me pagan por hacer lo que yo haría gratis. Por último, soy auditor y lo excitante es que estoy creando cultura estadística entre estadísticos en las dependencias públicas. Es cierto, así como lo lee, cultura estadística dentro del gremio. Eso es muy excitante porque forja mi carácter y además da claridad a los procesos estadísticos en el sector gubernamental.

Nombre algunas habilidades necesarias para realizar su trabajo

Por encima de todo la comunicación oral y escrita.

Nombre una habilidad que le gustaría aprender para hacer un mejor trabajo

Me gustaría aprender a tener más disciplina. Me gustaría a utilizar mejor el idioma. Como escritor de libros esto es fundamental.

¿Tuvo un mentor? Si fue así, ¿cuál fue su mejor consejo?

Sin duda. Mi tío Oscar que siempre vio en mí a un ganador. Y aún hoy sigue viendo en mí a un ganador. Mi familia toda me apoyo y les digo que los amo (a los miembros de mi familia). En la cuestión académica mi gran mentor ausente es Leonardo Bautista. Desde el principio nos la llevamos muy bien. Murió muy rápido pero dejó en mí algo de su pasión por el muestreo. Jorge Ortiz me dio un consejo que no tengo cómo agradecer y me auguró mejores éxitos en la USTA que en otros lados. Humberto Mayorga me dijo que yo tenía el factor X del muestreo. Leonardo Trujillo y Pedro Silva han tomado un gran riesgo conmigo al aceptarme como alumno de tesis de doctorado. Leonardo Trujillo me respondía muy amablemente todos los correos que yo le enviaba cuando él estaba en UK. Pero sobre todo mi esposa ha sido mi más fiel apoyo. Como sabe de todo entonces ella me explica las muchas cosas que no entiendo.

Nombre dos blogs o libros que recomendaría a otros

Me gusta leer a John Cook en su blog The Endeavour y me gusta leer Rblogs porque a veces se escriben post de hágalo usted mismo con R, sobre cosas que ni idea en estadística. Los libros infaltables son Statistical Design for Researches de Leslie Kish y uno muy bonito que se llama The Lady Tasting Tea que relata la historia de la estadística de forma muy amena y a manera de chisme.

¿Qué aviso les daría a los jóvenes que están empezando sus carreras?

Que si no les gusta ser profesor que no se metan en eso. Es un buen consejo porque muchos estadísticos en Colombia terminan dictando cátedras en universidades y si la pasión de dictar clase no está en ellos pueden frustarse ellos e imponer una imagen aburrida de la estadística entre sus alumnos.

¿Qué le gusta hacer en su tiempo libre?

Patinar. Gastar tiempo con mis amigos. Estar con Lucas (mi hijo) y dormir junto a él.
