---
title: "Blog stats"
author: "Andrés Gutiérrez"
date: "2011-01-02"
categories:
  - "Modeling"
  - "Elections"
---

Los duendes de estadísticas de WordPress.com han analizado el desempeño de este blog en 2010 y te presentan un resumen de alto nivel de la salud de tu blog:

El *Blog-Health-o-Meter™* indica: Wow.

## Números crujientes

El Museo del Louvre tiene 8,5 millones de visitantes al año. Este blog fue visto cerca de **96,000** veces en 2010. Si el blog fuera una exposición en el Louvre, tomaría 4 días para verla.

En 2010, publicaste **70** entradas nueva, haciendo crecer el arquivo para 213 entradas. Subiste **81** imágenes, ocupando un total de 7mb. Eso son alrededor de 2 imágenes por semana.

The busiest day of the year was 13 de abril with **713** views. The most popular post that day was [El gremio se pronuncia acerca de las recientes encuestas electorales de las elecciones en Colombia](2010-04-12-el-gremio-se-pronuncia-acerca-de-las-recientes-encuestas-electorales-de-las-elecciones-en-colombia.qmd).

## ¿De dónde vienen?

Los sitios de referencia más populares en 2010 fueran **search.conduit.com**, **facebook.com**, **usta.edu.co**, **es.wordpress.com** y **alexjzc.wordpress.com**.

Algunos visitantes buscan tu blog, sobre todo por **curtosis**, **apuntes de estadística blog**, **valor p**, **p valor** y **modelos estadísticos**.

## Lugares de interés en 2010

Estas son las entradas y páginas con más visitas en 2010.

1

[El gremio se pronuncia acerca de las recientes encuestas electorales de las elecciones en Colombia](2010-04-12-el-gremio-se-pronuncia-acerca-de-las-recientes-encuestas-electorales-de-las-elecciones-en-colombia.qmd)

abril, 2010

14 comentários

2

[La curtosis, una medida ampliamente conocida pero malinterpretada….](2010-02-12-la-curtosis-una-medida-ampliamente-conocida-pero-malinterpretada.qmd)

febrero, 2010

1 comentario

3

[Modelos estadísticos](https://web.archive.org/web/20101101165821/http://predictive.wordpress.com/2008/06/22/modelos-estadisticos-2/)

junio, 2008

4 comentários

4

[Seis simples técnicas para la presentación de datos](https://web.archive.org/web/20101101094609/http://predictive.wordpress.com/2008/05/03/seis-simples-tecnicas-para-la-presentacion-de-datos/)

mayo, 2008

11 comentários

5

[Estrategias de muestreo](../books.qmd)

noviembre, 2009
