---
title: "TEAM"
author: "Andrés Gutiérrez"
date: "2011-09-05"
categories:
  - "Probability"
  - "R"
---

[Contenido (clic acá)](https://web.archive.org/web/20120915092226/http://www.gutierrezandres.com/wp-content/uploads/2010/12/Contenido.pdf)  Este libro conduce al lector por el apasionante viaje de la práctica estadística la cual ciertamente debe estar fundamentada en una rigurosidad teórica bien definida. El análisis de datos no empieza con un modelo de probabilidad. El análisis de datos empieza con los mismos datos; en la vida práctica el profesional debe cuestionarse acerca de la naturaleza de los datos: ¿qué rango tienen? ¿cuál es la fuente de los datos? ¿cómo se obtuvieron? En la vida real no sucede que el profesional sea contratado para analizar una muestra aleatoria que proviene de una distribución continua o discreta. No, en la vida real, el profesional decide qué tipo de distribución se ajusta mejor y sobre ello utiliza las mejores herramientas para inferir y convertir su análisis en información valiosa. Este texto tiene ese enfoque y la particularidad de poner en contexto al lector y mediante ejemplos prácticos afianzar la teoría e introducir al lector en el interesante camino de la programación estadística.  **[Obtenga una visualización del texto acá](http://books.google.es/books?printsec=frontcover&id=62u0U46_QLsC#v=onepage&q&f=false)(Google books)**  **[Compre el libro acá (Librería de la U)](http://www.lalibreriadelau.com/libros-de-estadistica-ca39_79/libro-teoria-estadistica-aplicaciones-y-metodos-p69707)**  **[Compre el libro acá (Lemoine editores)](http://www.lemoineeditores.com/catalog/product_info.php?products_id=2376)**  **[Compre el libro acá (Librería Nacional)](http://www.librerianacional.com/es/index.php?option=com_catalogo&task=mostrarDetalleProducto&idProducto=273633)**    **Puntos de venta: **  **Librería de la Universidad Santo Tomás: Carrera 13 No 51 (Bogotá)**
