---
title: "Ideas al azar (Julio)"
author: "Andrés Gutiérrez"
date: "2011-07-23"
categories:
  - "Teaching"
  - "Sampling"
---

Hoy, mientras esperaba por unas copias en la Universidad Nacional de Colombia, me encontré de pronto ojeando libros en la librería de la universidad. Sin darme cuenta, estaba leyendo los prólogos de algunos libros escritos por autores de la universidad. En uno de ellos la autora afirmaba que el libro había nacido debido a la necesidad de los estudiantes de seguir un texto así y bla, bla, bla…

Con respecto a lo anterior me surgen dos ideas al azar… La primera es en forma de exclamación. Lo primero que pensé fue. En realidad no tengo ni idea acerca de las bondades del libro, puesto que ni siquiera es de estadística o matemáticas. Sin embargo, bueno o no, es realmente altruista que una doctora entre en la ardua tarea de escribir un libro de 500 páginas porque los estudiantes lo necesitan. De hecho, me parece una motivación influida de delirios mesiánicos y fuera de tono con la realidad de las nuevas tecnologías. Me explico, es mesiánica porque ella cree que les está haciendo un favor a los estudiantes, que no existe un libro mejor sobre el tema, que no existirá un mejor texto. Realmente, me parece que los estudiantes le están haciendo un favor a ella. Por supuesto, le están comprando el libro, le corrigen los posibles errores, le brindan alegría, entre otras. No creo ni siquiera que el estudiante esté enterado de que existe un gran vacío en la literatura y que sólo la profesora pueda llenar ese vacío.

El segundo pensamiento que tuve fue ¿Por qué no decir simplemente que la motivación es que a ella le gusta esa área de las ciencias, además le gusta enseñar, y por consiguiente, la haría muy feliz enseñar con su libro? No creo que haya nada de malo en eso. De hecho, con esa motivación estoy seguro que se escriben los mejores textos. Es así de sencillo, en materia de libros (pilas, no estoy hablando de investigación formativa) de texto, ya todo está escrito. El cálculo que hoy dictan en las universidades ya se inventó hace muchos siglos, miles de libros han sido escritos. En mi biblioteca, cuento con más de treinta libros de muestreo, incluyendo el mío. A decir la verdad, podría escoger al azar cualquiera y aun así podría dictar un muy buen curso de muestreo. No es que mi libro sea el mejor libro de muestreo, es simplemente que me gusta ese tema, me apasiona y como también me gusta mucho enseñar, pues enseño con el libro que yo escribí. Es por eso que no dicto el curso de muestreo con otro texto, sino con el mío, aun sabiendo que los otros pueden ser considerados como mejores. De hecho, la parte humana se alimenta cuando el alumno se da cuenta que el profesor sí comete errores, que el profesor es de carne y hueso, y eso aumenta el sentimiento de aprecio y, por qué no decirlo la calidad de las exposiciones.

I. D. me preguntó un día ¿para qué escribir un texto de inferencia estadística? Él argumentaba que habían otros textos, seguramente mucho mejores. Pues bien, hoy descubrí que en realidad, ese texto lo escribimos con ninguna motivación científica (eso no quiere decir que no sea un trabajo serio). De hecho, otros libros exponen lo mismo, pero en nuestro proceso de aprendizaje, quisimos plasmar nuestro punto de vista, que es muy diferente al de los otros textos. Quisimos entrar en ese bello camino de mostrarle al estudiante nuestra pasión por la estadística. Realmente lo escribimos con muchas motivaciones personales, pensando en todo tiempo en beneficiarnos de los comentarios de los estudiantes y colegas. Las añadiduras que trae, son simplemente producto de esa pasión y son la mejor versión de nosotros.

Este blog es fiel a esa filosofía, lo escribo porque sí, porque me apasiona, porque me gusta estar en contacto con mis valiosos lectores. No lo escribo pensando en que hay un vacío que llenar, no lo escribo por hacerle un favor a nadie. No creo que mis entradas sean la salvación del gremio. Simplemente lo hago por satisfacerme a mí mismo. Esa es la alegría de mi vida, satisfacerme con las pequeñas cosas.
