---
title: "I Concurso de Análisis de Datos con R"
author: "Andrés Gutiérrez"
date: "2011-07-17"
categories:
  - "Estadística"
  - "R"
---

Como una actividad complementaria a las III Jornadas de Usuarios de R, a celebrar en Madrid el 17 y 18 de noviembre de 2011. Nestoria y Lokku Labs buscan mejorar la comprensión y la información que se puede obtener de sus bases de datos y pretenden contactar con brillantes estadísticos que aporten un valor añadido a los datos disponibles sobre precios de viviendas. Los organizadores, por su parte, desean mostrar las aplicaciones del R en el ámbito empresarial y demostrar el beneficio que pueden obtener las empresas analizando sus bases de datos con R.

##### 1.500€ en premios... y más

El ganador obtendrá un cheque por importe de 1.000 euros y el segundo otro por 500 euros, además del certificado correspondiente en ambos casos. El concurso se podrá declarar desierto si el jurado considera una escasa calidad o interés en los trabajos presentados. Asimismo, uno o más de los participantes podrán ser invitados a una entrevista de trabajo en Londres, Reino Unido, para una colaboración inicial de tres meses en la sede central de Nestoria. Todos los participantes recibirán un certificado de su participación en el concurso con el título de su trabajo.

La página de las bases de la competición es: http://www.usar.org.es/concurso_es.php
