---
title: "Vamos a participar... \"chévere si un colombiano se lo gana\""
author: "Andrés Gutiérrez"
date: "2011-01-28"
categories:
  - "Estadística"
---

En la actualidad existen muchos eventos de caracter internacional que reunen periódicamente a la comunidad estadística internacional. No, espere... No le voy a hacer propaganda al [Second Workshop on Applied Statistics](2011-01-19-programacion-del-workshop-en-estadistica-bayesiana-bogota-colombia.qmd) organizado por la [Facultad de Estadística](http://www.usta.edu.co/index.php?option=com_content&view=article&id=66) de la Universidad Santo Tomás, y patrocinado por la [International Association of Survey Statisticians](https://web.archive.org/web/20190607032949/http://isi.cbs.nl/iass/allUK.htm), que tendrá lugar desde el 3 de febrero en Bogotá. No, de ninguna manera, esta vez quisiera divulgar por este medio las posibilidades existes para ser partícipes de los dos más importantes encuentros internacionales, según mi humilde parecer, en materia de estadística. Se trata de la 58 versión del ISI World Statistics Congress, que se llevará a cabo en Dublin (Irlanda), y de las Joint Statistical Meetings, que tendrán lugar en Miami (EE. UU.).

Para el primer evento mencionado, M. S. me envió este vínculo por facebook, en el cual se puede encontrar información sobre un premio que el ISI podría otorgar a un estadístico latinoamericano. Se trata del [JAN TINBERGEN AWARD](https://web.archive.org/web/20210411022928/http://isi.cbs.nl/tinbergen/2011papers.htm), que premia a los ganadores con € 2269 y la presentación de su artículo en Dublin, con todos los gastos pagos. En este concurso, sólo los paticipantes de los países en vía de desarrollo pueden partícipar, en palabras de Maurucio, chévere si un colombiano se lo gana.

En el segundo evento hay varias oportunidades de participar. La ASA tiene diferentes secciones que patrocinan a estudiantes que quieran presentar sus trabajos en las meetings. Además, ya hemos tenido ganadores colombianos ([parce](2008-09-17-felicitaciones-parce.qmd)). Ojalá nos veamos en los miamis porque yo pienso participar en [este concurso](http://www.amstat.org/sections/sbss/awards/travel/index.html) y [someter algo acá](http://www.amstat.org/meetings/jsm/2011/index.cfm?fuseaction=abstracts) también.

Ohhh, se me olvidaba recordarles que el ganador del Student Travel Award 2008 de la sección bayesiana va a participar en el [Second Workshop on Applied Statistics](2011-01-19-programacion-del-workshop-en-estadistica-bayesiana-bogota-colombia.qmd) organizado por la [Facultad de Estadística](http://www.usta.edu.co/index.php?option=com_content&view=article&id=66) de la Universidad Santo Tomás, y patrocinado por la [International Association of Survey Statisticians](https://web.archive.org/web/20190607032949/http://isi.cbs.nl/iass/allUK.htm), que tendrá lugar desde el 3 de febrero en Bogotá. ¿[y usted ya se inscribió](http://eventos.usta.edu.co/inscripcion_web.cfm? EVENTO=16)?
