---
title: "See ya in da beach!!!"
author: "Andrés Gutiérrez"
date: "2011-03-30"
categories:
  - "Estadística"
---

Bueno pues... este año la cita fue en Bogotá con el Workshop Bayesiano... ahora, nos vamos para las meetings 2011 en Miami... Ya se de 3 colombianos que van a ir... déjenme saber quién más piensa asistir para atenderlos como es debido allá en los miamis... Nos vemos allá parce!!!

We are pleased to inform you that your presentation (Abstract #

**301744**

,

**Hierarchical Design-Based Estimation in Stratified Multipurpose Surveys**

) has been accepted and is scheduled in Session #

**413**

on

**Tuesday, 8/2/2011**

beginning at

**2:00 PM**

during the Joint Statistical Meetings in Miami Beach, Florida, July 30–August 4, 2011.

We are pleased to inform you that your presentation (Abstract #

**301743**

,

**Student Paper Competitions**

) has been accepted and is scheduled in Session #

**459**

on

**Wednesday, 8/3/2011**

beginning at

**8:30 AM**

during the Joint Statistical Meetings in Miami Beach, Florida, July 30–August 4, 2011.
