---
title: "El creador del SPAD en Colombia…. Una autoridad mundial en Data Mining visita la Santoto"
author: "Andrés Gutiérrez"
date: "2012-03-27"
categories:
  - "Modeling"
  - "Teaching"
---

En el marco de la celebración de los cinco años de la creación de la Facultad de Estadística de la Universidad Santo Tomás en Bogotá, y gracias al apoyo del ICETEX y de la Embajada de Francia en Colombia, se ha concretado la visita del doctor Ludovic Lebart. El Dr. Lebart es autoridad a nivel mundial en el tema de minería de textos. Su investigación se centra en los Métodos de Análisis Estadístico de datos cualitativos y textuales. Los datos provenientes de encuestas socioeconómicas constituyen su principal ámbito de aplicación. Es autor de más de 14 libros especializados en el área de Text Mining y ha participado como coautor en decenas de publicaciones relacionadas.

Ludovic Lebart es doctor en estadística matemática, profesor de Estadística Matemática en la Universitad de Neuchatel (Suiza) y desde 1990 es presidente del Comité Científico del CESP (Centre d' Etude des Supports de Publicité: [www.cesp.org](http://www.cesp.org)). Además fue el creador del software SPAD, hoy comercializado por la empresa CISIA y del DTM, que sigue siendo de libre distribución.

Lebart dictará un curso de seis horas en análisis de datos textuales en la Santoto. Lastimosamente los cupos son muy limitados y, si usted quiere ser partícipe de este entrenamiento personalizado por una de las autoridades mundiales en el área, deberá estar muy atento a la publicidad y la información que nos brinde la Facultad de Estadística. Las inscripciones y publicidad en general se van a dar desde el 10 de abril. La buena noticia es que Lebart también dictará algunas conferencias de entrada libre en el marco de la celebración (también habrá conversatorios y otras conferencias de invitados nacionales). Si usted es estadístico de la Nacho, como yo, o de cualquier otra institución (del Valle, Nacho Medellín, Cordoba) no puede perderse esta celebración que es motivo de orgullo para el desarrollo estadístico en el país. ¡Celebremos juntos, celebremos como gremio!
