---
title: "Para profesores en la región"
author: "Andrés Gutiérrez"
date: "2012-03-05"
categories:
  - "Estadística"
---

#### UNILA abre processo seletivo com 18 vagas para diversas áreas do conhecimento

http://www.unila.edu.br/noticia/professores-visitantes

A Universidade Federal da Integração Latino-Americana (UNILA) abre as inscrições do Processo Seletivo Simplificado para professores visitantes. São 18 vagas, sendo uma para portadores de necessidades especiais, nas seguintes áreas do conhecimento: Arquitetura e Urbanismo (2), Biologia (1), Cinema (1), Engenharia (3), Estatística (1), Física (1), História (1), Letras/Artes (5), Música (1), e Saúde Coletiva (2).

Os professores serão contratados em regime de prestação de serviços no Ensino, na Pesquisa e na Extensão, durante um ano, podendo ser prorrogado pelo mesmo período para os brasileiros e por 36 meses para os estrangeiros.

### Inscrições

As inscrições ficarão abertas até o día

**9 de março**

, pelo site da UNILA, através do preenchimento do

[Formulário de Inscrição](https://web.archive.org/web/20121211024603/http://200.134.33.22/)

[.](https://web.archive.org/web/20121211024603/http://200.134.33.22/)

Além disso, os candidatos devem enviar Currículo Lattes e Proposta de Atuação Acadêmica na UNILA para o e-mail

**[segepe@unila.edu.br](mailto:segepe@unila.edu.br)**

. No caso dos estrangeiros, ao invés do Currículo Lattes, pode ser enviado um currículo detalhado.

A remuneração para professores doutores será de R $7.333,67, e para mestres, R $ 4.651,49.

### Mais informações

Em caso de dúvidas ou para obter mais informações, entrar em contato pelos telefones

**[+55 (45) 3576-7337](tel: %2B55%20%2845%29%203576-7337)**

e

**3576-7320**

, ou pelo e-mail da Secretaria de Gestão de Pessoas:

**[segepe@unila.edu.br](mailto:segepe@unila.edu.br)**

.
