---
title: "Llamado a árbitros"
author: "Andrés Gutiérrez"
date: "2012-09-04"
categories:
  - "Colombia"
  - "Estadística"
  - "R"
---

La [Revista Comunicaciones en Estadística](http://comunicacionesenestadistica.usta.edu.co) reconoce el valor y la importancia de los árbitros en el proceso de editorial general. En este momento, queremos lograr las cualificaciones apropiadas para lograr nuestra inclusión en bases de datos nacionales e internacionales de revistas científicas. Para ello, necesitamos la asistencia de evaluadores externos que ayuden al comité editorial en la selección de artículos adecuados para la publicación en la revista.

En un esfuerzo por facilitar la selección de árbitros apropiados para la revista, le pedimos que se tome un momento para completar [este formulario](http://revistas.usta.edu.co/index.php/estadistica/user/register) para nuestros archivos. Por favor, asegúrese de hacer clic en la casilla de verificación de revisión.

Gracias de antemano.

__________________________________________________________________________

##### Call For Reviewers

Our journal "Comunicaciones en Estadística" recognizes the value and importance of the peer reviewer in the overall publication process. Right now, we want to achieve appropriate qualifications for our inclusion in national and international scientific journal databases. For this, we need the assistance of external reviewers to help the Editorial Review Board select suitable papers for publication.

In an effort to facilitate the selection of appropriate peer reviewers for the journal, we ask you to take a moment to complete [this form](http://revistas.usta.edu.co/index.php/estadistica/user/register) for our files. Please, be sure to click in the review check box.

Thanks in advance.
