---
title: "Mi revisión del libro de Efron en el Journal of Official Statistics"
author: "Andrés Gutiérrez"
date: "2012-07-12"
categories:
  - "Publications"
  - "Inference"
---

Hace algunos meses, Jaki McCarthy me invitó a ser parte del número 2, Volumen 28 del Journal of Official Statistics para que hiciera un pequeño ensayo del libro *Large-Scale Inference: Empirical Bayes Methods for Estimation, Testing, and Prediction*de Bradley Efron. Pues bien, después de leer el libro y hacer el *review*, [aquí está el resultado](http://gutierrezandres.files.wordpress.com/2012/07/jos-review-gutic3a9rrez.pdf).

Realmente, Efron es una de las mentes más brillantes en la historia de la estadística y con este libro expone un tema que sin pretender ir más lejos, se está convirtiendo en una herramienta fundamental en experimentos clínicos y en la estadística de la era de la información masiva, la inferencia a gran escala. De hecho, el libro más parece ser una monografía de sus tantos artículos publicados sobre este tema.

Realmente lo recomiendo, y auguro que no tardará en convertirse en el texto de referencia en términos de pruebas de hipótesis y análisis estadísticos cuando se manejan grandes masas de datos. Por otra parte, no tardo en evidenciar que la bioestadística se convertirá en una disciplina reconocida y utilizada en muchos ámbitos cientifico y de investigación en América Latina y España. Desde ya, si usted está interesado en este bonito tema, tome mi consejo: baje las notas de clase de Efron (que son gratis y las puede [conseguir acá](http://www-stat.stanford.edu/~omkar/329/tanotes.pdf)) y aventúrese en estas metodologías. Si le gustan las notas, no dude en comprar el libro.

Por lo pronto, como ejemplo, yo no dudaré en descartar las metodologías clásicas para comparar medias, entre otras. Realmente, es sorprendente darse cuenta de que, cuando se trata con muchos datos, la metodología clásica de los p-valores no suele ser la mejor. Así que, desde ya estoy listo para mi próximo análisis de microarreglos.
