---
title: "Contraejemplos de consistencia e insesgamiento asintótico"
author: "Andrés Gutiérrez"
date: "2012-03-22"
categories:
  - "Estadística"
---

Alguna vez leí un libro de humor del periodista Daniel Samper Pizano y quedé encantado con esta frase:

> "Yo, personalmente, admiro más el plasma que la sangre"

Y es que, al escoger un estimador, pueden primar gustos por el plasma más que por la sangre. A lo que voy es que en teoría estadística, es bien sabido que el enfoque clásico, e incluso bayesiano, está enfocado en hallar un estimador que, en primera medida sea insesgado. Ya lo decía el viejo Hájek en alguna de sus obras que afirmaba que:

> "… si el sesgo del estimador no es despreciable, entonces el estimador es inútil sin importar qué otras propiedades estadísticas pudiese tener"

Tal vez sea por mi énfasis en el muestreo, pero cuando se trata de estimadores, yo prefiero examinar primero la consistencia y después las otras propiedades estadísticas del estimador. Un ejemplo clásico de muestreo consiste en que, para estimar el promedio de patas de los perros en la tierra, un alienígena procede a utilizar el estimador de Horvitz-Thonmpson, que es insesgado, y que en sus dos posible realizaciones arroja como resultados para una muestra 2 y para otra muestra 6… Sí, 2+6=8, 8/2=4. Efectivamente, el estimador es insesgado pero inútil. Sin embargo, paradójicamente, al utilizar el estimador de Hájek, que es consistente y asintóticamente insesgado, el alienígena encuentra que para sus dos posibles muestras, el estimador siempre es 4. Hoy quiero traer dos ejemplos de lo uno y de lo otro sin entrar en detalles técnicos ni computacionales. Antes de que siga con la lectura, le recomiendo que se empape del tema [leyendo esta entrada relacionada](2009-05-21-del-dicho-al-hecho-consistencia-eficiencia-e-insesgamiento.qmd).

**Un estimador consistente que no es asintóticamente insesgado**

Suponga una muestra aleatoria de variables con media $\mu $ y varianza $\sigma^2$. El siguiente estimador

$ T=\bar{X}+\frac{c}{n^{1/2}}$

es consistente, puesto que, entre otros, a medida que el tamaño de muestra crece:

1. Su esperanza tiende al valor del parámetro $\mu $.

2. Su error cuadrático medio $\frac{\sigma^2+c}{n}$ tiende a cero.

Sin embargo, no es asintóticamente insesgado puesto que la distribución límite de $ n^{1/2}(T-\mu)$ no tiene media nula. Lo anterior puesto que la distirbución límite de

$ n^{1/2}(T-\mu)= n^{1/2}(\bar{X}-\mu)+c $

Es normal con media

*c*

y varianza $\sigma^2$.

**Un estimador asintóticamente insesgado que no es consistente**

Suponga una muestra aleatoria de variables con distribución de Laplace

$ f(x)=\frac{1}{2}\exp{-|x-\theta|}$

Y considere el siguiente estimador insesgado para la media $\theta $

$ T=X_1$

Dado que *T*es insesgado, también es asintóticamente insesgado. Sin embargo, dado que la varianza de*T* es $\Var(T)=2\neq 0$, no es consistente. Por supuesto, lo anterior se verifica rápidamente cuando se nota que

$\Pr(|T-\mu|>\varepsilon)=1-\Pr(-\varepsilon No depende de n, y por lo tanto esta probabilidad no tiende a cero a medida que *n* crece.
