---
title: "My article in ib... Calibración de razones en encuestas complejas"
author: "Andrés Gutiérrez"
date: "2012-12-18"
categories:
  - "Colombia"
  - "Estadística"
---

Los estimadores de calibración se han convertido en una técnica robusta y eficiente en la estimación de totales en encuestas complejas. En este trabajo se considera y aplica un importante resultado que afirma que es posible calibrar con algunos otros parámetros complejos, diferentes a totales auxiliares, como la mediana, la media, la media geométrica o incluso una razón, logrando obtener estimaciones de totales con las mismas características de no tener sesgo y poseer varianza pequeña. Mediante simulaciones de Monte Carlo se aplicó este resultado a poblaciones empíricas, mostrando un buen desempeño. También, se utilizó esta técnica en la Gran Encuesta Integrada de Hogares realizada por el Departamento Administrativo Nacional de Estadística, lo cual permitió concluir acerca de la eficiencia de la técnica.

El artículo completo lo pueden [descargar haciendo clic acá](http://gutierrezandres.files.wordpress.com/2012/12/calibraraz_gut_riv.pdf)... En verdad espero que las personas que trabajan en los Institutos Nacionales de Estadística en América Latina (y por supuesto en Colombia en el DANE) encuentren en este artículo una valiosa herramienta para sus procesos de análisis de encuestas. Se agradecen todo tipo de comentarios al respecto.
