---
title: "Discurso de posesión"
author: "Andrés Gutiérrez"
date: "2013-01-31"
categories:
  - "Estadística"
---

Estas fueron las palabras con las que empecé este periodo de decanatura en la Facultad de Estadística de la Universidad Santo Tomás:

> Permítanme expresar mi agradecimiento a Dios, que me ha dado la visión, fortaleza y seguridad para enfrentar este nuevo reto. Las sagradas escrituras afirman que Dios da la sabiduría y de su boca viene el conocimiento (Pr 2). Así que hoy, al empezar mi decanatura, le pido a Dios que me acompañe, me guíe y me de sabiduría para hacer una buena labor como decano de la Facultad de Estadística. Agradezco también a las directivas de la Universidad Santo Tomás, en cabeza de su rector Padre Carlos Mario Alzate, quienes han depositado su confianza en mí para liderar la Facultad. Deben saber que daré todo de mí para que esta facultad se fortalezca y sea un ejemplo de buena administración y liderazgo, no solo en la comunidad tomasina, sino a nivel nacional e hispanoamericano. Agradezco al decano académico de la división de ciencias económicas y administrativas, padre Marco Antonio Peña, por su compromiso diario con la división. Porque con su gestión, nuestra Facultad se ha consolidado y ha crecido. Una vez más, agradezco al decano saliente el Doctor Sander Rangel, con quien tengo una sincera admiración. Fue el primer decano de la Facultad de Estadística y ha dejado una huella que perdurará en el tiempo. Agradezco a los profesores de la Facultad, de la división y de la Universidad, quienes cada día de este año me han expresado su compromiso y con quienes seguiremos realizando una excelente labor académica, que hasta el momento nos ha posicionado como una Facultad seria y comprometida con la visión de la Universidad. Por último, permítanme expresar mi gratitud a mi esposa Hanwen, quien me ha apoyado sin condiciones y al profesor Yesid Rodríguez, con quien hemos trabajado desde hace cinco años en los procesos de investigación de la Facultad.
>
>
> El visionario H. G. Wells afirmó hace más de un siglo que: "llegará el día en que el pensamiento estadístico será una condición tan necesaria para la convivencia eficiente como la capacidad de leer y escribir." Hoy, en pleno siglo 21, esta es una verdad tangible. El profesional que requiere nuestra sociedad no puede ser ajeno al pensamiento y al análisis estadístico. El padre Peña ha descrito esta característica con una frase que se ha convertido en nuestro lema "el poder de la información para la toma de decisiones." El profesional tomasino, a lo largo de su trayectoria académica se relaciona con la estadística y con el análisis de la información todos los días. Después de su grado, al empezar su carrera como profesional en nuestra sociedad, este hecho se hace más claro. No me estoy refiriendo solamente a los muchachos de nuestra facultad. No. Me estoy refiriendo a todos los profesionales y estudiantes de nuestra universidad. Desde el estudiante de sociología, hasta el estudiante de negocios internacionales y de psicología. En toda nuestra comunidad académica el pensamiento estadístico y la capacidad de análisis de la información debe ser una habilidad que se de por sentado. De esta manera, nuestra Facultad de Estadística deberá convertirse, y ya lo está logrando, en una Facultad que se relacione día a día con todas las otras Facultades y en todas las instancias de nuestra Universidad.
>
>
> Lo anterior, revela mi visión de Facultad. Yo quiero liderar una Facultad transdisciplinar, que se posicione como un acompañante en los procesos académicos y de investigación. Una Facultad cercana a la Universidad, a sus estudiantes, profesores e investigadores. Una Facultad que impacte en los importantes procesos que día a día se deben surtir para que nuestra universidad se siga consolidando a nivel nacional e internacional.
>
>
> En mi visión de Facultad, quiero liderar un proceso de acercamiento frente a las instituciones gubernamentales que día a día piden a gritos un acompañamiento técnico en sus labores de evaluación e investigación de políticas públicas y de servicios. Quiero liderar un Facultad cercana al estado en sus estudios técnicos y cercana a la empresa privada que requiere de nuestros servicios. Una facultad que brinde capacitación técnica a sus profesionales. Y esto implica una ampliación en nuestra visión y un giro hacia la apertura de programas de educación continuada, en modalidad de diplomados y cursos de extensión, en la modalidad de especializaciones y de maestría. Soñamos con una escuela de posgrados que brinde un servicio necesario para la sociedad de hoy en día y que alimente los procesos de investigación de la Universidad.
>
>
> Estos serán los pilares de mi gestión: la creación y consolidación de un centro de consultoría en la Facultad, con miembros de todas las disciplinas, que sea capaz de presentarse a licitaciones públicas y que pueda responder de manera adecuada a las expectativas de la sociedad. Un centro de consultorías cercano a la empresa privada. Y en segundo lugar, la creación de los programas de posgrados, vistos como una respuesta de la universidad a las necesidades de la sociedad Colombiana.
>
>
> No vamos a dejar de lado los procesos que ya están consolidados. Al contrario, vamos a reforzarlos. La labor investigativa de nuestra facultad, también es importante. Con alegría recibo la noticia de que en esto primeros días del año, nos aceptado artículos de investigación en dos revista del Canadá y en una revista de la India. Vamos a posicionar nuestros grupos de investigación que en la última convocatoria de Colciencias han quedado reconocidos y estamos en espera de nuestra categorización en los próximos meses.
>
>
> Tenemos una revista que desde hace cuatro años ha salido regularmente cada seis meses y en la cual hemos tenido la presencia de autores internaciones, así como participación colombiana de otras universidades. Nuestra revista, comunicaciones en estadística se ha consolidado como un espacio de investigación en Colombia, ya es reconocida por Colciencias, y este año esperamos su indexación. Además, nuestra Facultad ha ya tiene su propia colección de textos, con más de cinco libros y los estudiantes reconocen esta bonita gestión y eso hace que el cariño por nuestra universidad crezca en ellos cada día.
>
>
> Este 2013 es el año mundial de la estadística y vamos a tener nuestro tercer evento internacional, que desde hace cuatro años se denomina el "International Workshop on Applied Statistics." Tendremos la participación de cuatro profesores europeos, uno de ellos vino el semestre pasado y quedo impactado con nuestra Universidad. En este 2013 seguiremos haciendo presencia institucional en eventos internacionales y daremos a conocer a nuestra excelente universidad. Estoy seguro que nuestros docentes investigadores cuando participan como conferencistas en eventos nacionales e internacionales siente un fuerte orgullo al representar a nuestra universidad y al decir yo pertenezco a la familia tomasina.
>
>
> Nuestro cuerpo docente es un equipo y más que un equipo, es una familia. No en vano tenemos, en promedio, una de las mejores evaluaciones docentes de nuestra Universidad. Ayer tuve la oportunidad de citar a nuestro cuerpo docente y a lo largo del día me entrevisté con cada uno de ellos. Lo que encontré fue compromiso, amor por la institución y una calidad humana insuperable. Eso hace que nuestra Facultad sea reconocida por su exigencia académica y asegura que nuestros profesionales cumplan una excelente labor en la sociedad pues ellos, los estudiantes son nuestra razón de ser y son el porqué de todos estos procesos en la Facultad.
>
>
> Muchas gracias.
