---
title: "Grupo de usuarios de R en Bogotá (R Users Group in Bogotá)"
author: "Andrés Gutiérrez"
date: "2013-09-24"
categories:
  - "R"
  - "Software"
---

Hace pocos días creamos el [Bogotá R Users Group](http://www.meetup.com/Bogota-R-Users-Group/), como una iniciativa de algunas personas apasionadas por el software estadístico R en Bogotá. El objetivo general del grupo es compartir experiencias de los usuarios del software en Bogotá y servir de base para organizar encuentros y seminarios (presenciales y virtuales) que giren en torno al uso del software (con un sesgo muy marcado hacia la estadística y la minería de datos).

Hay cosas de R que muchos de nosotros no conocemos y que nos vendrían muy bien a la hora de actualizarnos. Por mencionar sólo algunos aspectos: la vinculación de R con HADOOP, para procesamiento en paralelo, cómo escribir artículos en LaTeX con R, cómo hacer gráficos elegantes con GGPLOT2, entre muchas otras cosas.

Entonces la idea es que todos los interesados en este software se unan a este grupo. Abandonemos por un momento las categorías y unámonos todos en este esfuerzo por generar una cultura estadística enfocada en este poderoso y gratuito ambiente computacional. Conmigo comparten la coordinación del grupo el profesor Campo Elías Pardo de la UNAL y el profesor José Fernando Zea de la USTA y si existe alguna otra persona que represente un conglomerado de profesionales o estudiantes es bienvenido en la coordinación.

Tendremos una primera reunión informal en los próximos días (esté atento porque se informará a través de la página del meetup) en donde se establecerán los principios que rigen al grupo y los objetivos del mismo. [Vamos a seguir estos pasos](http://www.revolutionanalytics.com/news-events/r-user-group/how-to-start-r-user-group.php) para la consolidación del grupo y pediremos patrocinio a universidades, empresas e instituciones para empezar con un primer ciclo de conferencias. Gracias por su participación.
