---
title: "Ciclo de discusión de la estadística Bayesiana en la medicina - Revista Comunicaciones en Estadística"
author: "Andrés Gutiérrez"
date: "2013-12-13"
categories:
  - "Bayesian Statistics"
  - "Publications"
---

El último número de la Revista Comunicaciones en Estadística, que edita la Facultad de Estadística de la Univerisdad Santo Tomás, trae un regalo navideño: una discusión muy interesante acerca de la aplicación de la estadística Bayesiana en la práctica médica. El reconocido estadístico Luis Carlos Silva trae a colación una discusión muy acertada acerca de la última obra del filósofo Mario Bunge, Filosofía para Médicos. Otros tres investigadores intervinieron en la discusión sobre le tema y por último, Luis Carlos dio su réplica a la discusión.

Les dejo el texto de Mario Bunge, que encendió la discusión:

> "En otros campos, la probabilidad suele concebirse como una intensidad o creencia. Esta es la interpretación subjetiva de la probabilidad, usualmente llamada bayesiana… Por ser subjetivas, las probabilidades bayesianas son arbitrarias. Y, siendo arbitrarias, no tienen cabida en la ciencia auténtica ni en medicina científica."

A continuación los artículos de la discusión:

Luis Carlos Silva - [En defensa de la racionalidad bayesiana: a propósito de Mario Bunge y su "Filosofía para médicos."](http://revistas.usta.edu.co/index.php/estadistica/article/view/482/998)

Andrés Gutiérrez - [Acerca de la defensa de la racionalidad bayesiana y la obra de Mario Bunge.](http://revistas.usta.edu.co/index.php/estadistica/article/view/948/999)

Jairo Fúquene - [El caso de la estadística bayesiana objetiva como una posibilidad en ensayos clíinicos.](http://revistas.usta.edu.co/index.php/estadistica/article/view/949/1000)

Jorge Ortiz - [Mario Bunge y la estadística bayesiana.](http://revistas.usta.edu.co/index.php/estadistica/article/view/950/1001)

Luis Carlos Silva - [Réplica: La larga vida científica que le espera a Thomas Bayes](http://revistas.usta.edu.co/index.php/estadistica/article/view/951/1002).
