---
title: "Resultados de la encuesta de factibilidad de los posgrados en Estadística Aplicada"
author: "Andrés Gutiérrez"
date: "2013-06-20"
categories:
  - "Surveys"
  - "Sampling"
---

Gracias por dejarnos saber su opinión acerca de su intención de realizar (o no) un posgrado en estadística aplicada. Como "compensación simbólica" quisiera que la información que se recopiló en este sondeo esté disponible para quien quiera. [En este enlace](http://gutierrezandres.files.wordpress.com/2013/06/descriptivos.pdf) está el resultado de la encuesta. Muchas gracias una vez más puesto que afortunadamente hubo una buena recepción. Creo que la encuesta estuvo bien localizada. La mayoría de personas fueron muy abiertas en proveer sus nombres y demás datos personales.

Les cuento entonces que este proyecto ya se echó a andar en la Facultad de Estadística de la Universidad Santo Tomás y esperamos que todos ustedes nos apoyen con ideas y comentarios respetuosos. Estamos seguros de que haremos una importante labor, con mucha responsabilidad y con mucha calidad. Pueden tener la seguridad de que esa será nuestra impronta en este proyecto.
