---
title: "Descripción de los cursillos en el 3er IWAS - Data Mining en Colombia - Universidad Santo Tomás"
author: "Andrés Gutiérrez"
date: "2013-03-22"
categories:
  - "Estadística"
---

Si desean más información no duden en escribirnos. La página oficial de la Facultad es https://web.archive.org/web/20240527213655/http://estadistica.usta.edu.co/. La página oficial del evento en donde se pueden inscribir es http://eventos.usta.edu.co/inscripcion_web.cfm?evento=66

La Facultad de Estadística de la Universidad Santo Tomás tiene el gusto de extenderles la invitación para que nos acompañen en el evento denominado "Third International Workshop on Applied Statistics", cuyo tema es la minería de datos. Para esta ocasión tendremos los siguientes entrenadores y capacitaciones:

***Entrenamiento #1***

***Práctica del análisis estadístico de datos textuales***

***Ludovic Lebart, PhD.***

*El curso consta de 6 sesiones de 1 hora y 30 minutos aproximadamente cada una, repartidas en tres mañanas y los estudiantes deben tener computadora personal (equipo portátil). En la primera sesión se descargará (o copiará desde una memoria USB) el software gratuito, el manual de uso del software (en castellano), y de los datos utilizados para los ejemplos en todo el curso.*

*Los temas incluirán: *

- *Listado de análisis estadísticos de los textos.*

- *El caso particular de las preguntas abiertas en las encuestas.*

- *La elección de las unidades estadísticas.*

- *Herramientas para la descripción multidimensional (análisis de componentes principales, análisis de correspondencias simples y múltiples, clasificación, Mapas de Kohonen).*

- *Los diferentes niveles de segmentación del texto.*

- *Las unidades características (palabras, frases, respuestas).*

- *La "lematización" de los textos.*

- *Los procedimientos de validación estadística: aplicación específica del "bootstrap" en el caso de los datos textuales.*

- *Estrategia de análisis.*

*Los ejemplos serán discutidos en cada sesión (ambos cálculos e interpretaciones).*

***Entrenamiento #2***

***Introducción al análisis de redes sociales***

***Emanuel Viennet, PhD.***

*El curso consta de 6 sesiones de 1 hora y 30 minutos aproximadamente cada una, repartidas en tres mañanas y los estudiantes deben tener computadora personal (equipo portátil).**Las numerosas aplicaciones de las plataformas de redes sociales en Internet plantean nuevos desafíos, tanto a nivel teórico como tecnológico. Dichos sistemas generan datos de gran volumen, asociando contenidos multimedia (imágenes, videos, textos) e informaciones relacionales ("amigos", "followers", etc.). Estos datos se modelan como redes complejas (complex networks), las cuales se caracterizan por propiedades específicas, compartidas con muchas redes encontradas en otros contextos: redes de transporte, redes biológicas, etc.**En esta entrenamiento, presentaremos las bases del análisis de las redes sociales, ilustrados con ejemplos reales y descripción de aplicaciones modernas.*

*Temas abordados: *

- *Redes sociales y ciencia de redes (network science); *

- *Teoría de los grafos; extracción de datos y construcción de grafos; *

- *Características estructurales de los grafos sociales; *

- *Visualización de grafos; *

- *Identificación de comunidades globales y locales; *

- *Aplicaciones con software libre de uso general; *

- *Difusión de información y "viralidad" (viral marketing); *

- *Data mining y aprendizaje automático en las redes sociales; *

- *Ejemplos de aplicaciones reales: detección del fraude en e-comercio, previsión de churn, animación de comunidades en el Web 2.0.*

*Prerequisitos: el curso se destina a un público con cultura general científica, pero no requiere conocimientos avanzados en matemáticas o informática. Se aprovechará de los computadores de los participantes para instalar software (libre) específico y hacer unos ejercicios de aplicación.*

***Entrenamiento #3***

***New advances in data mining: large-scale, streaming and distributed data***

***George Hebrail, PhD.***

*El curso consta de 6 sesiones de 1 hora y 30 minutos aproximadamente cada una, repartidas en tres mañanas y los estudiantes deben tener una computadora personal (equipo portátil). Este entrenamiento será impartido en el idioma inglés.*

*We have entered now in the era of 'Big Data'. According to Gartner, Big Data is related to the 3V's challenges: *

- *Volume (the amount of data to process is huge), *

- *Velocity (data arrives online and must be processed in real time) and, *

- *Variety (data is produced by multiple sources and is of various types – structured, text, image, audio, etc.).*

*In this course, we will first introduce the basic concepts related to some solutions to face the 3V's, i.e. Map Reduce framework for large scale data processing, data stream management, and distributed processing frameworks such as P2P or agents-based. Then, we will show how standard data mining algorithms can be adapted to these frameworks. The course will also present some applications.*

Como pueden evidenciar la didáctica de nuestro evento está enfocada en proveer un entrenamiento intensivo de un experto en la temática. Es decir, se trata, no de un cursillo de dos o tres horas, sino de una capacitación brindada por autoridades internacionales y reconocidas en el medio estadístico. Los cursos serán en las mañanas y tendremos ciclos de conferencias en la noche con invitados internacionales y nacionales. **El evento empezará el día 10 de abril y finalizará el 13 de abril.** Para su información, los costos son los siguientes:

**Estudiante de la USTA: $ COL 150.000**

**Estudiante externo: $ COL 180.000**

**Profesor de la USTA: $ COL 200.000**

**Profesor externo: $ COL 250.000**

**Profesional: $ COL 250.000**

**Participantes con ponencias: $ COL 120.000**

Si desean más información no duden en escribirnos. La página oficial de la Facultad es https://web.archive.org/web/20240527213655/http://estadistica.usta.edu.co/. La página oficial del evento en donde se pueden inscribir es http://eventos.usta.edu.co/inscripcion_web.cfm?evento=66

Por favor no dejen que se agoten los cupos, pues son limitados.

Cordial saludo,

**Comité Organizador**

**International Workshop on Applied Statistics (IWAS)**

**Facultad de Estadística**

**Universidad Santo Tomás**

**[http://estadistica.usta.edu.co](https://web.archive.org/web/20240527213655/http://estadistica.usta.edu.co/)**
