---
title: "#PredictiveCOL (Update #3)"
author: "Andrés Gutiérrez"
date: "2014-04-16"
categories:
  - "Colombia"
  - "Estadística"
---

In case you didn't know, [some guys carried out a massive poll](http://www.partidoverde.org.co/Portals/0/Documentos/CONSOLIDADO%20NACIONAL%20ABRIL%202014.pdf) (more than 9000 interviewed households). Having into account that the sample size of this poll is larger than regular polls (more than 6 times), our methodology gave it a weighted score of 96% - As polls get older, they lose weight in our bayesian approach. Let me congratulate those guys, they are showing us that decent polls are possible in Colombia. However, I am still wondering why this particular poll did not receive proper attention in the media. That sucks!

This is the third update of our [predictions for the Colombian presidential run](https://web.archive.org/web/20140730203514/http://www.gutierrezandres.com/predictivecol). We introduce a new graphic showing the evolution of vote intention for all of the contenders. This kind-of-chart shows that Santos' voting intention score is decreasing as we are getting closer to the election day. Note that Peñalosa's score is increasing markedly. The scores of the remaining contenders are flatlined.

Now, if election were held today, this is the SNAPSHOT (mere opinion) of the run.

On the other hand, having into account the auxiliary information, this is the forecast of the election for the day to be hold (May 25, 2014)

That said, this is the posterior distribution of voting intention. Peñalosa remains in second place, still far from Santos, but farther from Zuluaga. Bad news for Ramirez who is below Lopez.

Our simulations allow to predict some interesting parameters:

The probability that Santos wins with more than 50% of the votes (which ensures that there will be no second run) is 1.01%.

1. The probability that Peñalosa defeats Santos in the first run is 0.96%.

2. The probability that Peñalosa defeats Zuluaga is 80.55%.

So, with today's info, we can claim that there will be 2nd run and the contender of Santos would be Peñalosa.

Stay tuned!!!
