---
title: "Comparison of Some Small Area Estimation Techniques"
author: "Andrés Gutiérrez"
date: "2014-03-27"
categories:
  - "Modeling"
  - "Publications"
---

[This paper](http://gutierrezandres.files.wordpress.com/2014/03/smallarea.pdf) was published by DANE's journal in its last edition.

Several demographic methods have been developed in order to estimate a population total from a domain. Some of these methods do not take into account the random nature of the dynamic structure of the population, but are based on widely accepted demographic theories, among these techniques are rates of living (Bogue, 1950), the composite methods (Bogue & Duncan, 1959) and the housing unit type (Smith & Lewis, 1980). However, there are demographic methods that do involve a random component in the estimation, e.g. symptoma- tic regression procedures –including the correlation ratio method (Schmitt & Crosetti, 1954) and the correlation difference method (O`Hare, 1976)– and the sample regression method (Ericksen, 1974).

Here ([paper_choco_VF.pdf](http://gutierrezandres.files.wordpress.com/2014/03/paper_choco_vf.pdf)) you can download a draft version of the paper.
