---
title: "samplesize4surveys R package (ss4s) - A message to my colleagues"
author: "Andrés Gutiérrez"
date: "2014-03-20"
categories:
  - "Estadística"
  - "R"
  - "Stats"
---

I have worked for more than four years for a respected institution of the government of Colombia. My consulting job there is also linked with the review of sampling plans that external companies provide in order to get information about the impact that public programs may have over the people who benefit from some interventions. Obviously, a lot of sampling designs are involved in the methodologies that those companies provides. At the end, we choose the best proposal to evaluate a public policy.

Over the years, I have noticed that a few companies have well implemented technical proposals on survey sampling. The truth is that the majority of consulting companies in Colombia have technical weakness when it comes to compute sample sizes.

By the way, think about this: companies hire statisticians that do no have proper skills to compute sample sizes. That is weird, because for some reason, those companies decide to hire us! It is supposed that we know how to compute sample sizes! - As professors and people enrolled with academia, we should encourage our students to gain skills on sample size computation-. This is not a minor topic. It is very relevant. Your taxes are thrown away just because statisticians do not compute proper sample sizes. Moreover, decisions are made based on studies that do not meet the requirements on statistical confidence and precision. I am sure that some studies on public policy are very biased because of this issue of the sample size.

Ok, I am enrolled in a new project, a very exciting one! I am very pleased to present you the [samplesize4surveys](http://cran.r-project.org/web/packages/samplesize4surveys/) R package (ss4s). Right now it is under construction, but the online version already features some useful functions to compute your sample size. It will be all sampling-design-based, you will find how to compute sample sizes for mere estimation and sample size for hypothesis testing. I hope you enjoy the package and feel free to warn me about possible issues.
