---
title: "#PredictiveCOL (Update #1)"
author: "Andrés Gutiérrez"
date: "2014-03-26"
categories:
  - "Elections"
  - "Modeling"
---

This is the first update of our [predictions for the Colombian presidential run](https://web.archive.org/web/20140730203514/http://www.gutierrezandres.com/predictivecol). Note that at this time, we still do not know if Martha Lucía Ramírez will be supported by the Conservative Party. This way, if election were held today, this is the SNAPSHOT (mere opinion) of the run.

On the other hand, having into account the auxiliary information, this is the forecast of the election for the day to be held (May 25, 2014)

Our simulations allow to predict some interesting parameters:

The probability that Santos wins with more than 50% of the votes (which ensures that there will be no second run) is 2.8%.

1. The probability that Peñalosa defeats Santos in the first run is 0.004%.

2. The probability that Zuluaga defeats Santos in the first run is 0.042%.

3. The probability that Peñalosa defeats Zuluaga is 50.2%.

4. Undecided voters would not be blank voters.

So, with today's info, we can claim that there will be 2nd run and the contender of Santos could be Peñalosa or Zuluaga.

Stay tuned!!!
