---
title: "Thinking weirdly"
author: "Andrés Gutiérrez"
date: "2014-11-29"
categories:
  - "Colombia"
  - "Estadística"
---

Today I was talking with an old acquaintance. This guy is an statistician that thinks different. I don't know how to describe its way of thinking, but I know how to describe our way of thinking. As Colombian statisticians:

- As soon as we arrive to the labor market, we begin to think with a little bit of selfishness. We want to make money (that's not bad) and we want to buy things. Things that we lack when studying in the university. This way, we begin to work in many different places. We have our job, but at the same time, we are consultants on other projects and in the night we give classes.

- We have failed to associate. The oldest undergraduate program in statistics is almost 60 years old. Some other programs have appeared, and some others have disappeared. In almost 60 years, we have done anything to create powerful alliances that put ourselves in decision making positions.

- We have failed to realise that our profession is the next big thing. Right now, this world urges statisticians. We are important for this world to be. Imagine the performance of google (or your cellphone, or your computer, or anything) without statistics.

- We have failed to be people of influence. It looks like we are not interested in assuming directive positions. We are not interested in politics, we have no big relationships with other professional. If some technical institution requires people to assume directive positions, we do not apply.

- We have failed to be entrepreneurs. We want to be in the comfort zone. We are not taking risks. We want our money at the end of the month. We lose opportunities because we do not want to do anything else but convenient things.

A lot of theorems, a lot of databases, a lot of jobs, a lot of money, but a very short vision. When we realize that life is not only money and that we have wasted our time when focusing in ourselves and our necessities, it is to late because we have no strength anymore, we are old and that was it for us.

However...

The time has come when young people may and should appropriate their duty. Old people may and should encourage young statisticians to be in risky positions, to take leadership attitudes, to stand in front of the business, to rule the National Statistical Office (DANE), to be in the senate, to give jobs to some other statisticians.

I want to be of local influence. I am a proud Colombian guy that want to lead our country by doing my thing: to take risks, to help other people to improve, to educate, etc. If you are old, help me; if you are young, join me in this adventure.
