---
title: "#PredictiveCOL (Update #5)"
author: "Andrés Gutiérrez"
date: "2014-05-06"
categories:
  - "Elections"
  - "Modeling"
---

The new poll by Cifras & Conceptos has been released. This is the fifth update of our [predictions for the Colombian presidential run](https://web.archive.org/web/20140730203514/http://www.gutierrezandres.com/predictivecol). The trends of Peñalosa and Zuluaga remain upward. The scores of the remaining contenders are flatlined.

Now, if election were held today, this is the SNAPSHOT (mere opinion) of the run.

On the other hand, having into account the auxiliary information, this is the forecast of the election for the day to be hold (May 25, 2014)

That said, this is the posterior distribution of voting intention. Peñalosa lost the second place, still far from Santos, and Zuluaga.

Our simulations allow to predict some interesting parameters:

The probability that Santos wins with more than 50% of the votes (which ensures that there will be no second run) is 0.57%.

1. The probability that Peñalosa defeats Santos in the first run is 0.15 %.

2. The probability that Zuluaga defeats Santos in the first run is 0.52 %.

3. The probability that Zuluaga defeats Peñalosa is 66.35 %.

So, with today's info, we can claim that there will be 2nd run and the contender of Santos would be Zuluaga.

Stay tuned!!!
