---
title: "#PredictiveCOL (Update #4)"
author: "Andrés Gutiérrez"
date: "2014-04-27"
categories:
  - "Colombia"
  - "Estadística"
---

This week new polls were released (from [Datexco](http://www.eltiempo.com/elecciones-2014/presidencia/juan-manuel-santos-ganara-en-segunda-vuelta/13888615), [CNC](http://www.cmi.com.co) and [IPSOS](http://www.rcnradio.com/noticias/presidente-candidato-santos-ganaria-en-la-segunda-vuelta-segun-la-gran-encuesta-132576)). The results of voting intention are somehow obscure because of the large proportion of undecided and blank voters. As usual, media insist in elaborating fantastic stories (big winners and so on) and giving misleading conclusions. Why? Because with an undecided voting rate around 30% anything may happen! And, of course, once in the voting station you must already have taken your decision.

This is the forth update of our [predictions for the Colombian presidential run](https://web.archive.org/web/20140730203514/http://www.gutierrezandres.com/predictivecol). The trends of Peñalosa and Zuluaga remain upward. The scores of the remaining contenders are flatlined.

Now, if election were held today, this is the SNAPSHOT (mere opinion) of the run.

On the other hand, having into account the auxiliary information, this is the forecast of the election for the day to be hold (May 25, 2014)

That said, this is the posterior distribution of voting intention. Peñalosa lost the second place, still far from Santos, but closer to Zuluaga.

Our simulations allow to predict some interesting parameters:

The probability that Santos wins with more than 50% of the votes (which ensures that there will be no second run) is 0.63%.

1. The probability that Peñalosa defeats Santos in the first run is 0.16 %.

2. The probability that Zuluaga defeats Santos in the first run is 0.26 %.

3. The probability that Peñalosa defeats Zuluaga is 40.04 %.

4. The probability that Zuluaga defeats Peñalosa is 53.45 %. (It is not a mistake… Think well about Monte Carlo).

So, with today's info, we can claim that there will be 2nd run and the contender of Santos would be Zuluaga or Peñalosa.

Stay tuned!!!
