---
title: "#PredictiveCOL (Update #6)"
author: "Andrés Gutiérrez"
date: "2014-05-14"
categories:
  - "Elections"
  - "Modeling"
---

The new poll by [CNC](http://www.cmi.com.co/?n=229447) has turned the Colombian opinion upside down. Now, there is a clear polarization between Santos and Zuluaga. This is the sixth update of our [predictions for the Colombian presidential run](https://web.archive.org/web/20140730203514/http://www.gutierrezandres.com/predictivecol). The trend of Zuluaga is the only one that still remains upward. The scores of the remaining contenders are flatlined or downward.

Now, if election were held today, this is the SNAPSHOT (mere opinion) of the run.

On the other hand, having into account the auxiliary information, this is the forecast of the election for the day to be hold (May 25, 2014)

That said, this is the posterior distribution of voting intention.

Our simulations allow to predict some interesting parameters:

The probability that Santos wins with more than 50% of the votes (which ensures that there will be no second run) is 0.63%.

1. The probability that Zuluaga defeats Santos in the first run is 1.39 %.

2. The probability that Zuluaga defeats Peñalosa is 85.48 %.

So, with today's info, we can claim that there will be 2nd run and the contender of Santos would be Zuluaga.

Stay tuned!!!
