---
title: "#PredictiveCOL (Update #1 - Second run)"
author: "Andrés Gutiérrez"
date: "2014-05-29"
categories:
  - "Colombia"
  - "Estadística"
---

From the info that pollsters collected about the second run, we present the first update of the predictions for the second run of the presidential election in Colombia. The trend of Zuluaga remains upward and the conditional expectation of the voting intention is higher for Zuluaga than for Santos.

Now, if election were held today, this is the SNAPSHOT (mere opinion) of the run. The credibility interval from blank vote is (0.5 %, 1.3 %), for Santos is (41 %, 51 %) and for Zuluaga is (48 %, 58 %).

On the other hand, having into account the auxiliary information, this is the forecast of the election for the day to be hold (June 15, 2014). The credibility interval from blank vote is (2.9 %, 4.4 %), for Santos is (42.7 %, 52.6 %) and for Zuluaga is (43.6 %, 53.6 %).

That said, this is the posterior distribution of voting intention.

Our simulations allow to predict some interesting parameters:

1. The probability that Zuluaga defeats Santos in the first run is 52.06 %.

2. The probability that Santos defeats Zuluaga is 44.02 %.

Stay tuned for the new predictions of the second run!!!
