---
title: "Proyecto GitHub - Estrategias de muestreo: diseño de encuestas y estimación de parámetros"
author: "Andrés Gutiérrez"
date: "2015-06-28"
categories:
  - "Estadística"
  - "GitHub"
  - "LaTeX"
  - "Teaching"
---

Hace seis años nacía mi primer libro: [Estrategias de muestreo](http://www.amazon.com/Estrategias-Muestreo-encuestas-estimacion-parametros/dp/9586316084) (EM). Este libro abarca los contenidos más importantes del muestreo y la inferencia basada en encuestas y utiliza el software R. En los últimos años, EM ha sido utilizado por profesores y consultores a lo largo de Colombia y Latinoamérica. El éxito del libro ha implicado que a la fecha se haya vendido todo el tiraje de la primera edición.

Con la evolución tecnológica en materia de contenidos científicos, han surgido nuevas herramientas que permiten no sólo la visualización estética de contenidos estadísticos sino la integración de LaTeX con R. Es por esto que la segunda edición de este libro estará escrita en la plataforma [RStudio](http://www.rstudio.com) y utilizará [knitr](http://yihui.name/knitr/) como gestor de intrerlocución entre LaTeX y R.

Este proyecto estará disponible de manera gratuita en [mi repositorio de GitHub](https://psirusteam.github.io/EstrategiasDeMuestreo/). Esta plataforma permite que las personas interesadas (sin importar su lugar de ubicación) puedan compilar los contenidos del libro y sugerir cambios o mejoras.

En resumen: en GitHub podrá encontrar el código LaTeX de los capítulos del libro que se encuentren en producción, el código en R para reproducir los ejemplos del libro y el archivo PDF del libro. Este proyecto permitirá que los interesados puedan descargar el material y producir nuevos contenidos a partir del libro.

¡Sean todos bienvenidos!
