---
title: "My talk in Bogotá - Pvalues: use and abuse"
author: "Andrés Gutiérrez"
date: "2016-08-18"
categories:
  - "Inference"
  - "Teaching"
---

Did you know that American Statistical Association (ASA) [made a disclaimer about the proper use of p-values](http://www.tandfonline.com/doi/pdf/10.1080/00031305.2016.1154108?needAccess=true)? Moreover, ASA (the oldest scientific association in the USA) claimed that:

1. P-values can indicate how incompatible the data are with a specified statistical model.

2. P-values do not measure the probability that the studied hypothesis is true, or the probability that the data were produced by random chance alone.

3. Scientific conclusions and business or policy decisions should not be based only on whether a p-value passes a specific threshold.

4. Proper inference requires full reporting and transparency.

5. A p-value, or statistical significance, does not measure the size of an effect or the importance of a result.

6. By itself, a p-value does not provide a good measure of evidence regarding a model or hypothesis.

With such a disclaimer, from my statistical perspective I gave a talk at ICFES about the use (misuse and abuse) of p-values and how to face this new reality. In the end, I consider that p-values and hypothesis testing have several disadvantages in this information era. With Petabytes of data generated every day, sample sizes influence directly on p-values, and decisions taken from this perspective may be misleading.

[Hope you enjoy these slides.](https://drive.google.com/open?id=0ByzoHkgSB8F3cXA4bXgtT1BnMjQ)
