---
title: "Voting intention and calibration estimators - My article in CJS"
author: "Andrés Gutiérrez"
date: "2016-07-19"
categories:
  - "Elections"
  - "Estadística"
  - "Sampling"
  - "Stats"
---

During the last few years, I've been very interested in electoral studies. If you have been a reader of this blog, maybe you could remind that I predicted, some years ago, that Santos was going to win the presidential elections in Colombia. From that very election (Zuluaga won in the first round, while Santos won in the soon round), I learned that estimating voting intention is not a matter of sample size. Moreover, is not an issue of sampling. Elections are a very dynamic process that takes into account so many factors. However, in this paper, we strived to relate a sampling technique called "sampling calibration" with "electoral studies." So, if you are a social researcher on political issues, and if you are interested in predicting voting intention, this paper published in the Colombian Journal of Statistics is just for you.

Here is the abstract: In this paper, the calibration approach is revisited to allow new calibration weights that are subject to the restriction of multiple calibration equations on a vector of ratios, means, and proportions. The classical approach is extended in such a way that the calibration equations are not based on a vector of totals, but on a vector of other nonlinear parameters. We stated some properties of the resulting estimators and carried out some empirical simulations to assess the performance of this approach. We found that this methodology is suitable for some practical situations like vote intention estimation, estimation of the labor force, and retrospective studies. The method is applied in the context of the Presidential elections held in Colombia in 2014 for which we estimated the vote intention in the second round using information from an election poll, taking the results from the first round as auxiliary information.

[Here is the link to the entire document.](https://drive.google.com/open?id=0ByzoHkgSB8F3THp0cHVyOVhKYTQ)
