---
title: "Más importante que el principio de representatividad"
author: "Andrés Gutiérrez"
date: "2019-05-28"
categories:
  - "Encuestas"
  - "Muestreo"
---

Quiero retomar mi actividad bloguera abordando un tema casi filosófico que ha marcado mi práctica profesional desde siempre. Se trata del principio de representatividad y cuándo es pertinente utilizarlo. Si ante un fenómeno desconocido, fuera posible observar de forma exhaustiva a toda la población, no dudaríamos ni un instante en utilizar la estadística descriptiva para responder a las preguntas de interés. Por ejemplo, en estadísticas sociales, si la pregunta fuese cuál es el cambio de la tasa de desempleo en dos periodos consecutivos, bastaría con observar a la población en los dos periodos consecutivos y hacer una simple operación matemática para responder a esta cuestión. Bajo este escenario, no habría necesidad de pruebas de hipótesis, ni de intervalos de confianza, ni de escoger estrategias de estimación porque simplemente no serían necesarias. Sin embargo, como este escenario no se puede ejecutar en la realidad, tenemos que conformarnos con planear encuestas, seleccionar muestras y hacer inferencias objetivas y subjetivas.

Hacer inferencias objetivas está bien haciendo uso del método científico y de la teoría estadística. En este ámbito es necesario acudir al principio de representatividad que básicamente descansa en el hecho de que, en la mayoría de las ocasiones, las poblaciones se aglomeran: pobres con pobres, ricos con ricos. Existe una alta homogeneidad dentro de los sectores censales. Si vamos a las zonas marginales de una ciudad y escogemos una manzana, la probabilidad de que nos encontremos con muchos hogares pobres dentro de esta manzana es muy alta; asimismo, la probabilidad de que nos encontremos con hogares acaudalados en esta manzana es casi nula. Si vamos a los sectores más adinerados de la ciudad, nos encontraremos con hogares pudientes y no con hogares pobres. Por lo tanto, la heterogeneidad entre los sectores censales es alta. De esta manera se van configurando las realidades regionales, que al parecer son realidades de los países en vía de desarrollo. Gracias a esta realidad podemos decir que es posible seleccionar una muestra con una fracción de muestreo pequeña y concluir sobre todo un país. Estas conclusiones se permiten porque el mecanismo inferencial descansa sobre el principio de representatividad que involucra el cálculo de ponderadores, que vienen inducidos directamente de las probabilidades de inclusión del diseño de muestreo.

Hay inferencias subjetivas también. Hacer inferencias subjetivas está mal y lamentablemente es lo que mejor sabemos hacer al momento de leer los datos de una encuesta. Nótese que no estoy hablando de un sondeo, cuyas desventajas se dan por descontado. Si los datos de una encuesta no se ponderan, las inferencias resultantes son inadecuadas. Seguramente es por la falta de adiestramiento en las facultades y en los cursos de estadística, que parten del supuesto ([ver acá](2011-09-06-del-muestreo-a-la-teoria-estadistica-si-no-utilizo-un-mas-con-reemplazo-sus-analisis-no-son-validos.qmd)) de que se tienen muestras aleatorias simples con reemplazo en todos los estudios. La verdad, en estos años de experiencia profesional, jamás he seleccionado una muestra aleatoria simple con reemplazo. Todas las muestras de las encuestas grandes son complejas y se alejan de estos supuestos. Por lo tanto, utilizar la base de datos para sacar conclusiones sin utilizar los ponderadores es errado.

En general, lamentablemente he comprobado que el tema de la ponderación tiene poco calado en la región; me he encontrado con estupendos investigadores, apasionados por su país, con maravillosas bases matemáticas y estadísticas, pero desconocedores del principio de representatividad, o desconocedores de un principio más grande que este: **el diseño nunca puede ser pasado por alto** ([ya lo decía el sabio Leslie](2014-12-03-leslies-advice-on-statistical-design.qmd)). Hace dos años en Cuiabá, un profesor me contó una anécdota interesante. En un país latinoamericano se contrató el diseño de una evaluación de impacto sobre una intervención estatal de grandes proporciones. Por aquellas cuestiones burocráticas, que suelen suceder en esta región macondiana, el levantamiento de la información se contrató aparte del análisis de los datos. Un gran equipo de muestristas diseñó la encuesta, que entre otras cosas había estratificado con algún criterio el marco de muestreo. Otro gran equipo de influyentes académicos analizó los datos; pero cometieron un error, no tuvieron en cuenta el diseño de la encuesta. Fuese cuales fuesen los resultados, no tener en cuenta la estratificación tiene implicaciones muy graves en el cálculo de las varianzas, el error estándar de los estimadores y, por consiguiente, en la determinación de si hubo o no impacto del programa en la población que lo recibió. Es decir, la inferencia fue subjetiva y lo más probable es que, como dicen en mi tierra, esa platica se haya perdido ([ver acá](2011-11-24-pensamientos-de-un-auditor-en-muestreo.qmd)).

Retomando la introducción de esta entrada, quiero ser enfático al decir que, cuando haya una encuesta de por medio, siempre hay que tener en cuenta el principio de representatividad, no sólo utilizando los ponderadores sino también conociendo el diseño el diseño de muestreo, que se traduce en estratos, unidades primarias de muestreo, pesos de muestreo, ajustes al marco, ajustes por ausencia de respuesta, calibración, entre otros. Ya tendremos tiempo de profundizar en estas cuestiones.
