---
title: "La aproximación al último conglomerado (parte 1)"
author: "Andrés Gutiérrez"
date: "2019-06-10"
categories:
  - "Encuestas"
  - "Muestreo"
  - "R"
---

Photo by [Florian van Duyn](https://unsplash.com/@flovayn?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText) on [Unsplash](https://unsplash.com/search/photos/final?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText)

Hace algunos [años había escrito](2011-08-29-cuidado-con-la-estimacion-de-la-varianza-sas-pc-carp-sudaan-wesvar-y-r-pueden-arrojar-malos-resultados.qmd) [acerca del uso de las aproximaciones de la varianza](2011-08-29-cuidado-con-la-estimacion-de-la-varianza-sas-pc-carp-sudaan-wesvar-y-r-pueden-arrojar-malos-resultados.qmd) y se podía leer a un autor muy crítico del uso indiscriminado del software. Sigo pensando esto, aunque después de haberle dado la vuelta a las Oficinas Nacionales de Estadística en la región, creo que el uso del software es adecuado y necesario. En esta entrada quiero profundizar un poco acerca del espíritu de estas aproximaciones.  En primer lugar diré que, a diferencia de otras ramas de la estadística aplicada (como los modelos lineales, los modelos lineales generalizados, el diseño de experimentos, las series de tiempo e incluso los modelos de estadística bayesiana), el diseño y análisis de encuestas difícilmente se puede generalizar. Lo que quiero decir con esto es que, por ejemplo, casi cualquier estimación del vector de coeficientes de regresión en un modelo lineal y su correspondiente estimación de la matriz de varianzas se pueden expresar como formas matriciales fácilmente computables; mientras que en el mundo del muestreo, el estimador siempre se expresa como una forma lineal, la estimación de su varianza no tiene una expresión común general. Si el diseño de muestreo fue sistemático, la estimación de la varianza es muy diferente a si el diseño de muestreo fue estratificado en tres etapas, que a su vez es muy diferente a si el diseño de muestreo tuvo selección de UPMs proporcional a una medida de tamaño. Evidentemente sí existen tales fórmulas, pero son tan disímiles que no pueden generalizarse. Por tanto, es casi imposible que el programador del software automatice cada caso particular de todos los diseños de muestreo a funciones computacionales para la estimación de la varianza.

La gran idea fue de Hansen, Hurwitz, y Madow en 1953 y desde entonces, la aproximación de la varianza con la técnica del último conglomerado se ha posicionado en las Oficinas Nacionales de Estadística ([en este artículo](http://www.isr.umich.edu/src/smp/asda/first_stage_ve_new.pdf), Brady West presenta un recuento exhaustivo de las bondades del método). En general, la idea es que el software reconozca tres elementos importantes en la base de datos: los *estratos* ($ h=1, \ldots, H $), las *UPMs* ($ i \in sI_h $) y los *pesos finales de muestreo* ($ w_k $). De esta forma, cualquier estimador del total de una variable $ y $ estará dado por la siguiente expresión:  $\hat t_y = \sum_{h=1}^H \sum_{i \in sI_h}\sum_{k\in s_i} w_ky_k $  La aproximación del *último conglomerado*para la varianza del estimador del total, que es la misma que utilizan todos los softwares computacionales usados en las Oficinas Nacionales de Estadística (como SAS, SPSS, R, Stata, Wesvar, SUDAAN, entre otros) está dada por la siguiente expresión:  $\wide\hat{\Var}(\hat{t}_y)=\sum_{h=1}^H \frac{n_{Ih}}{n_{Ih} -1}\sum_{i \in sI_h}\left( \breve{t}_{y_i} - \bar{\breve{t}}_{y_h} \right)^2$  En donde $ n_{Ih}$ representa el número de UPMs que han sido seleccionadas en el estrato $ h $, $\breve{t}_{y_i}=\sum_{k \in s_i} w_k y_k $ es una estimación del total de la variable en la UPM $ i $ dentro de su estrato, y $\bar{\breve{t}}_{y_h} =\frac{1}{ n_{Ih} }\sum_{i \in sI_h}\breve{t}_{y_i}$ es un promedio de las estimaciones de los totales de las UPM en el estrato $ h $.

En general, puedo dar fe de que esta aproximación funciona bien en encuestas de hogares que abordan fenómenos sociales. La razón: en toda América Latina las UPMs están agrupadas (en mayor o menor grado) de acuerdo al nivel de poder adquisitivo de los hogares. Los hogares acaudalados se agrupan junto a hogares acaudalados y los hogares pobres se agrupan junto a hogares pobres. Ahora, por lo general, los fenómenos sociales están relacionados con el poder adquisitivo. Es por esto que encontramos que la pobreza tiene una mayor incidencia en algunas zonas de las ciudades y no se distribuye de forma uniforme; la informalidad en el mercado laboral tiene su concentración en sectores específicos; el crimen y la victimización también tienen una mayor incidencia en algunos sectores; el consumo de los hogares no es el mismo en todos los sectores de la ciudad, etc. Por las anteriores razones, es posible concluir que al interior de las UPMs y al interior de los hogares, hay una gran homogeneidad, pero entre UPMs hay una mayor heterogeniedad. Por lo tanto, al considerar un muestreo multietápico, cuando se separa la contribución de la varianza en cada etapa, se encuentra que la varianza total está dominada por la contribución de la variabilidad en la primera etapa y que la contribución de las etapas subsiguientes es muy pequeña y, por ende, despreciables.
