---
title: "¿Análisis de encuestas sin UPMs y sin estratos?"
author: "Andrés Gutiérrez"
date: "2019-06-08"
categories:
  - "Encuestas"
  - "Muestreo"
---

Photo by

[AbsolutVision](https://unsplash.com/@freegraphictoday?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText)

on

[Unsplash](https://unsplash.com/search/photos/idea?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText)

Hace algún tiempo que estoy pensando en el problema de - en el contexto de las encuestas de hogares - cómo estimar aproximadamente bien los errores de muestreo de un estimador cuando la base de datos únicamente incorpora los factores de expansión y omite la información de las unidades primarias de muestreo (UPMs) y de los estratos. Este no es un problema si uno está trabajando en una Oficina Nacional de Estadística (ONE), puesto que allí se tiene acceso irrestricto a la ubicación de los hogares en los sectores censales o cartográficos, y por ende la pertenencia del hogar a las UPMs y a los estratos. Sin embargo, muchos investigadores externos a las ONEs no tienen acceso a esta información, puesto que la publicación de las bases de datos pasa por un proceso de anonimización de la información, en donde se ocultan todas las evidencias que pudieran hacer que un hogar sea identificado por la información que proveyó en la encuesta.  Pregunté a los que saben de muestreo y fui remitido a

[una solución realmente creativa y sencilla de Brady T. West](https://journals.sagepub.com/doi/pdf/10.1177/1536867X1201200410)

en la que se plantea la utilización de los pesos de muestreo, que están dados en cualquier base de datos de encuestas de hogares, y la consecución del efecto de diseño general de la encuestas, que podría estar disponible en las publicaciones de las ONEs en sus páginas web. El efecto de diseño cumple la siguiente propiedad:  $\Var_p(\hat \theta) = Deff^T \times \Var_{MAS}(\hat \theta)$  Además,

[Park et al. (2003) han propuesto](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.617.9852&rep=rep1&type=pdf)

que el efecto de diseño se puede descomponer en tres partes que se relacionan entre sí de forma multiplicativa. En primer lugar está el efecto debido a la ponderación desigual, $ Deff^W $; en segundo lugar se encuentra el efecto debido a la estratificación, $ Deff^S $; y por último se tiene el efecto debido al muestreo en varias etapas, $ Deff^C $. Por lo tanto:  $ Deff^T = Deff^W \times Deff^S \times Deff^C $  A su vez, el efecto de diseño debido a la ponderación se expresa de la siguiente manera:  $\Var_{MAS}(\hat \theta) = \frac{ \Var_W(\hat \theta)}{ Deff^{W}}$  Bajo la hipótesis de que se conociera una aproximación al efecto de diseño total y teniendo en cuenta de que el efecto de diseño y la varianza debido a la ponderación desigual se pueden calcular fácilmente con los datos de la encuesta, entonces una mejor aproximación a la varianza del estimador es:  $\Var_p(\hat \theta) = \Var_W(\hat \theta) \times\frac{ Deff^T }{ Deff^{W}}$  En general, esta aproximación será válida siempre y cuando la correlación entre los pesos de muestreo y la variable del indicador sea despreciable; en otras palabras, cuando

[el diseño de muestreo no es informativo](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.522.3665&rep=rep1&type=pdf)

para la variable de interés. Por último, es necesario tener una aproximación al $ Deff^T $ que dependerá de la desagregación de interés. En mi experiencia, podría resumir estos efectos de la siguiente manera:

- Nacional: $ Deff^T \geq 2$.

- Sexo: $ Deff^T \geq 2$.

- Tramos de edad: $ Deff^T \geq 3$.

- Zona (urbano/rural): $ Deff^T \geq 3$.

- Edad - Zona: $ Deff^T \geq 5$.

Note que, entre mayor sea la desagregación, mayor será la homogeneidad dentro de las UPMs, por ende mayor la correlación intraclase, y finalmente mayor el DEFF.
