---
title: "Subgrupos poblacionales en muestreo"
author: "Andrés Gutiérrez"
date: "2019-06-08"
categories:
  - "Surveys"
  - "Sampling"
---

Aunque el marco de referencia de la teoría de muestreo es la estimación de un parámetro de interés sobre alguna característica de interés, lo cierto es que en la práctica no solo se necesitan estimaciones que cobijen la población entera sino que también son indispensables estimaciones que involucren subgrupos poblacionales, puesto que éstos inducen una partición de la población de interés. En general, es bien sabido que cuando se habla de subgrupos poblacionales se está haciendo referencia a

**dominios de interés**

,

**estratos**

o

**postestratos**

. Cuando el investigador se enfrenta a una encuesta que tiene en cuenta subgrupos poblacionales - es decir, siempre - es indispensable conocer en qué se diferencian cada uno de ellos, pues de esto depende que la investigación arroje resultados confiables mediante el planteamiento de la mejor estrategia de muestreo.

Vamos de una vez con las formalidades de notación. Sean $U_1, \ldots, U_g, \ldots, U_G$ los subgrupos poblacionales tales que $\bigcup_{g=1}^GU_g=U$. Siendo $N_g$ el tamaño absoluto del subgrupo $U_g$, entonces se tiene que $\sum_{g=1}^G N_g=N$. A partir de las anteriores definiciones, se han planteado algunas diferencias y similitudes entre cada uno de ellos. A continuación las resumo rápidamente:

- **Dominios de interés: ** Este tipo de subgrupos poblacionales son aquellos para los cuales se requieren estimaciones separadas. Estos requerimientos se planean en la etapa de diseño para asegurar que el diseño de la muestra sea tal que al momento de la recolección de la información exista una buena cobertura en cada uno de los dominios de interés. Lo anterior sólo se puede lograr ampliando el tamaño de muestra $n$ puesto que el marco de muestreo no informa acerca de la pertenencia de los individuos a los dominios de interés. Un aspecto importante de esta clase de subgrupos poblacionales es que el número de individuos en la muestra que pertenecen a un dominio $n_d$ de interés es siempre aleatorio, y para algunos dominios particulares puede llegar a ser muy pequeño. Por otro lado el tamaño absoluto de cada dominio $N_d$ no se conoce ni antes de la etapa de diseño ni después de la etapa de estimación. Un ejemplo claro de estos subgrupos es la condición de ocupación, la condición de pobreza, la rama de actividad, entre otros.

- **Estratos: ** Cuando el marco de muestreo permite conocer la pertenencia de todos los individuos de la población a un subgrupo poblacional, se dice que esta clase de subgrupos se llaman estratos. Más aun, cuando se sabe que la característica de interés tiene un comportamiento distinto en cada uno de los estratos y se planea un diseño de muestreo que tenga en cuenta este aspecto mediante la selección aleatoria de unidades en cada uno de los estratos, se dice que el diseño de muestreo es estratificado. El aspecto fundamental de esta clase de subgrupos poblacionales es que el conocimiento de la pertenencia de los individuos a los estratos se incorpora en la etapa de diseño de la muestra. Nótese que a diferencia de los dominios, en los estrato se conoce tanto $N_h$ como $n_h$ antes de la etapa de estimación. Un ejemplo claro de estos subgrupos son las zonas urbanas o rurales, regiones y municipios.

- **Postestratos: ** La propiedad que caracteriza a este tipo de subgrupos poblacionales es que aunque en la etapa de diseño el tamaño del postestrato $N_g$ es conocido, se desconoce el número de individuos que pertenecerán al postestrato $n_g$ en la muestra realizada. Un ejemplo claro de estos subgrupos son los grupos etarios, el sexo o la etnia que, si bien no son utilizadas en la fase de diseño, sí se utilizan sus proyecciones demográficas en la fase de análisis para analizar mejorar la eficiencia de los estimadores. Al respecto Sarndal, Swensson & Wretman (1992) afirma que existen dos situaciones en las cuales se presenta esta situación, llamada comúnmente postestratificación:  - Cuando el marco de muestreo es tal que se conoce la pertenencia de todos los elementos a los subgrupos poblacionales pero el investigador decide no utilizar esta información en la etapa de diseño. Las razones para esto son diversas pero principalmente se decide obviar este tipo de información por practicidad logística. Una vez que se ha realizado la selección de la muestra, se observa la característica de interés $y_k$ en los individuos tales que $k \in s$. El investigador decide utilizar la información auxiliar de pertenencia a los postestratos en la etapa de estimación para mejorar la eficiencia de la estrategia de muestreo, en particular del estimador propuesto. - Mediante alguna fuente de información confiable se conocen los tamaños absolutos $N_g$ de cada subgrupo poblacional aunque se desconoce la pertenencia de los individuos a los subgrupos pues el marco de muestreo presenta esta deficiencia. Después de la etapa de diseño, se observa la característica de interés y se pregunta acerca de la pertenencia de los individuos seleccionados en los postestratos de tal forma que en la etapa estimación se utiliza esta información para mejorar la eficiencia de los estimadores de los parámetros de interés.

Después de valorar mis años de experiencia en el mundo del muestreo, las encuestas y las estadísticas oficiales, puedo afirmar que el análisis apropiado de una encuesta no puede pasar por alto las diferencias de estos subgrupos. Es más, el diseño y rediseño de las encuestas se basan fundamentalmente en la búsqueda de estos subgrupos en la población. En todas las encuestas de hogares que se planean en América Latina se buscan investigar fenómenos asociados a subgrupos poblacionales que se encuentran dispersos en la geografía de los países y podría especificar los siguientes aspectos:

1. El tamaño de muestra de una encuesta *siempre* se basa en la incidencia de un fenómeno que clasifica a la población en algún dominio de interés.

2. Este tamaño de muestra *siempre* se reparte entre los diferentes estratos geográficos para mejorar la eficiencia del levantamiento de la información y del diseño de muestreo.

3. En *muchas ocasiones*, las proyecciones demográficas sobre los post-estratos son utilizadas en la fase de estimación para mejorar la precisión de los estimadores.
